### ISSUE TITLE
[Remove Request] www.houzz.com (Looks like false-positive)

### ISSUE THREAD

**Issue by PeterDaveHello** [blocklistproject/Lists#1018]
URL you wish to be removed:

- www.houzz.com

Why you believe this to be a false positive:

Checked with many different protective DNS services and OSINT sources(using https://github.com/PeterDaveHello/chkdomain), none of these OSINT sources found this domain:

> 
> Running dig/nslookup over 11 secure DNS:
>  - CleanBrowsing (185.228.168.9) ... OK! (houzz.map.fastly.net. 146.75.112.93)
>  - Cloudflare (1.1.1.2) ... OK! (houzz.map.fastly.net. 151.101.0.93 151.101.64.93 151.101.128.93 151.101.192.93)
>  - Comodo (8.26.56.26) ... OK! (houzz.map.fastly.net. 146.75.48.93)
>  - CONTROL D (76.76.2.1) ... OK! (houzz.map.fastly.net. 199.232.44.93)
>  - dns0.eu (193.110.81.0) ... OK! (houzz.map.fastly.net. 199.232.168.93)
>  - OpenDNS (208.67.222.222) ... OK! (houzz.map.fastly.net. 151.101.128.93 151.101.192.93 151.101.0.93 151.101.64.93)
>  - Quad101 (101.101.101.101) ... OK! (houzz.map.fastly.net. 199.232.44.93)
>  - Quad9 (9.9.9.9) ... OK! (houzz.map.fastly.net. 151.101.128.93 151.101.192.93 151.101.64.93 151.101.0.93)
>  - SafeDNS (195.46.39.39) ... OK! (houzz.map.fastly.net. 146.75.112.93)
>  - UltraDNS (156.154.70.2) ... OK! (houzz.map.fastly.net. 151.101.76.93)
>  - Yandex (77.88.8.2) ... OK! (houzz.map.fastly.net. 151.101.36.93)
> 
> Running dig/nslookup over 6 AD(and tracker)-blocking DNS:
>  - AdGuard (94.140.14.14) ... OK! (houzz.map.fastly.net. 146.75.112.93)
>  - AhaDNS (5.2.75.75) ... OK! (houzz.map.fastly.net. 151.101.36.93)
>  - CONTROL D (76.76.2.2) ... OK! (houzz.map.fastly.net. 151.101.104.93)
>  - dnsforge.de (176.9.93.198) ... OK! (houzz.map.fastly.net. 146.75.120.93)
>  - OVPN (192.165.9.157) ... OK! (houzz.map.fastly.net. 151.101.84.93)
>  - Tiarap (188.166.206.224) ... OK! (houzz.map.fastly.net. 199.232.44.93)
> 

>
> AlienVault Open Threat Exchange
>   - https://otx.alienvault.com/indicator/domain/www.houzz.com
> Bitdefender TrafficLight
>   - https://trafficlight.bitdefender.com/info/?url=https%3A%2F%2Fwww.houzz.com
> Google Safe Browsing
>   - https://transparencyreport.google.com/safe-browsing/search?url=www.houzz.com
> Kaspersky Threat Intelligence Portal
>   - https://opentip.kaspersky.com/www.houzz.com?tab=web
> McAfee SiteAdvisor
>   - https://siteadvisor.com/sitereport.html?url=www.houzz.com
> Norton Safe Web
>   - https://safeweb.norton.com/report/show?url=www.houzz.com
> OpenDNS
>   - https://domain.opendns.com/www.houzz.com
> URLVoid
>   - https://www.urlvoid.com/scan/www.houzz.com/
> urlscan.io
>   - https://urlscan.io/domain/www.houzz.com
> VirusTotal
>   - https://www.virustotal.com/en/domain/www.houzz.com/information/
> Yandex Site safety report
>   - https://yandex.com/safety/?l10n=en&url=www.houzz.com

Their webpage and social media pages look pretty normal.

The houzz.com domain is also confirmed as top 100k domains in many different lists, including alexa, builtwith, cloudflare, domcop, majestic, statvoo, tranco and umbrella. Marked whitelisted on AlienVault OTX(https://otx.alienvault.com/indicator/domain/www.houzz.com)

List it is on:

Didn't see it in the other lists.

Other info you think we should know:

I don't have further details. Just OSINT resources.

**Comment by gap579137** [comment]
Closed with merge
