### ISSUE TITLE
[Remove Request] - api.account.xiaomi.com

### ISSUE THREAD

**Issue by yoshimo** [blocklistproject/Lists#1019]
URL you wish to be removed:

api.account.xiaomi.com

Why you believe this to be a false positive:
it is used for connecting a Xiaomi device to Xiaomi services like FindMyDevice or unlocking the bootloader

List it is on:

- ads.txt
- alt-version/ads-nl.txt

Other info you think we should know:

**Comment by gap579137** [comment]
Closed with merge
