### ISSUE TITLE
[Remove Request] - hhcdn.ru

### ISSUE THREAD

**Issue by mtxadmin** [blocklistproject/Lists#1025]
URL you wish to be removed:

hhcdn.ru

Why you believe this to be a false positive:

it is a static domain of hh.ru, Russian biggest job site. Not as big as Linkedin, but way more comfortable. Clearly false positive

List it is on:

Other info you think we should know:

**Comment by gap579137** [comment]
This issue was completed using our review process and will be included in the next merge.
