### ISSUE TITLE
[Remove Request] - someone added a bunch on non fraud domains to fraud list.

### ISSUE THREAD

**Issue by GregoryGHarding** [blocklistproject/Lists#1028]
as the title says, someone added a bunch on non fraud domains to fraud list.

examples
reddit
bungie
microsoft
etc

consider a rollback.

**Comment by iam-py-test** [comment]
What specific domains do you think are false positives? For example, I don't see `reddit.com` in the list so am unsure what you mean by *reddit*.
I did notice line 359 was just
> .net

**Comment by GregoryGHarding** [comment]
> What specific domains do you think are false positives? For example, I don't see `reddit.com` in the list so am unsure what you mean by _reddit_.
> 
> <style>details{ color: red; }</style>
> Unrelated mistakes
> I did notice a few minor mistakes: Line 359 was just > .net
> And `6.gp` is a URL shortener not fraud.

bungie.net
help.bungie.net
reddit.com
a load of microsoft and xbox related URLS that i cant remember
i had to disable the fraud blocklist in order to gain back access. too many individual URLs to whitelist otherwise

**Comment by gap579137** [comment]
I’ll take ownership of that one. We are working with some new scripts and had a couple issues. I’ll get it fixed tomorrow. 

My apologies

**Comment by PeterDaveHello** [comment]
It's now blocking massive services including LINE and App Store. The specific domains including gwz.line.naver.jp, obs.line-scdn.net, profile.line-scdn.net, stickershop.line-scdn.net, 41-courier2.push.apple.com, gsp-ssl.ls.apple.com, gsp64-ssl.ls.apple.com and many.

**Comment by jonnycastaway** [comment]
And there a lot more:
tagesschau.de
ntv.de
amazon.de <- really cool on prime day 2 !! not
init.push.apple.com
api.amazonalexa.com

ans much more

**Comment by CnuPuH** [comment]
Hi all.
The problem is due to an incorrect entry in the "adguard_fraud-ags" sheet.
Line 359 is ".net"

**Comment by coldcue** [comment]
Shouldn't it have some sort of sanity check? It blocked major services and caused a big problem in my network.

**Comment by couladin** [comment]
It's not just one bad line:

```
$ wget https://github.com/blocklistproject/Lists/raw/master/fraud.txt
$ egrep -vn "^0.0.0.0|^#" fraud.txt
359:.net
1635:pany
1651:.net
1653:.co.uk
```

Blocking all of `.net` and `.co.uk`.

**Comment by iam-py-test** [comment]
> Blocking all of .net and .co.uk.

Luckily, Windows and GNU/Linux doesn't actually view `.net` in a HOSTs file as "block all .net websites", though other software might.

**Comment by gap579137** [comment]
> Shouldn't it have some sort of sanity check in the CI pipeline, so this would never happen again?

Yes we really should… problem is we lost our main CI person 😢

**Comment by Write** [comment]
Lost two hours thinking my OPNsense had issue with some ssl domains lmao omggggggggggggggg

**Comment by TheGITofTeo997** [comment]
I can confirm this, for example twitch and gigabyte websites won't work and there are many others

**Comment by gap579137** [comment]
We have done a complete roll back. Please create a new issue if you are still facing problems
