### ISSUE TITLE
[Remove Request] - whole .net on fraud list

### ISSUE THREAD

**Issue by celevra** [blocklistproject/Lists#1029]
URL you wish to be removed:
.net

Why you believe this to be a false positive:
because its a top level domain

List it is on:
frau line 359

Other info you think we should know:
how could that happen?

**Comment by iam-py-test** [comment]
Someone has already reported this: https://github.com/blocklistproject/Lists/issues/1028#issuecomment-1632281555

**Comment by gap579137** [comment]
Closed with roll back
