### ISSUE TITLE
false positive, I think, http://geekxgirls.com/

### ISSUE THREAD

**Issue by blackskye-sx** [blocklistproject/Lists#104]
URL you wish to be removed:
geekxgirls.com

Why you believe this to be a false positive:
found under porn.txt, but the site isn't really porn. It tends to be cosplay and geek topics.

List it is on:
porn.txt

Other info you think we should know:

**Comment by gap579137** [comment]
Looking into this.

**Comment by gap579137** [comment]
This site has suggestive material but is not "porn" it has been removed. Thank you
