### ISSUE TITLE
False positive ldex.exchange

### ISSUE THREAD

**Issue by jondubois** [blocklistproject/Lists#105]
URL you wish to be removed:

`ldex.exchange`

Why you believe this to be a false positive:

It appears to have been used in a phishing attack at some point in the past (pretending to be https://idex.market/).
But this domain has since changed ownership and note that the gTLD is different from the one owned by idex.

List it is on:

https://blocklistproject.github.io/Lists/phishing.txt

**Comment by gap579137** [comment]
Looking into this

**Comment by jondubois** [comment]
Also, note that this was an issue with MetaMask and they have since removed `ldex.exchange` from their blacklist: https://github.com/MetaMask/eth-phishing-detect/pull/3891

**Comment by gap579137** [comment]
This has been fixed. Thank you for your helping with the lists.
