### ISSUE TITLE
mail.gandi.net probably shouldn't be in abuse.txt

### ISSUE THREAD

**Issue by emory** [blocklistproject/Lists#108]
URL you wish to be removed: `mail.gandi.net`

Why you believe this to be a false positive: It's where all customers of Gandi (.fr or .net) end up having mail delivered if they use Gandi's IMAP service instead of redirecting elsewhere. It may also be where CalDAV calendar subs live, I didn't investigate very far except I saw denied requests for mail.gandi.net coming from my iPad and I immediately added it to the Allowed list and am here to do my duty as a network ciltizen.

List it is on: abuse.txt

Other info you think we should know: Gandi is great for DNS registration, their PaaS service is a really good way to run a Wordpress blog without having to manage database and software upgrades. I would be really surprised if anyone had a bad encounter with Gandi or an employee of Gandi. They've always been amazing to me and I've been a customer for at least a decade.

**Comment by gap579137** [comment]
This has been fixed. Thank you for your helping with the lists.
