### ISSUE TITLE
crazyegg.com

### ISSUE THREAD

**Issue by blackskye-sx** [blocklistproject/Lists#109]
**URL you wish to be removed:**
crazyegg.com

**Why you believe this to be a false positive:**
Partial false positive? The company appears to work with website designers to analyze their websites. So definitely belongs in tracking, and possibility in ads. But I don't think it belongs abuse or malware.

**List it is on:**
abuse
malware
tracking (do not remove?)
ads (do not remove?)

Other info you think we should know:

**Comment by gap579137** [comment]
This has been fixed. Thank you for your helping with the lists.
