### ISSUE TITLE
dmd.metaservices.microsoft.com

### ISSUE THREAD

**Issue by daberlin** [blocklistproject/Lists#110]
URL you wish to be removed:
dmd.metaservices.microsoft.com

Why you believe this to be a false positive:
It causes recurring Windows 10 error log entries:
"DeviceSetupManager" , event ID "201"
A connection to the Windows Metadata and Internet Services (WMIS) could not be established.

List it is on:
ads

Other info you think we should know:

**Comment by gap579137** [comment]
This has been fixed. Thank you for your helping with the lists.
