### ISSUE TITLE
meta.wikimedia.org

### ISSUE THREAD

**Issue by j5k** [blocklistproject/Lists#111]
URL you wish to be removed:
[meta.wikimedia.org](meta.wikimedia.org)

Why you believe this to be a false positive:
"Meta-Wiki, the global community site for the Wikimedia Foundation's projects and related projects, from coordination and documentation to planning and analysis."

List it is on:
Ads

Other info you think we should know:

**Comment by gap579137** [comment]
This has been fixed. Thank you for your helping with the lists.
