### ISSUE TITLE
Rutracker.wiki false positive

### ISSUE THREAD

**Issue by Kexogg** [blocklistproject/Lists#112]
URL you wish to be removed:
rutracker.wiki
www.rutracker.wiki

Why you believe this to be a false positive:
This is FAQ section of russian torrent tracker "rutracker.org". There is no malware on this site, just instructions on how to download torrents from the main site.

List it is on:
malware

Other info you think we should know:
This site needs to be moved to the "Torrent" list.

**Comment by gap579137** [comment]
This has been fixed. Thank you for your helping with the lists.
