### ISSUE TITLE
False positive: app.powerbigov.us

### ISSUE THREAD

**Issue by BlueSpaceCanary** [blocklistproject/Lists#113]
URL you wish to be removed:
app.powerbigov.us

Why you believe this to be a false positive:
Power BI is a MS service for government sites. See here for docs: https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview 

For example, COVID data charts on the SF city government site (link: https://data.sfgov.org/stories/s/dak2-gvuj) are incorrectly blocked as they're hosted on this domain.

List it is on:
Phishing

Other info you think we should know:
N/A

**Comment by gap579137** [comment]
This has been fixed. Thank you for your helping with the lists.
