### ISSUE TITLE
[Add request] thotsluts.com to porn list

### ISSUE THREAD

**Issue by DragonflyPacificGallery** [blocklistproject/Lists#1156]
URL you wish to be added:

thotsluts.com

Why you believe this should be added:

site for porn streams

Add to list:

porn.txt

Other info you think we should know:

**Comment by spirillen** [comment]
What a surprise... https://github.com/mypdns/matrix/commit/9961e9ea7404a1e1a1e23a925b6cafe535740b47

Why do you not just copy the hole list and suggest a license change a give the full credit to My Privacy DNS as you are required to https://github.com/mypdns/matrix/blob/master/source/LICENSE?

same words like in https://github.com/blocklistproject/Lists/pull/1157
