### ISSUE TITLE
tinurl on malware list

### ISSUE THREAD

**Issue by dovecode** [blocklistproject/Lists#120]
URL you wish to be removed:
tinyurl.com

Why you believe this to be a false positive:
This isn't malware. It might be used to point to malware sites, but in itself it isn't and is used by many legitimite users.

List it is on:
malware

Other info you think we should know:
You guys keep adding URL shorteners to the lists. Please stop!

**Comment by blocklistproject** [comment]
This has been resolved. Thank you for letting us know.
