### ISSUE TITLE
[Remove Request] - conferences.sigcomm.org

### ISSUE THREAD

**Issue by larseggert** [blocklistproject/Lists#121]
URL you wish to be removed:
conferences.sigcomm.org

Why you believe this to be a false positive:
conferences.sigcomm.org hosts web sites for various conferences sponsored by ACM SIGCOMM. The password for one of those sites was hacked in 2019 and phishing content was uploaded, but has long been removed. (If you believe this is not the case, please identify the URL in question?)

List it is on:
```
alt-version/phishing-nl.txt
phishing.txt
alt-version/everything-nl.txt
everything.txt
```

Other info you think we should know:

**Comment by gap579137** [comment]
This issue has been resolved. Thank you
