### ISSUE TITLE
[Remove Request] - Ads list nytimes app failure

### ISSUE THREAD

**Issue by crt333** [blocklistproject/Lists#123]
URL you wish to be removed:
not sure, I see 26 nytimes references in the file, may be one of those or something else.

Why you believe this to be a false positive:
When running the ads list on my opnsense firewall as an unbound blacklist nytimes app fails (not connected) on both android devices (galaxy s8) on the network. Removing Ads list and keeping other lists working results in nytimes app success.

List it is on:
Ads

Other info you think we should know:
Sorry I can't be more specific, but nytimes app failing seems repeatable.

**Comment by crt333** [comment]
I ran the Ads list and whitelisted nytimes hosts one by one until the android app worked again, it seems:
    samizdat-graphql.nytimes.com
is the one that needs to be removed from the Ads list to make the android nytimes app work.

**Comment by blocklistproject** [comment]
I have removed that single URL. Please let me know if that fixes it.

**Comment by crt333** [comment]
I removed my whitelist entry and pulled down a new copy of your list to 
opnsense, and nytimes seems to work fine.

Thanks for the change!

Chris

------------------------------------------------------------------------
*From:* The Block List Project [mailto:notifications@github.com]
*Sent:* Tuesday, November 10, 2020, 10:10 AM
*To:* blocklistproject/Lists <Lists@noreply.github.com>
*Cc:* crt333 <chris@thewalt.us>, Author <author@noreply.github.com>
*Subject:* [blocklistproject/Lists] [Remove Request] - Ads list nytimes 
app failure (#123)
