### ISSUE TITLE
[Add request] https://baby-walz-sale.shop/

### ISSUE THREAD

**Issue by NCIceWolf** [blocklistproject/Lists#1246]
URL you wish to be added:
https://baby-walz-sale.shop/

Why you believe this should be added:
Fake shop, prices way too low and not affiliated with Baby-Walz

Add to list:
scam, phishing

Other info you think we should know:

**Comment by spirillen** [comment]
Hmm

Can you show why this domain should be an active threat.

![image](https://github.com/blocklistproject/Lists/assets/44526987/c82b6247-9dd6-4d8e-a243-7f9ecb2167a2)

**Comment by NCIceWolf** [comment]
Seems there were enough complains to take this site down already.
It is neither reachable anymore, nor is the sites registration valid anymore. Maybe they found another domain already.

That's how it looked yesterday:
![Screenshot_20240617-063350](https://github.com/blocklistproject/Lists/assets/127289023/31d2db08-5a7f-4efd-9e58-4ec85a075613)
![Screenshot_20240617-063407](https://github.com/blocklistproject/Lists/assets/127289023/6e9279e1-b843-40d3-9cbc-1c5964fa662b)

**Comment by spirillen** [comment]
A shame you didn't added the dumps in the OP. Another time when you runs into phishing, you should add them to both [https://github.com/mypdns/matrix/issues](https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=&projects=&template=domain_blacklist.yml) and [https://github.com/mitchellkrogza/Phishing](https://github.com/mitchellkrogza/phishing/issues/new?assignees=mitchellkrogza%2Cfunilrys&labels=&projects=&template=phishing.yml)
