### ISSUE TITLE
[Remove Request] - HubSpot client scripts

### ISSUE THREAD

**Issue by jgetto** [blocklistproject/Lists#129]
**URL you wish to be removed:**
```
hs-scripts.com
js.hs-scripts.com
js.hscta.net
js.hsforms.net
js.hsleadflows.net
js.hscollectedforms.net
```

**Why you believe this to be a false positive:**

These scripts power different features of a HubSpot customer's site. Blocking them can prevent the site from rendering and functioning properly.

`hs-scripts.com` and `js.hs-scripts.com` : This is the top-level script loader. It loads the other scripts that power different features. It has no tracking or analytics. See https://knowledge.hubspot.com/reports/what-is-the-hs-scripts-embed-code-loading-on-my-website for details

`js.hscta.net` : Renders CTA buttons

`js.hsforms.net` : Renders Forms

`js.hsleadflows.net` : Renders dynamic pop-in forms

`js.hscollectedforms.net` : Integrates non-HubSpot forms. See https://knowledge.hubspot.com/forms/use-non-hubspot-forms

**List it is on:**

Ads

**Other info you think we should know:**

There are a few other HubSpot scripts that are slightly miscategorized (e.g. under Ads when they should be Tracking). I'm happy to file an issue for those as well if that would be helpful.

**Comment by blocklistproject** [comment]
This has been resolved
