### ISSUE TITLE
cs11.wpc.v0cdn.net (Windows-Updates)

### ISSUE THREAD

**Issue by hduelme** [blocklistproject/Lists#13]
URL you wish to be removed: cs11.wpc.v0cdn.net

Why you believe this to be a false positive: The Pi-hole is blocking Windows-Updates cause of this domain:
![Bildschirmfoto vom 2020-07-17 00-30-35](https://user-images.githubusercontent.com/46139144/87729156-f966c200-c7c4-11ea-8d01-3683589a54f2.png)
If it is needed for Windows-Updates it's probably not ads.

List it is on: ads

Other info you think we should know: Other Windows-Update-servers may be blocked cause of this too.

**Comment by blocklistproject** [comment]
This has be resolved
