### ISSUE TITLE
[Remove Request] - nosto.com

### ISSUE THREAD

**Issue by zappe** [blocklistproject/Lists#132]
URL you wish to be removed: nosto.com

Why you believe this to be a false positive: Needed for kronansapotek.se to work

List it is on: Tracking

Other info you think we should know:

**Comment by obeho** [comment]
Please dont whitelist this domain. From their website, `data-fueled personalization & Action your customer data & Use behavioral data & analyzes shoppers’ online and offline activity` . This is far worse than a tracker.

**Comment by obeho** [comment]
Hello, the updated list shows `# nosto.com Issue 132`. Does this mean, the domain is allowed or blocked?

TIA
