### ISSUE TITLE
[Remove Request] - mandrillapp.com

### ISSUE THREAD

**Issue by Bilibox** [blocklistproject/Lists#133]
URL you wish to be removed:
mandrillapp.com

Why you believe this to be a false positive:
This is used by Corporations for business usage and is required for certain applications to load.

List it is on:
https://github.com/blocklistproject/Lists/blob/master/tracking.txt

Other info you think we should know:

**Comment by gap579137** [comment]
It may be needed for certain apps to load but it is "tracking" as such it belongs on the list. If you are in need of this website, I would recommend white listing it.
