### ISSUE TITLE
[Remove Request] - ibx.key.com

### ISSUE THREAD

**Issue by PazzoBread** [blocklistproject/Lists#134]
URL you wish to be removed: ibx.key.com

Why you believe this to be a false positive: Used to log into keybank's online banking system

List it is on: https://blocklistproject.github.io/Lists/alt-version/ransomware-nl.txt 

Other info you think we should know:

**Comment by gap579137** [comment]
Did not find this on our list. Please feel free to reopen with a screenshot

**Comment by PazzoBread** [comment]
![7FA8425E-5F14-4C1B-BBF0-36FF43D51BF5](https://user-images.githubusercontent.com/75051642/101994349-d0712d00-3c8f-11eb-87c5-5fb892951f23.jpeg)

This is the list I found it on: https://blocklistproject.github.io/Lists/alt-version/phishing-nl.txt (wrong link before)
