### ISSUE TITLE
[Remove Request] - priority-static-api.nkstatic.com

### ISSUE THREAD

**Issue by aclelland** [blocklistproject/Lists#141]
URL you wish to be removed: priority-static-api.nkstatic.com

Why you believe this to be a false positive:
Hi, developer at Ninja Kiwi here :) We've had a bunch of players who're having trouble with our nkstatic.com subdomains being added to various block lists. The content downloaded from this domain is stuff like profile avatars, content updates and isn't used for any tracking/analytics. 

List it is on: tracking.txt

Other info you think we should know:

**Comment by gap579137** [comment]
This issue has been resolved. Thank you!
