### ISSUE TITLE
[Remove Request] - Sitetracker.com

### ISSUE THREAD

**Issue by Ahmad6519** [blocklistproject/Lists#146]
URL you wish to be removed:
https://www.sitetracker.com

Why you believe this to be a false positive:
On Blocklist: https://blocklist-tools.developerdan.com/blocklists 
This is a legit website for a project management solution. This is not a gambling website.

List it is on:
https://blocklist-tools.developerdan.com/blocklists

Other info you think we should know: 
[Blocklist Tool.pdf](https://github.com/blocklistproject/Lists/files/5703840/Blocklist.Tool.pdf)

**Comment by gap579137** [comment]
Believe this has already been removed. Please check again.
