### ISSUE TITLE
[Remove Request] - https://web.whatsapp.com/

### ISSUE THREAD

**Issue by adzimzf** [blocklistproject/Lists#151]
URL you wish to be removed:
https://web.whatsapp.com/

Why you believe this to be a false positive:
this is for whatsapp web or dekstop

List it is on:
https://blocklistproject.github.io/Lists/facebook.txt

Other info you think we should know:

**Comment by S-B-3** [comment]
WhatsApp is Facebook!

**Comment by blocklistproject** [comment]
This will remain on the list because WhatsApp is owned by FB
