### ISSUE TITLE
users.telenet.be

### ISSUE THREAD

**Issue by mkb2091** [blocklistproject/Lists#16]
URL you wish to be removed: users.telenet.be

Why you believe this to be a false positive: It blocks access to http://users.telenet.be/MySQLplaylist/pi-hole.pdf which is a pdf about using Pi-Hole

List it is on: malware.txt

Other info you think we should know:

**Comment by MTShipp** [comment]
That full path may be legit for sharing that file but the site “users.telenet.be” is listed many times as a source for malware. I am just a user of this list so if the owners want to remove it from the blacklist, of course they can, but I will have to add it to my local blacklist. I think that is a compromise :)

**Comment by blocklistproject** [comment]
Looking into this

**Comment by blocklistproject** [comment]
Unfortunately this will not be unblocked at this time. If you feel that this need further consideration please recreate an issue with supporting reasons and we will be happy to look into this further. Thank you
