### ISSUE TITLE
[Add request] RedGifs

### ISSUE THREAD

**Issue by derekantrican** [blocklistproject/Lists#160]
URL you wish to be added: `redgifs.com` (and any subdomains)

Why you believe this should be added: Most of the pornographic gifs shared on reddit are now through this site

Add to list: porn.txt

Other info you think we should know:

**Comment by Trainax** [comment]
> URL you wish to be added: `redgifs.com` (and any subdomains)
> 
Hello. Are you able to provide all the subdomains you have encountered from this website?

Specific domains/subdomains can be blacklisted while wildcards can't be inserted in the lists as there are some devices which don't support wildcards

**Comment by derekantrican** [comment]
I am not sure of any subdomains (and don't want to try investigating). Blocking the domain itself should be fairly effective

**Comment by Trainax** [comment]
Ok. I think gifdeliverynetwork.com should also be added because it's one of the domains used for RedGIFs.

[Source](https://www.reddit.com/r/redgifs/comments/klou8y/gifdeliverynetworkcom/)
