### ISSUE TITLE
Why not provide an aggregated list?

### ISSUE THREAD

**Issue by nodje** [blocklistproject/Lists#167]
Just stumbled upon your project while looking for good lists of domain to block.
And wondering why you wouldn't want to provide an aggregated list of all these specialized lists?

I mean it seems that any sensible user would have to take all of them or almost anyway.
A list or a command to grab them all and concatenate them in a place seem to be in order!

Or am I missing something on how this should be used?

**Comment by Trainax** [comment]
The *everything* list contains all the domains which are found on the other lists.

- [Link](https://blocklistproject.github.io/Lists/everything.txt)
- [Link w/o leading IP](https://blocklistproject.github.io/Lists/alt-version/everything-nl.txt)

Please keep in mind this list is **very** big! Also, if you choose to use this the entire list must be downloaded every time something gets updated, while if you use the smaller lists only those which have been changed get downloaded on your device reducing wear and tear on the SD card if you are using it

**Comment by blocklistproject** [comment]
> The *everything* list contains all the domains which are found on the other lists.
> 
> 
> 
> - [Link](https://blocklistproject.github.io/Lists/everything.txt)
> 
> - [Link w/o leading IP](https://blocklistproject.github.io/Lists/alt-version/everything-nl.txt)
> 
> 
> 
> Please keep in mind this list is **very** big! Also, if you choose to use this the entire list must be downloaded every time something gets updated, while if you use the smaller lists only those which have been changed get downloaded on your device reducing wear and tear on the SD card if you are using it

This is a great reply. Thank you for answering their question! Please let me know if there is somewhere I can "buy you a coffee"

**Comment by Trainax** [comment]
> This is a great reply. Thank you for answering their question! Please let me know if there is somewhere I can "buy you a coffee"

No need to buy me a coffee! I find this project really interesting so I want to collaborate when I can

**Comment by nodje** [comment]
Sorry for not seeing the obvious!~

I guess putting `everything.txt` in evidence would just do.

I get your point for the upgrade problem though, but unfortunately there's no mecanism that would allow to put all files in something like `/etc/hosts.d/` that would automatically pick up updates.

I'm not familiar with PiHole, but on a regular unix system, you have to combine everything into a unique `hosts` file anyway. So whether only one file is updated or everything, it boils down to the same procedure: pull latest and run a script to combine all you want into your `/etc/hosts`

I found that this project https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#dns-server
had a clever way to provide access to their list: a DNS server.

That's another story and it creates other problems, but it is an easy to use solution.
