### ISSUE TITLE
Why not provide an aggregated master list ?

### ISSUE THREAD

**Issue by nodje** [blocklistproject/Lists#168]
Just stumbled upon your project while looking for good lists of domain to block.
And wondering why you wouldn't want to provide an aggregated list of all these specialized lists?

I mean it seems that any sensible user would have to take all of them or almost anyway.
A list or a command to grab them all and concatenate them in a place seem to be in order!

Or am I missing something on how this should be used?

**Comment by Trainax** [comment]
Duplicate of #167
