### ISSUE TITLE
[Remove Request] - ing-diba.de

### ISSUE THREAD

**Issue by Wunderharke** [blocklistproject/Lists#169]
URL you wish to be removed:

ing-diba.de

Why you believe this to be a false positive:

Redirects to the original german ING website ing.de.

List it is on:

phishing

Other info you think we should know:

The domain is used by the official german ING Banking app. Login is not working while ing-diba.de is blocked.

**Comment by gap579137** [comment]
This issue has been addressed. Thank you!
