### ISSUE TITLE
Removal Request

### ISSUE THREAD

**Issue by trustinsec** [blocklistproject/Lists#18]
URL you wish to be removed:

http://stackpathcdn.com/
http://stackpathcdn.com/
http://www.stackpath.com/

Why you believe this to be a false positive: 
Please be advised that the domains listed are legitimate domains that are registered to StackPath a content delivery network (CDN)  

List it is on:
ads.txt
gambling.txt

Other info you think we should know:

**Comment by blocklistproject** [comment]
Completed
