### ISSUE TITLE
[Add request] Block ads from mdn.net

### ISSUE THREAD

**Issue by Anthael** [blocklistproject/Lists#183]
URL you wish to be added:
s0.2mdn.net
*.*mdn.net

Why you believe this should be added:
To many ads in articles

Add to list: Ads

Other info you think we should know:
https://s0.2mdn.net/8574600/1611590487141/300x600_Palette_Launch_Awareness_V3/index.html

**Comment by gap579137** [comment]
Can you provide more details like where you see the ads?

**Comment by blocklistproject** [comment]
This will be closed with no other updates. Please reopen if you have additional info.
