### ISSUE TITLE
[Add request] Block ads from google ads iframe

### ISSUE THREAD

**Issue by Anthael** [blocklistproject/Lists#185]
URL you wish to be added:
https://*.safeframe.googlesyndication.com

Why you believe this should be added:
Generated ads

Add to list: ads

Other info you think we should know:
https://www.frandroid.com/marques/tesla/834808_la-nouvelle-tesla-model-s-est-la-interieur-renouvele-plus-rapide-et-plus-grande-autonomie#utm_medium=e-mail&utm_source=newsletter_hebdo&utm_campaign=20210129

the google ads appears at least 3 times

**Comment by gap579137** [comment]
Done
