### ISSUE TITLE
[Add request] 

### ISSUE THREAD

**Issue by Syrup** [blocklistproject/Lists#187]
URL you wish to be added:
rule34.xxx
Why you believe this should be added:
NSFW site
Add to list:
porn.txt
Other info you think we should know:
when you are on the main page there may be nothing that smells like nsfw but, if you have done a search that's where the NSFW is

**Comment by ahmmedmohamed** [comment]
Can you block the following link in the pics

FYI

**Comment by Trainax** [comment]
@Syrup Why did you close this issue?

Was the website you asked to be added a false positive?

**Comment by Syrup** [comment]
Maybe as long as you haven't done the search, it's fine
