### ISSUE TITLE
Format issue

### ISSUE THREAD

**Issue by naude-r** [blocklistproject/Lists#188]
some records have incorrect formatting, ie a space instead of newline.

ads.txt contain two such instances:
admaym.com cs.genieesspv.jp
um2.eqads.com x.skimresources.com

in addition there is also:
admaym.comcs.genieesspv.jp
um2.eqads.comx.skimresources.com
watson.microsoft.comwebpooldm21a08.infra.lync.comwww.linkedin.comwww.msn.comx.skimresources.com

these might need additional newlines?

**Comment by MokraCota** [comment]
which files?

**Comment by naude-r** [comment]
ads.txt in the repo. ads-nl.txt when downloading.
