### ISSUE TITLE
[Remove Request] - best-cons.ru

### ISSUE THREAD

**Issue by kulikov-a** [blocklistproject/Lists#190]
URL you wish to be removed:
best-cons.ru

Why you believe this to be a false positive:
legal software distributor

List it is on:
phishing

Other info you think we should know:

**Comment by MokraCota** [comment]
Can you confirm that this company really exists?
Google streetview, shows that the address stated is a residence building.

**Comment by kulikov-a** [comment]
Yes. contractor of our company. information services in construction
legal addresses in Russia are sometimes in garages and cowsheds)
