### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by xabi62** [blocklistproject/Lists#192]
URL you wish to be added:
cpasbien.sh
cpasbienss.fr
Why you believe this should be added:
torrent
Add to list:
Torrent
Other info you think we should know:

**Comment by ahmmedmohamed** [comment]
Dear project members

Reasons to block torrents is that network is open to everyone in a house.
House may have 1 - 10 familys
Family may have 2 - 5 members

Most of the countires use allowance (MB) base ISP packages
 e. g 1 TB for 1 month can be used if torrents is blocked.


its different people living in sperate apartments. they used their own data
packages to manage their allowance (MB)

its always better to give a torrent blocker to the user who want it.

FYI

Thank You
