### ISSUE TITLE
[Remove Request] - www.getnow.com

### ISSUE THREAD

**Issue by p-rintz** [blocklistproject/Lists#193]
URL you wish to be removed:
www.getnow.com

Why you believe this to be a false positive:
The URL www.getnow.com is used by a local online supermarket in Germany.
I think they used www.getnow.de until January this year and started to use www.getnow.com since then.

List it is on:
Abuse & Malware

Other info you think we should know:

**Comment by gap579137** [comment]
This has been fixed
