### ISSUE TITLE
[Remove Request] - pr0gramm.com

### ISSUE THREAD

**Issue by kb-elmo** [blocklistproject/Lists#194]
URL you wish to be removed:
*.pr0gramm.com (all subdomains)

except: 
escobar.pr0gramm.com (should be moved to ads list)

Why you believe this to be a false positive:
The page is a legitimate german imageboard.
They were previously hosting a monero crypto miner (on a subdomain that told the user it was now using their PC for mining) but cut ties with the associated company (Coinhive) a while ago and removed the miner from their page.
The miner on the page never ran without the users knowledge.

List it is on:
Crypto

Other info you think we should know:

**Comment by gap579137** [comment]
Going to have to look into this one. There are a lot of domains on the list and it will take some time to verify them all.

**Comment by kb-elmo** [comment]
Here's a list of the domains and their functions. Should be easy to confirm it.
Half of the subdomains don't exist anyways.

|Domain|Function|
|-|-|
|pr0gramm.com|Main page|
|www.pr0gramm.com|Main page www subdomain|
|thumb.pr0gramm.com|CDN for thumbnails|
|img.pr0gramm.com|CDN for the preview images on the page|
|full.pr0gramm.com|CDN for high resolution images|
|vid.pr0gramm.com|CDN for videos on the board|
|app.pr0gramm.com|Website for the boards own android app|
|escobar.pr0gramm.com|Ad service hosting subdomain|
|miner.pr0gramm.com|(Now disabled) miner subdomain|
|www-tb7c.pr0gramm.com|doesn't exist|
|ww.pr0gramm.com|doesn't exist|
|m.pr0gramm.com|doesn't exist|
|hans.pr0gramm.com|doesn't exist|
|hurensohn.pr0gramm.com|doesn't exist|
|avatar.pr0gramm.com|doesn't exist|
