### ISSUE TITLE
tns-sifo.se

### ISSUE THREAD

**Issue by zappe** [blocklistproject/Lists#2]
URL you wish to be removed: tns-sifo.se

Why you believe this to be a false positive: It's for surveys

List it is on: Ads and Tracking

Other info you think we should know:

**Comment by blocklistproject** [comment]
This issue has been resolved and pushed to the master branch. Thank you for your help. Due to the type of url it is it will remain on the tracking list.

Please let us know if you have any questions.

**Comment by zappe** [comment]
Why is it tracking?
That URL goes to the main site of the company.
What tracking do you see on it?

**Comment by blocklistproject** [comment]
Once I can pull it up on my desktop and read over the terms I can better determine if it should stay but my experience is that survey sites do a fair amount of tracking.

**Comment by zappe** [comment]
The domain redirects to kantarsifo.se though.

**Comment by zappe** [comment]
Any updates on this?
