### ISSUE TITLE
[Remove Request] - nllapps.com

### ISSUE THREAD

**Issue by NLLAPPS** [blocklistproject/Lists#204]
URL you wish to be removed: nllapps.com

Why you believe this to be a false positive: This our site for apps we created and it is not and advertising provider nor has any adverts on it.

List it is on:
https://blocklistproject.github.io/Lists/ads.txt
https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt

Other info you think we should know:
Hi, I am not sure why our site got in to your list. We actually use your lists that's how we noticed it. Our site is just a site for our apps and is not an advert site.

**Comment by gap579137** [comment]
This has been fixed. Apologize for the issues.
