### ISSUE TITLE
[Remove Request] - 

### ISSUE THREAD

**Issue by suresh18th** [blocklistproject/Lists#207]
URL you wish to be removed: https://www.renovationkingdom.com.au/

Why you believe this to be a false positive: Yes

List it is on: Clean Website

Other info you think we should know:
We tested this website on Magento security scan. Its clean.
Our development team scan whole website and they reported its clean.
All the firewalls and antyvirus reporting its clean.
3rd party scanners like sucuri, pcrisk, VirusTotal, Forcepoint ThreatSeeker, Comodo Valkyrie Verdict are reporting its clean.

**Comment by suresh18th** [comment]
URL you wish to be removed: https://www.renovationkingdom.com.au/ 

Why you believe this to be a false positive: 
We tested this website on Magento security scan. Its clean.
Our development team scan whole website and they reported its clean.
All the firewalls and antivirus reporting its clean.
3rd party scanners like sucuri, pcrisk, VirusTotal, Forcepoint ThreatSeeker, Comodo Valkyrie Verdict are reporting its clean.

List it is on: Clean Website list

Other info you think we should know:

**Comment by MokraCota** [comment]
"List it is on" - you need to specify the txt name where this domain is blocked.

**Comment by suresh18th** [comment]
URL you wish to be removed: https://www.renovationkingdom.com.au/

Why you believe this to be a false positive:
We tested this website on Magento security scan. It's clean.
Our development team scan the whole website and they reported it clean.
All the firewalls and antivirus reporting its clean.
3rd party scanners like sucuri, pcrisk, VirusTotal, Forcepoint ThreatSeeker, Comodo Valkyrie Verdict are reporting it's clean.

List it is on: 
https://raw.githubusercontent.com/blocklistproject/Lists/master/alt-version/phishing-nl.txt
https://raw.githubusercontent.com/blocklistproject/Lists/master/phishing.txt
https://blocklistproject.github.io/Lists/phishing.txt
https://blocklist.site/app/dl/phishing
https://v.firebog.net/hosts/static/HPHosts/Hostspsh.txt

Other info you think we should know:

**Comment by 18thtech** [comment]
Hi.

https://v.firebog.net/hosts/static/HPHosts/Hostspsh.txt still showing entry of renovationkingdom.com.au.
Can you please remove from this list as well.

Regards
Suresh
