### ISSUE TITLE
Pages that should not be considered as malware within malware.txt

### ISSUE THREAD

**Issue by jhoncorreacastillo** [blocklistproject/Lists#216]
Dear, this is to report that false positives are being taken as malware pages.

The ones that I have managed to detect are the following:

mikrotik.com.pe
mikrotikxperts.com
movistar.com.pe

These pages are trustworthy. Movistar is the page of a telephone operator, mikrotikxperts.com is a networking training page and mikrotik.com.pe is a forum to help people seeking help in mikrotik solutions

**Comment by gap579137** [comment]
This has been fixed, Thank you!
