### ISSUE TITLE
[Add] rebrandlydomain.com

### ISSUE THREAD

**Issue by ignoramous** [blocklistproject/Lists#217]
URL you wish to be added: `rebrandlydomain.com`

Why you believe this should be added: It is a tracker, and other rebrandly domains are already covered in `tracking.txt` like `myrebrandly.com`, for example.

Add to list: [`tracking.txt`](https://github.com/blocklistproject/Lists/blob/7461484/tracking.txt)

**Comment by blocklistproject** [comment]
This has been done.
