### ISSUE TITLE
[Remove Request] - crashlytics.com

### ISSUE THREAD

**Issue by aravindvnair99** [blocklistproject/Lists#218]
[Firebase Crashlytics](https://firebase.google.com/products/crashlytics) is a lightweight, realtime crash reporter that helps developers track, prioritize, and fix stability issues that erode app quality. Crashlytics saves developers troubleshooting time by intelligently grouping crashes and highlighting the circumstances that lead up to them.

I don't think Crashlytics should be blocked. It's used in various apps and is useful for a lot of developers.

**Comment by gap579137** [comment]
Please indicate what list you would like this removed from.

**Comment by aravindvnair99** [comment]
> Please indicate what list you would like this removed from.

@gap579137 My bad... It's in the `ads.txt` list.

**Comment by gap579137** [comment]
This has been fixed
