### ISSUE TITLE
[Add request] Add domains to block Samsung smart TV ads

### ISSUE THREAD

**Issue by mkleinschnitker** [blocklistproject/Lists#219]
URL you wish to be added:
- ads.samsungads.com
- cdn.samsungcloudsolution.com
- config.samsungads.com
- eu-auth2.samsungosp.com
- img-resize-cdn-prod.samsungnyc.com
- ocfconnect-shard-eu02-euwest1.samsungiotcloud.com
- osb-v2.samsungqbe.com
- scs.samsungqbe.com
- uimetadata.samsungiotcloud.com

Why you believe this should be added:
Dramatically reduces DNS requests to Samsung Smart TV

Add to list:
- ads.txt 
- or new list "smart_tv.txt"

Other info you think we should know:

**Comment by blocklistproject** [comment]
Created a new beta list "Smart TV" please let us know how it works.

**Comment by rh-fcristin** [comment]
osb-v2.samsungqbe.com record block OTA firmware updates on newer TV like QN90 and even Q60 series, both are on latest firmwares.
It possibly break also initial TV configuration along with osb-apps-v2.samsungqbe.com record, my initial issue was found when reinstalling of the Q60 via smartthings android app, the procedure was failing. After unlocking both records it works flawlessly.
