### ISSUE TITLE
[Add request] Online casino pages

### ISSUE THREAD

**Issue by mkleinschnitker** [blocklistproject/Lists#229]
URL you wish to be added:
- https://www.hyperino.com
- https://www.netbet.de
- https://www.drueckglueck.com
- https://www.platincasino.com
- https://www.merkur24.com
- https://merkur-casino.de
- https://energycasino.com
- https://de.888casino.com/
- https://slots.888wetten.de/
- https://www.onlinecasino-eu.com/
- https://www.onlinecasino.de/

Why you believe this should be added:
- german online casino and online gambling pages

Add to list:
- gambling.txt

Other info you think we should know:
- no

**Comment by blocklistproject** [comment]
These have been added. Thank you
