### ISSUE TITLE
[Remove Request] - 

### ISSUE THREAD

**Issue by VonChair** [blocklistproject/Lists#230]
URL you wish to be removed:

the-eye.eu

Why you believe this to be a false positive:
As one of the staff for the site I know this site to be fully in compliance with all DMCA take down requests. While our volunteer team may post some data which is not in the public domain, this is not intentional and we respect the rights of intellectual property owners who issue take down requests. In most cases, the reason our site is added to lists such as this is due to it's listing a directory called piracy, however this directory in accordance with our mission to archive historical data, is an archive of scene release nfo data files and metadata as well as some defunct forum site clones. There are no pirated materials in the directory. You can see for your self here:

https://the-eye.eu/public/Piracy/

List it is on:

piracy

Other info you think we should know:

It is a rather common issue that our site is blocked by such lists and it's a lot of work to keep us off of such lists. We work closely with other digital archiving groups to help preserve the history of the internet. We are all volunteers and do not profit from our work. You can read more about what we do below or visit our site or discord community.
The-Eye is a non-profit, community driven platform dedicated to the archiving and long-term preservation of any and all data including but by no means limited to... websites, books, games, software, video, audio, other digital-obscura and ideas.

Thank you for your time.

**Comment by MokraCota** [comment]
I object to the removal. Here we can see you are hosting music https://the-eye.eu/public/Music/multi-tracks/ and apps
https://the-eye.eu/public/Software/Old%20Apps/

**Comment by nektro** [comment]
> I object to the removal. Here we can see you are hosting music [..] and apps [..]

These files have long surpassed their copyright and we actively removed any DMCA requests sent to us, should we have missed one. Should you be the owner of any such files you are more than welcome to contact us here https://the-eye.eu/dmca/.

Otherwise, we have an active community on Discord of almost 34k members https://discord.com/invite/the-eye.

We and our members are also active on `r/DataHoarder`, `r/datacurator`, `r/homelab`, `r/selfhosted`, and many more.

**Comment by blocklistproject** [comment]
As of right now this will remain on the list. We will continue to review the site and make a decision soon.

**Comment by blocklistproject** [comment]
This will remain on the list until all owned property is removed. Please feel free to resubmit request once this is done. For additional information about why this decision was made please review -> [https://www.royaltyexchange.com/length-of-ownership-music#:~:text=Music%20Copyrights,a%20recording%20of%20a%20song.&text=If%20a%20song%20was%20copyrighted,the%20author%20plus%2070%20years.](https://www.royaltyexchange.com/length-of-ownership-music#:~:text=Music%20Copyrights,a%20recording%20of%20a%20song.&text=If%20a%20song%20was%20copyrighted,the%20author%20plus%2070%20years.)

**Comment by nektro** [comment]
where did you get the initial list for`piracy.txt`, since you didnt add us to the list yourself. we'd like to remedy this issue upstream as well.

**Comment by elderlabs** [comment]
Please then also blacklist archive.org as the very same logic applies.
