### ISSUE TITLE
s-media-cache-ak0.pinimg.com potential false positive

### ISSUE THREAD

**Issue by mkb2091** [blocklistproject/Lists#25]
URL you wish to be removed: s-media-cache-ak0.pinimg.com

Why you believe this to be a false positive:

s-media-cache-ak0.pinimg.com blocks access to https://s-media-cache-ak0.pinimg.com/originals/28/86/42/288642dec69cb52611e17a2afadc940e.jpg. That url redirects to https://i.pinimg.com/originals/28/86/42/288642dec69cb52611e17a2afadc940e.jpg which isn’t blocked, and is just an image from a video game.

The original url is found in duckduckgo image search results: View file at https://duckduckgo.com/?t=ffab&q=arvak&iax=images&ia=images&iai=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2Foriginals%2F28%2F86%2F42%2F288642dec69cb52611e17a2afadc940e.jpg

List it is on: ads.txt

Other info you think we should know:

**Comment by blocklistproject** [comment]
Searched, did not find that url on the ads lists.

**Comment by blocklistproject** [comment]
My mistake, found and resolved
