### ISSUE TITLE
[Remove Request] - Instagram

### ISSUE THREAD

**Issue by zckyachmd** [blocklistproject/Lists#256]
URL you wish to be removed:
All URLs linked to instagram.com 

Why you believe this to be a false positive:
Because when I added the Facebook block list, all access via the website & application to Instagram was blocked. I'm sure an error occurred while filtering urls that are considered dangerous, please review them again 

![photo_2021-03-29_09-06-25](https://user-images.githubusercontent.com/31559432/112778137-0d5e0580-906e-11eb-9779-22a317026dab.jpg)

**Comment by blocklistproject** [comment]
Facebook owns Instagram, that's why it was on the list.

**Comment by zckyachmd** [comment]
I understand that, but I mean that Instagram can still be accessed even though some things are on the block list. Can you do that? because I want to keep accessing Instagram please

**Comment by CYB3RL4MBD4** [comment]
Hi, in my opinion, it's the same kind of discussion as the one I opened about WhatsApp belonging to Facebook. I could advise you to open a discussion about creating a Instagram list separated from the Facebook list.

**Comment by CYB3RL4MBD4** [comment]
> I understand that, but I mean that Instagram can still be accessed even though some things are on the block list. Can you do that? because I want to keep accessing Instagram. Please 

Hi, in my opinion, it's the same kind of discussion as the one I opened about WhatsApp belonging to Facebook (#239). I could advise you to open a discussion about creating a Instagram list separated from the Facebook list.

**Comment by SimonGhoul** [comment]
If this is ever made, I believe a "softfacebook list" would be easier to manage

Unblocks all facebook domains and trackers, but removes domains that had been shown to break features.

If possible though, I believe facebook domains made for just tracking should be added to the tracking list though (I see how trackers from sites like Google appear there, but facebook isn't there.)
