### ISSUE TITLE
[Remove Request] - byloth.net

### ISSUE THREAD

**Issue by Byloth** [blocklistproject/Lists#266]
**URL you wish to be removed:**
[`byloth.net`](https://www.byloth.net/)

**Why you believe this to be a false positive:**
I am the owner of this domain.  
My site it's simply a statically-generated personal blog; here's the source code: https://github.com/Byloth/website

**List it is on:**
[`phishing.txt`](https://github.com/blocklistproject/Lists/blob/master/phishing.txt)

**Other info you think we should know:**
Many years ago (I think almost 5) my hosting service was attacked and many domains were compromised.  
Someone uploaded fake Microsoft Office 365 login pages to all the hosted websites (including mine).

Provider solved this in no time.

**Comment by blocklistproject** [comment]
After reviewing your site, this has been fixed.
