### ISSUE TITLE
[Remove Request] - platform.linkedin.com

### ISSUE THREAD

**Issue by aravindvnair99** [blocklistproject/Lists#268]
URL you wish to be removed: `platform.linkedin.com`

Why you believe this to be a false positive:

Blocking prevents https://platform.linkedin.com/litms/whitelist/jobs-ea-web from loading which is necessary for job applications using LinkedIn Easy Apply.

List it is on: `ads`

Other info you think we should know: There aren't any ads of any kind.

**Comment by blocklistproject** [comment]
This has been reviewed and fixed. Thank you for bringing this to our attention!
