### ISSUE TITLE
[Remove Request] - coedcherry.com

### ISSUE THREAD

**Issue by clickwir** [blocklistproject/Lists#275]
URL you wish to be removed: 
coedcherry.com

Why you believe this to be a false positive: 
Agree it should be on the porn.txt list.
However it does not seem it should be on abuse or malware.

List it is on: 
porn.txt
abuse.txt
malware.txt

Other info you think we should know:

**Comment by gap579137** [comment]
Removed from abuse and malware lists. Thank you for helping.
