### ISSUE TITLE
[Remove Request] - tinyurl.com

### ISSUE THREAD

**Issue by Deses** [blocklistproject/Lists#279]
URL you wish to be removed:

tinyurl.com 

Why you believe this to be a false positive:

tinyurl.com is a url shortener that has existed for years, maybe you mixed it up with `mytinyurl.com` which is also blocked as `abuse` and `malware`. `mytinyurl.com` is just a blank wordpress template now, whatever it was before.

List it is on:

abuse

Other info you think we should know:

**Comment by blocklistproject** [comment]
This has been fixed, thank you!
