### ISSUE TITLE
[Add request] - citasyencuentros.com	

### ISSUE THREAD

**Issue by Deses** [blocklistproject/Lists#282]
URL you wish to be added:

citasyencuentros.com

Why you believe this should be added:

They send a lot of spam mails and seem to run a dubious hookups website. Smells like a scam.

Add to list:

Abuse
Scam

Other info you think we should know:

**Comment by blocklistproject** [comment]
Will investigate this and see what we need to do.

**Comment by blocklistproject** [comment]
After review we have added this to the recommended lists.
