### ISSUE TITLE
[Remove Request] - ImmoScout24 Mobile API urls

### ISSUE THREAD

**Issue by ustav** [blocklistproject/Lists#288]
**URL you wish to be removed:**

- api.finanzen.immobilienscout24.de
- api.mobile.immobilienscout24.de
- api.recommendation.immobilienscout24.de

**Why you believe this to be a false positive:**

These URLs are used in mobile applications as API endpoints

https://play.google.com/store/apps/details?id=de.is24.android&hl=en&gl=US
https://apps.apple.com/de/app/immobilienscout24-immobilien/id344176018

**List it is on:**

ads

**Other info you think we should know:**

I've created a pull request to solve this issue https://github.com/blocklistproject/Lists/pull/287

**Comment by blocklistproject** [comment]
This has been closed by pull.
