### ISSUE TITLE
[Remove Request] - app.hubspot.com

### ISSUE THREAD

**Issue by CYB3RL4MBD4** [blocklistproject/Lists#289]
URL you wish to be removed:
app.hubspot.com

Why you believe this to be a false positive:
This is the HubSpot app page, why is it on the ads.txt list? Something weired about it? Many thanks for your feedback.

List it is on: 
ads.txt

Other info you think we should know:
This is part of the HubSpot CRM.

**Comment by blocklistproject** [comment]
This has been resolved. Thank you

**Comment by CYB3RL4MBD4** [comment]
Wouaw! You were so quick on this one ;-) Many thanks!
