### ISSUE TITLE
[Remove Request] - soft98 & radiofarda

### ISSUE THREAD

**Issue by Chamrosh** [blocklistproject/Lists#290]
URL you wish to be removed:
soft98.ir

Why you believe this to be a false positive:
This site is one of the most reputable download sites in Persian 

List it is on:
Malware List
Abuse List 

----------------------------------------------------------------------------

URL you wish to be removed:
radiofarda.com

Why you believe this to be a false positive:
is the Iranian branch of the U.S. government-funded Radio Free Europe/Radio Liberty (RFE/RL) external broadcast service for providing "factual, objective and professional journalism" to its audiences. It broadcasts 24 hours a day in the Persian language from its headquarters in the district Hagibor of Prague, Czech Republic

List it is on:
Redirect List

**Comment by blocklistproject** [comment]
This has been partially fixed.
