### ISSUE TITLE
list for blocking viber and telegram needed

### ISSUE THREAD

**Issue by travelg** [blocklistproject/Lists#291]
Please add list for viber and telegram thanks.

**Comment by blocklistproject** [comment]
Will try and get this started today.

**Comment by blocklistproject** [comment]
The way that telegram works I do not believe that Telegram can be blocked via host file (via Pi-Hole)

**Comment by electricduck** [comment]
No, all the official Telegram clients have a list of IPs stored in the source code, and it then picks the closest one it can find. There is `api.telegram.org`, but this is used for bots.

**Comment by blocklistproject** [comment]
This will be closed for now as "not possible"
