### ISSUE TITLE
[Remove Request] - learn.hedera.com

### ISSUE THREAD

**Issue by si618** [blocklistproject/Lists#294]
URL you wish to be removed:  

&nbsp;&nbsp;&nbsp;&nbsp;https://learn.hedera.com

Why you believe this to be a false positive: 

&nbsp;&nbsp;&nbsp;&nbsp;Subdomain is an educational resource, emails linking to it are opt-in and not spam, unsub works.

List it is on:

&nbsp;&nbsp;&nbsp;&nbsp;[basic.txt](https://github.com/blocklistproject/Lists/blob/master/basic.txt), [basic-nl.txt](https://github.com/blocklistproject/Lists/blob/master/alt-version/basic-nl.txt), [basic-dnsmasq.txt](https://github.com/blocklistproject/Lists/blob/master/dnsmasq-version/basic-dnsmasq.txt)

Other info you think we should know:

&nbsp;&nbsp;&nbsp;&nbsp;Hedera is a reputable organization.

**Comment by Myridium** [comment]
I have no idea why this would be blocked. Seems like a mistake.

**Comment by blocklistproject** [comment]
This has been fixed. Thank you!

**Comment by si618** [comment]
Thanks for the prompt review and action @blocklistproject. 

Is there a way to determine why it was added in the first place?
