### ISSUE TITLE
Whitelist llnwd.net 

### ISSUE THREAD

**Issue by It0w** [blocklistproject/Lists#3]
URL you wish to be removed: llnwd.net

Why you believe this to be a false positive: ```Standard query response 0xb230 No such name A www.nintendo.de CNAME nintendoeu-1.hs.llnwd.net```

List it is on: ads.txt

Other info you think we should know: Please do not block entire domain. This will only increase the false positive. The owner of llnwd.net is Limelight Networks a CDN Service Provider. By Blocking this domain you also block Nintendo (EU), BubbleUP and DailyMotion.

**Comment by blocklistproject** [comment]
This has been fixed. Thank you for your help!
