### ISSUE TITLE
[Remove Request] - statics.streamable.com

### ISSUE THREAD

**Issue by electricduck** [blocklistproject/Lists#309]
URL you wish to be removed:
`statics.streamable.com`

Why you believe this to be a false positive:
This provides important assets for the site, such as CSS and JS. Blocking this causes the site to break. Streamable itself is a moderated video sharing site.

List it is on:
Ads

Other info you think we should know:
None

**Comment by blocklistproject** [comment]
This issue has been resolved. Thank you
