### ISSUE TITLE
Add these to the porn lists[Add request]

### ISSUE THREAD

**Issue by ahmed-tasaly** [blocklistproject/Lists#310]
### URLs:
https://bestporncomix.com/
https://worldporncomix.com/
https://wporncomics.com/
https://erocomicsxxx.com/
https://hentaicomicsonline.com/
https://fotonovelasxxx.com/
http://www.sexcomix.me/
https://comix.site/
https://hornyson.com/
https://porncomixinfo.net/
http://porncomics.name/
http://8-muses.xyz/
https://hdhentaicomics.com/
https://comixzilla.com/
https://comicporns.com/
https://8muses.net/

**Cause :** Porn or Porn comics sites

**Comment by blocklistproject** [comment]
These have been added. Thank you for your help.
