### ISSUE TITLE
[Add request] privatestats.whatsapp.net to WhatsApp list

### ISSUE THREAD

**Issue by CYB3RL4MBD4** [blocklistproject/Lists#312]
URL you wish to be added: privatestats.whatsapp.net

Why you believe this should be added: it's on the facebook.txt list and is a WhatsApp domain

Add to list: whatsapp.txt

Other info you think we should know:should it be removed from Facebook list too?? Or is it also used by Facebook and should stay on that list?

**Comment by blocklistproject** [comment]
This has been added. Thank you for your help

**Comment by CYB3RL4MBD4** [comment]
> This has been added. Thank you for your help

You're welcome
