### ISSUE TITLE
[Add request] confirm28371630-coinbase-com.web.app

### ISSUE THREAD

**Issue by fishcharlie** [blocklistproject/Lists#313]
### URL you wish to be added:

`confirm28371630-coinbase-com.web.app`

### Why you believe this should be added:

Website is a phishing attempt to get Coinbase credentials.

### Add to list:

Phishing

### Other info you think we should know:

Received the following text message:

```
Coinbase: A withdrawal has been requested from an unknown IP address. If this was not you, follow the steps here: www.bit.ly/3y6YGAR
```

**Comment by blocklistproject** [comment]
This has been added. Thank you
