### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by CYB3RL4MBD4** [blocklistproject/Lists#314]
URL you wish to be added: media.fqls2-1.fna.whatsapp.net

Why you believe this should be added: It's accessed when opening WhatsApp (saw it in my pi-hole log)

Add to list: whatsapp.txt

Other info you think we should know: maybe there are other similar addresses, I'll keep you informed.

**Comment by MokraCota** [comment]
So.. what is wrong with this address? It's a normal address that WhatsApp uses.

**Comment by CYB3RL4MBD4** [comment]
> So.. what is wrong with this address? It's a normal address that WhatsApp uses.

Nothing wrong, it should be added to the list whatsapp.txt
