### ISSUE TITLE
[Remove Request] - gmail-smtp-in.l.google.com

### ISSUE THREAD

**Issue by WordsOfMe** [blocklistproject/Lists#317]
URL you wish to be removed: gmail-smtp-in.l.google.com

Why you believe this to be a false positive: This is the primary MX for gmail.com and will result in hiccups with any mailserver using DNS requests filtered by this list. Any mail to a ...@gmail.com account will result in a 0.0.0.0 reply for the MX, with e.g. postfix aborting with a "mail loops back to myself" error.

List it is on: blocklist.site abuse list

Other info you think we should know: I am wondering based on which evidence / clue this entry could make it to the abuse list, was this a fun bird? This alread happended in issue #92.

**Comment by rumplin** [comment]
I'm stopping to use this blocklist, it's getting random sites to the lists. This makes no sense anymore.

**Comment by blocklistproject** [comment]
> I'm stopping to use this blocklist, it's getting random sites to the lists. This makes no sense anymore.

We are sorry to hear this. Hopefully you will find a list that better suites your needs. Thank you for using our lists up until this point. We appreciate your help in the community.
