### ISSUE TITLE
[Add request] `captcharesolving-universe[.]com`

### ISSUE THREAD

**Issue by iam-py-test** [blocklistproject/Lists#319]
URL you wish to be added:
`captcharesolving-universe.com`
Why you believe this should be added:
This website is malware/phishing. See 
https://www.virustotal.com/gui/url/0c4cb3b1f10824b29eff5781e28622555816960c4c6e6b0318ed6f5a477501b0/detection
https://www.siteadvisor.com/sitereport.html?url=captcharesolving-universe.com
https://www.fortiguard.com/webfilter?q=captcharesolving-universe.com&version=8
https://github.com/DandelionSprout/adfilt/commit/0af1431c8f4cf45e9c27e359edf777b0c9bfa153
https://safeweb.norton.com/report/show?url=captcharesolving-universe.com
https://www.urlvoid.com/scan/captcharesolving-universe.com/
https://sitecheck.sucuri.net/results/captcharesolving-universe.com
https://quttera.com/detailed_report/captcharesolving-universe.com
https://www.virustotal.com/gui/domain/captcharesolving-universe.com/detection
Add to list:
Malware or Phishing
Other info you think we should know:
This domain was discovered by @DandelionSprout in https://github.com/DandelionSprout/adfilt/issues/188
I have verified it is not in Phishing/Malware and there are no issues (open or closed) referencing this domain

**Comment by blocklistproject** [comment]
This has been added. Thank you for your help!
