### ISSUE TITLE
[Remove Request] - jqueryui.com, api.jqueryui.com

### ISSUE THREAD

**Issue by mkdjns** [blocklistproject/Lists#320]
URL you wish to be removed:
jqueryui.com, api.jqueryui.com

Why you believe this to be a false positive:
Both of those sites provide documentation for jQuery UI. I cannot fathom a reason anyone would need to block them.

List it is on:
malware, abuse

Other info you think we should know:

**Comment by blocklistproject** [comment]
This has been fixed. Thank you
