### ISSUE TITLE
[Add request] Add porn domain - `youngroulette.com`

### ISSUE THREAD

**Issue by iam-py-test** [blocklistproject/Lists#323]
URL you wish to be added:
`youngroulette.com`
Plus  `www.youngroulette.com` (for HOSTS)
Why you believe this should be added:
It is a unblocked porn domain - see https://www.fortiguard.com/webfilter?q=youngroulette.com&version=8
Add to list:
porn
Other info you think we should know:
According to https://sitecheck.sucuri.net/results/cumteen.com, `cumteen.com` redirects to this domain.

_Irrelevant:_ Thank  you for your work! I use your blocklists in uBlock Origin everyday

**Comment by blocklistproject** [comment]
This has been added. Thank you for your help
