### ISSUE TITLE
[Remove Request] - 

### ISSUE THREAD

**Issue by acs-com** [blocklistproject/Lists#324]
URL you wish to be removed: https://antiviruscontactsupport.com and associated URLS

Why you believe this to be a false positive: I am the owner of this domain since January and it is not fraudulant

List it is on: Fraud, Alt Version/Fraud

Other info you think we should know: Please feel free to contact me on email for any further information info@antiviruscontactsupport.com, Thank you

**Comment by blocklistproject** [comment]
This will be investigated.

**Comment by iam-py-test** [comment]
@acs-com how do you know your domain has not been hacked?

**Comment by acs-com** [comment]
I have ran multiple scans and my site is secure

On Jun 22, 2021, 18:12, at 18:12, iam-py-test ***@***.***> wrote:
***@***.*** how do you know your domain has not been hacked?

**Comment by iam-py-test** [comment]
Ok…
I visited your site & it looked very strange.
Why do you advertise & have downloads for two avs? Also, why is it look like I have to pay for a free product…

**Comment by acs-com** [comment]
I sell bitdefender and Kaspersky, the free editions are listed as free, so you don't pay

**Comment by iam-py-test** [comment]
@acs-com 
1. Why are you selling avs that can be download from their own websites
2. Why is there no link to the vender's website
3. I could not find a free bitdefender on their website, so what are you selling?

Please note I have no relation to @blocklistproject and have no real say in what happens here

**Comment by acs-com** [comment]
Have you checked the shop page?

https://www.antiviruscontactsupport.com/bitdefender-kaspersky-mcafee-norton-webroot-malwarebytes-keys/

A you can see I'm selling the paid variants of each av.

Why would i need a link to the vendor? The product is downloading through the bitdefender portal not myself, apart from the free versions which I host the download and again it's free

Here is the link for the bitdefender free page

https://www.bitdefender.co.uk/solutions/free.html

If there is anything else of course just ask

On Jun 22, 2021, 18:29, at 18:29, iam-py-test ***@***.***> wrote:
***@***.***

**Comment by acs-com** [comment]
That's fine, enquires about what we do is fine, we have nothing to hide.

I have a feeling that the domain may have been up to no good in the past as I only acquired the domain in January ish

Hence why I am trying to clean up it's act from the past as it is currently blocked on both bing and Facebook, however all good on Google.

The sooner I can get a reply from someone here about what's happening there better



On Jun 22, 2021, 18:29, at 18:29, iam-py-test ***@***.***> wrote:
***@***.***

**Comment by iam-py-test** [comment]
> Here is the link for the bitdefender free page

I guess I was looking in the wrong place. Sorry.
> Why would i need a link to the vendor? The product is downloading through the bitdefender portal not myself, apart from the free versions which I host the download and again it's free

Considering you are selling their (free) product, I would expect some credit, but considering it only takes one DuckDuckGo search to find bitdefender, I don't think that alone makes your site a scam. 

> If there is anything else of course just ask

I am not sure if you are talking to me or @blocklistproject, but thanks for responding to my questions.

**Comment by iam-py-test** [comment]
I scanned your bitdefender files & they look ok.
https://www.virustotal.com/gui/file/f5467e4f14cbb0901d7f2f15c3293600069e920c1c9bef9afd1c32cd89e15e58/detection
https://www.virustotal.com/gui/file/8737c0fd7f35c6804269bdeefee68499c325350fd60a287e5972214da68f8845/detection

**Comment by blocklistproject** [comment]
If you can provide proof that you only acquired the domain this year we can go ahead and remove it. After research we are unable to find any evidence of recent malicious activity. But showing that you have just recently acquired the domain would surely help.

**Comment by acs-com** [comment]
I can yes

Not sure if it will show up here but I have attached the domain transfer screen shot to this email

**Comment by iam-py-test** [comment]
> 
> I can yes Not sure if it will show up here but I have attached the domain transfer screen shot to this email
> […](#)
> On Jun 22, 2021, 18:46, at 18:46, The Block List Project ***@***.***> wrote: If you can provide proof that you only acquired the domain this year we can go ahead and remove it. After research we are unable to find any evidence of recent malicious activity. But showing that you have just recently acquired the domain would surely help. -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#324 (comment)](https://github.com/blocklistproject/Lists/issues/324#issuecomment-866197271)

Attachments don't work
Upload it to GitHub

**Comment by iam-py-test** [comment]
@acs-com why is your BitDefender+ $17 more expensive than the one on the BitDefender website?
They look like exactly the same

**Comment by acs-com** [comment]
Not a chance, every product I sell is cheaper than bitdefender direct, which product are you referring too and are you looking at RRP or the same price?

On Jun 22, 2021, 19:02, at 19:02, iam-py-test ***@***.***> wrote:
***@***.*** why is your BitDefender+ $17 more expensive than the one on

**Comment by iam-py-test** [comment]
I am looking at `https://www.antiviruscontactsupport.com/bitdefender-antivirus-plus-3-devices-1-year-digital-delivery/`
Technically, I am not looking at the marked down price, which is a bit cheaper.

**Comment by acs-com** [comment]
All of my products are listed a RRP discounted to the same price, just like bitdefender.

That product with us is 12.95 GBP

At bitdefender direct it is £16.00 so much cheaper

**Comment by iam-py-test** [comment]
> 
> All of my products are listed a RRP discounted to the same price, just like bitdefender. That product with us is 12.95 GBP At bitdefender direct it is £16.00 so much cheaper
> […](#)
> On Jun 22, 2021, 19:27, at 19:27, iam-py-test ***@***.***> wrote: I am looking at `[https://www.antiviruscontactsupport.com/bitdefender-antivirus-plus-3-devices-1-year-digital-delivery/`](https://www.antiviruscontactsupport.com/bitdefender-antivirus-plus-3-devices-1-year-digital-delivery/%60) Technically, I am not looking at the marked down price, which is a bit cheaper. -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#324 (comment)](https://github.com/blocklistproject/Lists/issues/324#issuecomment-866231028)

It looks like I forgot to convert.
Sorry for wasting your time

**Comment by iam-py-test** [comment]
@acs-com please post the domain verification screenshot as requested by @blocklistproject.
Apart from that, your domain looks free of scams & malware (as far as I can tell)

**Comment by acs-com** [comment]
I tried, apparently I cannot do this via email, out watching the Euros tonight so will do it from my PC tomorrow

Cheers

On Jun 22, 2021, 19:37, at 19:37, iam-py-test ***@***.***> wrote:
***@***.*** please post the domain verification screenshot as requested by
***@***.***

**Comment by iam-py-test** [comment]
Can you visit https://github.com/blocklistproject/Lists/issues/324 in your browser?
If your on iOS or Android, you should be able to click on it & open it in Safari and Chrome

**Comment by acs-com** [comment]
Yes but can't see an upload option

**Comment by iam-py-test** [comment]
> 
> Yes but can't see an upload option
> […](#)
> On Jun 22, 2021, 19:42, at 19:42, iam-py-test ***@***.***> wrote: Can you visit #324 in your browser? If your on iOS or Android, you should be able to click on it & open it in Safari and Chrome -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#324 (comment)](https://github.com/blocklistproject/Lists/issues/324#issuecomment-866240495)

Can you make a new comment & click _attach files by dragging & dropping_

**Comment by acs-com** [comment]
Hi please find attached PDF with some of my details erased for privacy
[ACS DOMAIN PURCHASE RECEIPT.pdf](https://github.com/blocklistproject/Lists/files/6700164/ACS.DOMAIN.PURCHASE.RECEIPT.pdf)

**Comment by acs-com** [comment]
Thank you can you delete your comment highlighting the same 
[ACS.DOMAIN.PURCHASE.RECEIPT.pdf](https://github.com/blocklistproject/Lists/files/6701910/ACS.DOMAIN.PURCHASE.RECEIPT.pdf)
please

**Comment by iam-py-test** [comment]
@blocklistproject is it look valid?

**Comment by acs-com** [comment]
> What do you mean?
> To my knowledge, they don't have their own blocklists.

What I mean is that I found this website while investigation the reasons as to why I am blocked on both facebook and bing, I am unsure as to how these companies get their information and why they block (absolutely zero help from either other than follow the guidelines, all of which I think are fine) but I would imagine being listed here as a scam is not great no matter the effect on these sites hence why I have asked for removal.
 of course if anyone here knows a way to find out what is wrong I would be hugely grateful

**Comment by acs-com** [comment]
> @blocklistproject is it look valid?

I am sorry I do not understand the question? this PDF is downloaded from my namecheap account and I have edited out sensitive information for privacy

**Comment by iam-py-test** [comment]
> > @blocklistproject is it look valid?
> 
> I am sorry I do not understand the question? this PDF is downloaded from my namecheap account and I have edited out sensitive information for privacy

I was asking @blocklistproject if they had looked over it & found it valid.

**Comment by acs-com** [comment]
> > > @blocklistproject is it look valid?
> > 
> > 
> > I am sorry I do not understand the question? this PDF is downloaded from my namecheap account and I have edited out sensitive information for privacy
> 
> I was asking @blocklistproject if they had looked over it & found it valid.

Oh ok sorry

**Comment by blocklistproject** [comment]
As of now I will unblock this domain BUT I will be running scans on the site randomly and watching reviews. I am still a little skeptical for some reason but I see nothing that jumps out right now and says "this is a scam"

**Comment by iam-py-test** [comment]
@blocklistproject can this issue be closed?

**Comment by acs-com** [comment]
I can assure you it's not, not I fully understand the sentiment this block list provides

Watch and see, we are awesome lol
