### ISSUE TITLE
[Remove Request] - catbox.moe

### ISSUE THREAD

**Issue by SimonGhoul** [blocklistproject/Lists#325]
URL you wish to be removed:
files.catbox.moe

Why you believe this to be a false positive:
The site is used by a lot of legimite users online, and by a lot of artists on Twitter. It has been added on the abuse list.
catbox.moe is a free to use file sharing website, their rules state that they don't allow or promote the usage of their service in order to spread viruses, or other illegal or potentially dangerous content. This is seen on their [FAQ](https://catbox.moe/faq.php)

Please whitelist this domain

List it is on:
abuse list
https://blocklistproject.github.io/Lists/abuse.txt
https://github.com/blocklistproject/Lists/blob/master/abuse.txt

**Comment by blocklistproject** [comment]
Unfortunately, a quick search shows that, yes they do have that in there FAQ but they do not actively mitigate issues. At this time I would recommend whitelisting this site if you need it.
