### ISSUE TITLE
[Add request] 16 Porn Websites

### ISSUE THREAD

**Issue by TheyCallMeZ** [blocklistproject/Lists#327]
URL you wish to be added:
`jayspov.net`
`www.redwap.me`
`www.pornfuck.net`
`cum-shows.net`
`filthykings.com`
`www.tube100.me`
`sex-hd.org`
`hdxxxtube.online`
`mypervyfamily.com`
`www.cosmid.net`
`alettaoceanlive.com`
`www.clubsweethearts.com`
`www.mylf.com`
`sexmex.xxx`
`www.tushyraw.com`
`www.analvids.com`

Why you believe this should be added:
Porn

Add to list:
Porn

Other info you think we should know:
Some Pay sites some free content not sure if the goal is anything pornographic or just "free video content"

**Comment by iam-py-test** [comment]
@TheyCallMeZ please edit your comment and put  ` around the domains so they are not linked

**Comment by TheyCallMeZ** [comment]
> @TheyCallMeZ please edit your comment and put ` around the domains so they are not linked

Wasn't sure if you meant all or each individually, did individual. Let me know your preference for future submissions.

**Comment by iam-py-test** [comment]
> > @TheyCallMeZ please edit your comment and put ` around the domains so they are not linked
> 
> Wasn't sure if you meant all or each individually, did individual. Let me know your preference for future submissions.

@TheyCallMeZ I don’t have any relationship with @blocklistproject; I was just informing you that the domains were auto linked so people might accidentally click on them.
Sorry for the confusion

**Comment by blocklistproject** [comment]
These have been added. Thank you for your help!

**Comment by iam-py-test** [comment]
@TheyCallMeZ `filthykings.com` shows it is Domain Parking?

**Comment by TheyCallMeZ** [comment]
> @TheyCallMeZ `filthykings.com` shows it is Domain Parking?

I just double checked the domain is not parked. I double checked with a copy/paste of the mentioned url. 
Thanks for the feedback on the issue submission as well, it does make sense to have them not show as links.

**Comment by iam-py-test** [comment]
> filthykings.com

Verified; it is not parked. Wonder why https://www.fortiguard.com/webfilter?q=filthykings.com&version=8 shows domain parking & https://www.siteadvisor.com/sitereport.html?url=filthykings.com shows marketing.
Maybe they are confusing the heuristics?

**Comment by iam-py-test** [comment]
Maybe also add `imgs1cdn.adultempire.com` due to HOSTS file syntax? I just spotted that domain in my NoScript allows & thought it might be worth adding

**Comment by iam-py-test** [comment]
@blocklistproject @TheyCallMeZ Another malware/porn domain connected to this submission:
`my-sweet-sexfinder.com`
https://www.siteadvisor.com/sitereport.html?url=https://my-sweet-sexfinder.com
https://safeweb.norton.com/report/show?url=my-sweet-sexfinder.com
https://www.virustotal.com/gui/url/ef4606592186c16b1bd66b086b19bcd5200ac22ab9c72016c03fca4989ce926a/detection

**Comment by TheyCallMeZ** [comment]
> @blocklistproject @TheyCallMeZ Another malware/porn domain connected to this submission:
> `my-sweet-sexfinder.com`
> https://www.siteadvisor.com/sitereport.html?url=https://my-sweet-sexfinder.com
> https://safeweb.norton.com/report/show?url=my-sweet-sexfinder.com
> https://www.virustotal.com/gui/url/ef4606592186c16b1bd66b086b19bcd5200ac22ab9c72016c03fca4989ce926a/detection

@iam-py-test  Please open a new issue to submit adding any new sites to the appropriate list.
I too am not affiliated with this project, just helping with contributions.
