### ISSUE TITLE
[Add request] Spam & scam domain

### ISSUE THREAD

**Issue by iam-py-test** [blocklistproject/Lists#330]
URL you wish to be added:
`ammjaflk.ru` 
Why you believe this should be added:
This is a spam/scam domain from https://forum.mywot.com/reputation-discussions-f5/eva-pharmacy-name-servers-t97042.html
Add to list:
Scam.txt
Other info you think we should know:
Verification:
https://www.mywot.com/scorecard/ammjaflk.ru
https://www.virustotal.com/gui/url/f4c05c0b5b110716976612974456e57ffd41515f206248cd20baf4c856b797a7/detection

**Comment by blocklistproject** [comment]
This has been added. Thank you
