### ISSUE TITLE
Data issue

### ISSUE THREAD

**Issue by fishcharlie** [blocklistproject/Lists#333]
In the `ads.txt` file, lines 132271-132273, it has the following:

```
0.0.0.0 um2.eqads.com
0.0.0.0 um2.eqads.com x.skimresources.com
0.0.0.0 um2.eqads.comx.skimresources.com
```

These obviously look to be incorrect URLs, but it's really hard to tell what is going on here. There really can't be spaces in URLs, so that middle one is for sure not accurate.

Not quite sure how to fix this tho.

**Comment by Trainax** [comment]
> Not quite sure how to fix this tho

I think you have to add a new line instead of the spaces and also put a new line after `com` before `x` on the third line which can be also deleted because it would be duplicated.

Instead of
```
0.0.0.0 um2.eqads.com
0.0.0.0 um2.eqads.com x.skimresources.com
0.0.0.0 um2.eqads.comx.skimresources.com
```

I think there should be

```
0.0.0.0 um2.eqads.com
0.0.0.0 x.skimresources.com
```

**Comment by fishcharlie** [comment]
@Trainax That makes sense, it just seems weird that it's duplicated. Maybe a weird copy and paste error or something?

**Comment by Trainax** [comment]
> @Trainax That makes sense, it just seems weird that it's duplicated. Maybe a weird copy and paste error or something?

It could be, sometimes also domains ending in `&amp` get into the lists

**Comment by blocklistproject** [comment]
This may also have been an issue with one of the earlier version of the python scripts I used.
