### ISSUE TITLE
Next automation task?

### ISSUE THREAD

**Issue by fishcharlie** [blocklistproject/Lists#335]
@blocklistproject What would you like to see next for automation on this project? You obviously run a lot of the day to day of this project and have an extremely good sense of what people want, and what takes up most of your time. So just looking for some of that insight in terms of what to prioritize on the automation front.

**Comment by blocklistproject** [comment]
What about deduplication in each list? Most of the lists I have deduplicated but as we add more URLs and grow the lists there is bound to be duplicates.

**Comment by blocklistproject** [comment]
Also would like to work on creating a version of the lists for adblock

Syntax can be seen here: [https://adblockplus.org/en/filter-cheatsheet](https://adblockplus.org/en/filter-cheatsheet)

I am going to see if I can get the script to work for it and will post it here for you to check if you don't mind
