### ISSUE TITLE
[Add request] 28 Adult Websites

### ISSUE THREAD

**Issue by TheyCallMeZ** [blocklistproject/Lists#339]
URL you wish to be added:

`brattysis.com`
`www.nudevista.com`
`www.tnaflix.com`
`xxxtube2022.com`
`xhlocal.com`
`faphouse.com`
`www.youjizz.com`
`www.eporner.com`
`www.dogfartnetwork.com`
`www.dogfartbehindthescenes.com`
`www.teamskeet.com`
`www.familystrokes.com`
`www.pervmom.com`
`www.fostertapes.com`
`www.littleasians.com`
`www.dadcrush.com`
`www.daughterswap.com`
`www.shoplyfter.com`
`www.shoplyftermylf.com`
`submissived.org`
`www.teensloveblackcocks.com`
`www.teamskeet.com`
`www.thickumz.com`
`www.blackvalleygirls.com`
`www.notmygrandpa.com`
`www.teamskeettube.com`
`www.pervdoctor.com`
`www.bffs.com`

Why you believe this should be added:
Porn Content / Multi-site network for some of the sites listed above
xhlocal is a variant of XHamster

Add to list:
Porn

Other info you think we should know:

**Comment by blocklistproject** [comment]
These have been added. Thank you!

**Comment by TheyCallMeZ** [comment]
> These have been added. Thank you!

Glad to help!
