### ISSUE TITLE
browser.pipe.aria.microsoft.com, mobile.pipe.aria.microsoft.com, nexusrules.officeapps.live.com, nexus.officeapps.live.com @ gambling

### ISSUE THREAD

**Issue by Homas** [blocklistproject/Lists#34]
URL you wish to be removed: browser.pipe.aria.microsoft.com,  mobile.pipe.aria.microsoft.com, nexusrules.officeapps.live.com, nexus.officeapps.live.com
Why you believe this to be a false positive: it is tracking, not gambling
List it is on: gambling
Other info you think we should know:

**Comment by blocklistproject** [comment]
This has been fixed. Thank you
