### ISSUE TITLE
[Remove Request] - advcash.com, wallet.advcash.com

### ISSUE THREAD

**Issue by CYB3RL4MBD4** [blocklistproject/Lists#343]
URL you wish to be removed:
advcash.com
wallet.advcash.com

Why you believe this to be a false positive:
This is a payment service and wallet that, after a rapid check, seems to be valid and safe
https://www.scamquery.com/review/advcash.com/

List it is on:
abuse.txt
ads.txt
malware.txt

Other info you think we should know:
Is there a particular reason why this site landed on all these lists?

**Comment by gap579137** [comment]
This has been addressed. Thank you!
