### ISSUE TITLE
[Remove Request] - lagranitmarble.it

### ISSUE THREAD

**Issue by gianniferrai** [blocklistproject/Lists#345]
URL you wish to be removed:
lagranitmarble.it

Why you believe this to be a false positive:
site cleaned

List it is on:
phishing

Other info you think we should know:
thankyou

**Comment by blocklistproject** [comment]
What tool did you use to check the site?

**Comment by fishcharlie** [comment]
I do **not** support this removal request without more information from @gianniferrai.

According to the waybackmachine the website visually looks almost identical to what it looks like today: https://web.archive.org/web/20180901170225/http://www.lagranitmarble.it/.

Just putting `site cleaned` with no additional information I don't believe is enough information to warrant a removal.

**Comment by gianniferrai** [comment]
Hi Charlie, I asked my customer more informations.
He said that a couple of year ago his site was hacked due to a bug in wordpress, and that his website developer upgraded wp version in a few days
He can't give me more infos.

Hopeing this is enough for you...
Many Thanks
Gianni

**Comment by fishcharlie** [comment]
Gonna leave this up to @blocklistproject. I don't have any further comment on it. The site from what I have seen looks ok. It's hard to see any sign of phishing. But a lot of phishing sites are very subtle. So it's hard to say.

**Comment by blocklistproject** [comment]
I will look into this more tomorrow.

**Comment by blocklistproject** [comment]
Without further information this issue is being closed. Please feel free to create a new issue with additional info if you feel like this was done in error. Please make sure you reference this issue. Issues regarding previously closed issues without reference to previously closed issue will be closed. Thank you.
