### ISSUE TITLE
s-imp.rmp.rakuten.com, s-bid.rmp.rakuten.com are listed in gambling should be ads

### ISSUE THREAD

**Issue by Homas** [blocklistproject/Lists#36]
URL you wish to be removed: s-imp.rmp.rakuten.com, s-bid.rmp.rakuten.com listed in gambling should be ads

Why you believe this to be a false positive: It is ads, not gambling
https://www.mysysadmintips.com/windows/home-and-media/802-remove-ads-from-viber-desktop
List it is on: gambling

Other info you think we should know:

**Comment by blocklistproject** [comment]
This has been fixed. Thank you
