### ISSUE TITLE
[Add request] - Fake Unemployment phishing URLs

### ISSUE THREAD

**Issue by RooneyMcNibNug** [blocklistproject/Lists#366]
URL you wish to be added:
rb.gy/e7sycu
hovrecording.com

Why you believe this should be added:
Currently being used to harvest credentials in phishing attack

Add to list:
Abuse

Other info you think we should know:
https://twitter.com/RooneyMcNibNug/status/1410386168777265167

**Comment by blocklistproject** [comment]
This has been added. Thank you.
