### ISSUE TITLE
[Add request] Scam and malware domain

### ISSUE THREAD

**Issue by iam-py-test** [blocklistproject/Lists#367]
URL you wish to be added:
`WhyNotWin11.com`
Why you believe this should be added:
This is malware and a scam. See https://github.com/rcmaehl/WhyNotWin11/issues/66
Add to list:
Malware and Scam
Other info you think we should know:

**Comment by micwoj92** [comment]
Why did you link specifically to my comment?

**Comment by iam-py-test** [comment]
Oh. Sorry.
I just copypasted the url in the url bar, and GitHub brought me to your comment.
Fixing

**Comment by blocklistproject** [comment]
I have read through the thread associated with the issue on the creator's repo. The site in question seems to still be linking to the repo. Has there been any update?

**Comment by iam-py-test** [comment]
> I have read through the thread associated with the issue on the creator's repo. The site in question seems to still be linking to the repo. Has there been any update?

They confirmed that the download is malware.

**Comment by blocklistproject** [comment]
This has been added. Thank you
