### ISSUE TITLE
*.yandex.ru subdomains in gambling

### ISSUE THREAD

**Issue by Homas** [blocklistproject/Lists#37]
URL you wish to be removed: multple yandex.ru subdomains. Also I saw some other yandex domains which can be legit
Why you believe this to be a false positive:  Yandex is like a google in Russia. their domains can be related to tracking, ads but not gambling.
List it is on: gambling
Other info you think we should know:
gambling.txt:# [yandex.ru]
gambling.txt:0.0.0.0 adfox.yandex.ru
gambling.txt:0.0.0.0 matchid.adfox.yandex.ru
gambling.txt:0.0.0.0 adsdk.yandex.ru
gambling.txt:0.0.0.0 advertising.yandex.ru
gambling.txt:0.0.0.0 an.yandex.ru
gambling.txt:0.0.0.0 redirect.appmetrica.yandex.ru
gambling.txt:0.0.0.0 awaps.yandex.ru
gambling.txt:0.0.0.0 awsync.yandex.ru
gambling.txt:0.0.0.0 bs.yandex.ru
gambling.txt:0.0.0.0 bs-meta.yandex.ru
gambling.txt:0.0.0.0 clck.yandex.ru
gambling.txt:0.0.0.0 informer.yandex.ru
gambling.txt:0.0.0.0 kiks.yandex.ru
gambling.txt:0.0.0.0 grade.market.yandex.ru
gambling.txt:0.0.0.0 mc.yandex.ru
gambling.txt:0.0.0.0 metrica.yandex.ru
gambling.txt:0.0.0.0 metrika.yandex.ru
gambling.txt:0.0.0.0 click.sender.yandex.ru
gambling.txt:0.0.0.0 share.yandex.ru
gambling.txt:# 0.0.0.0 clck.yandex.ru
gambling.txt:# 0.0.0.0 grade.market.yandex.ru
gambling.txt:0.0.0.0 ms.yandex.ru

**Comment by blocklistproject** [comment]
This has been fixed. Thank you
