### ISSUE TITLE
[Remove Request???] - boards.greenhouse.io

### ISSUE THREAD

**Issue by fishcharlie** [blocklistproject/Lists#372]
**I'm not confident this URL should be removed**

There are pros and cons each way to removing it or keeping it. It needs a solid review and to be thought through well before making a final decision.

---

**URL you wish to be removed:**

- boards.greenhouse.io

**Why you believe this to be a false positive:**

To be very clear I'm **not** confident that this URL should be removed. I think this is where we possibly need more policies about what URLs should be on the lists and which shouldn't.

In this case, should URLs where `tracking` is not the primary purpose, but where `tracking` might occur be on the list? It's a double edged sword. One argument to having them on the list is that it might block legit sites. However, the other thought process is that removing it will lead to sites trying to avoid being listed by doing bad activity as a secondary purpose to get around being blocked.

Very tough call here.

**List it is on:**

- `tracking`

**Other info you think we should know:**

**Comment by blocklistproject** [comment]
I do not think that we need to add sites that to the tracking list unless their primary purpose is tracking. If we were to start adding sites to the list that could possibly track you then we would have to add the internet to the list. Thoughts?

**Comment by fishcharlie** [comment]
> then we would have to add the internet to the list

@blocklistproject I mean, most domains aren't involved in tracking. Most websites out source that to other companies (ie. Facebook, etc). So even if they embed trackers, I think that is different than actually tracking.

I think part of it comes down to definition. In my mind a tracker is a 3rd party domain involved in tracking activity across multiple websites.

Features like this from the URL linked above: https://support.greenhouse.io/hc/en-us/articles/200721644-Job-Board-Integration-Options, indicate that they are involved in tracking activity across multiple websites that they don't control.

Which falls under that definition if true.

Is that their primary customer facing purpose? No.

In this example specifically, I am leaning towards removing it tho. I don't see clear evidence of abuse here or malicious tracking behavior.

However, if something came out that indicates that they are abusing this data they are collecting, no doubt should it be added to the list.

Which almost is not a good standard to set. Only add sites that are abusing the tracking privileges? That is a huge gray area and subject to a lot of bias.

**Comment by blocklistproject** [comment]
Agree without clear evidence of abuse it should be removed.

**Comment by blocklistproject** [comment]
This has been removed. Thank you
