### ISSUE TITLE
widgetdata.tradingview.com s.tradingview.com s3.tradingview.com

### ISSUE THREAD

**Issue by mkb2091** [blocklistproject/Lists#38]
URL you wish to be removed: widgetdata.tradingview.com
s.tradingview.com
s3.tradingview.com

Why you believe this to be a false positive: Those are needed to display graphs on investopedia such as https://www.investopedia.com/markets/quote?tvwidgetsymbol=aapl

List it is on: ads.txt

Other info you think we should know:

**Comment by blocklistproject** [comment]
This has been fixed. Thank you
