### ISSUE TITLE
[Remove request] lagranitmarble.it (closed reference#345)

### ISSUE THREAD

**Issue by gianniferrai** [blocklistproject/Lists#381]
URL you wish to be removed: lagranitmarble.it

Why you believe this to be a false positive: 

List it is on: phishing

Other info you think we should know:
Previous request closed because of "no more infos". Please specify what kind of infos you need. Thankyou

**Comment by iam-py-test** [comment]
@gianniferrai 
1. You may want to rename this issue as it is named _add request_
2. Your site still has 3 AV detections on VirusTotal, so you will have to report FPs to them too. Also, Malwarebytes has it blocked as phishing
4. I have visited it in a VM. No obvious malware activity but considering it is Phishing, visual inspection alone is not much

If your site was hacked, you should be able to provide evidence (i.e. logs) to prove it.
So far, your site does appear to be running Wordpress 5.7.2, and considering the amount of Wordpress-security-issues there are, it sounds plausible your site could have been hacked.

**Comment by fishcharlie** [comment]
@gianniferrai I agree with @iam-py-test, and would add that something fishy does seem to be going on here. Can you give more details about what kind of relationship you have with this customer? Are you getting paid to submit to removal requests on block lists for their domains?

I can tell you right now that behavior looks very sketchy, and will likely result in not being removed from this list. There seems to be a lack of transparency here with comments that you have made like `He can't give me more infos`.

I'd also like to know why Malwarebytes has blocked it as phishing if it isn't? Have you reached out to Malwarebytes regarding this? What communication have you had with them?

**Comment by iam-py-test** [comment]
> @gianniferrai I agree with @iam-py-test, and would add that something fishy does seem to be going on here. Can you give more details about what kind of relationship you have with this customer? Are you getting paid to submit to removal requests on block lists for their domains?
> 
> I can tell you right now that behavior looks very sketchy, and will likely result in not being removed from this list. There seems to be a lack of transparency here with comments that you have made like `He can't give me more infos`.
> 
> I'd also like to know why Malwarebytes has blocked it as phishing if it isn't? Have you reached out to Malwarebytes regarding this? What communication have you had with them?

@gianniferrai if you want your _client_'s domain unblocklisted, you will have to reach out to Fortinet, Webroot, and a few others. 
Also, if you are being paid by someone, please disclose that
