### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by Titomrock21** [blocklistproject/Lists#386]
URL you wish to be added:

`www.หนังโป๊หี.tv
คลิปหลุดหี.com`

Why you believe this should be added:

Add to list:

Porn

Other info you think we should know:

This domains was add to porn list (issue #374 ) but seems invalid in Gravity log After Gravity update.

![IMG_20210707_072637](https://user-images.githubusercontent.com/76562017/124705384-e37e6f80-def5-11eb-958f-68e9b9f1096f.jpg)

**Comment by blocklistproject** [comment]
These will have to be removed. Most devices we support are unable to handle non English characters.

**Comment by Titomrock21** [comment]
Should i change issue to [remove request] ?

**Comment by blocklistproject** [comment]
This has been fixed
