### ISSUE TITLE
[Add request] Porn domains

### ISSUE THREAD

**Issue by iam-py-test** [blocklistproject/Lists#388]
URLs you wish to be added:
```
0.0.0.0 hegreartnudes.com
0.0.0.0 www.hegreartnudes.com
0.0.0.0 fancelebs.com
0.0.0.0 www.reachporn.com
0.0.0.0 reachporn.com
0.0.0.0 babesdiscounts.com
0.0.0.0 www.babesdiscounts.com
0.0.0.0 eroticbeauties.com
0.0.0.0 www.eroticbeauties.com
0.0.0.0 mail.eroticbeauties.com
0.0.0.0 4fuq.com
```
Why you believe this should be added:
These are porn
Add to list:
Porn
Other info you think we should know:
These domains should be able to be copypasted directly into the list

**Comment by fishcharlie** [comment]
Just by doing a curl request to `www.reachporn.com` and looking at the HTML content it looks like this website does not contain any explicit content and is simply a directory to other explicit websites. I think this project should be hesitant about including websites that don't contain the content we are blocking themselves.

I could be missing something here, so someone might want to do a more in depth look to ensure I'm not missing something. Maybe some JavaScript is adding content in after the fact?

**Comment by iam-py-test** [comment]
@fishcharlie I was just looking at the AV rating for these domains and McAfee & FortiGuard rate it as _Pornography_

**Comment by iam-py-test** [comment]
@fishcharlie I am checking it out in a VM. 
Please wait

**Comment by fishcharlie** [comment]
@iam-py-test Yeah. I try to look at the HTML content behind it as well to get a better sense of what is going on (and in this case use curl to get a response without loading it in the browser). It's up to @blocklistproject about the policies here. It's obviously a lot easier to load ads domains in your browser and such to confirm.

Especially with this category, I tend to use Safari with the developer tools enabled to `Disable Images`. That is a really helpful tool in this case.

**Comment by iam-py-test** [comment]
> @iam-py-test Yeah. I try to look at the HTML content behind it as well to get a better sense of what is going on (and in this case use curl to get a response without loading it in the browser). It's up to @blocklistproject about the policies here. It's obviously a lot easier to load ads domains in your browser and such to confirm.
> 
> Especially with this category, I tend to use Safari with the developer tools enabled to `Disable Images`. That is a really helpful tool in this case.

I don't have safari (my VM is Linux) so I can't do that.
However, uBlock Origin with `*$image` works for me.
One problem; without images, you can't tell if it is porn or not

**Comment by iam-py-test** [comment]
I have confirmed there is porn content.
Example URL: ``

**Comment by fishcharlie** [comment]
@iam-py-test Very true. Allows you get an initial sense of the content tho. Sometimes `Disable Images` gives you enough information to know it should be added to the list.

**Comment by fishcharlie** [comment]
@iam-py-test Yep, I'm fine with that. Thanks for double checking. I can create a PR for this.

**Comment by iam-py-test** [comment]
@fishcharlie I can open a PR

**Comment by fishcharlie** [comment]
@iam-py-test Already done: #390
