### ISSUE TITLE
[Add request] - l.tyrantdb.com

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [blocklistproject/Lists#397]
URL you wish to be added:
l.tyrantdb.com

Why you believe this should be added:
Redirect to porn/ad

Add to lists:
Porn, ads

Other info you think we should know:

**Comment by blocklistproject** [comment]
Unbale to find this domain when I tried to confirm. Can you provide additional info please

**Comment by SodaWithoutSparkles** [comment]
Thats a lower-case L not a cap i.

When you click on some ads, it first redirects you to l.tyrantdb.com/something then to the ad/porn site, like 54647.io, which you just added to the list. 

By adding that to blacklist it could prevent the redirection to said sites.

**Comment by blocklistproject** [comment]
This has been resolved. Thank you!
