### ISSUE TITLE
[Add request] - sta.anicdn.com

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [blocklistproject/Lists#398]
URL you wish to be added:
sta.anicdn.com

Why you believe this should be added:
Ads (may also have NSFW ads)

Add to list:
Ads

Other info you think we should know:

A little bit aggressive, may block things that arent ads too, like some icons. 
This was seen on a video-sharing site, blocking this would cause some icons not showing correctly, but dont have any effects on the video itself.

**Comment by blocklistproject** [comment]
These have been added. Thank you
