### ISSUE TITLE
Quote's on beginning and end of domains

### ISSUE THREAD

**Issue by tuurie72** [blocklistproject/Lists#4]
[i] Target: https://raw.githubusercontent.com/blocklistproject/Lists/master/malware.txt
[✓] Status: Retrieval successful
[i] Received 718213 domains, 245011 domains invalid!
      Sample of invalid domains:
      - -sso.anbtr.com"
      - 0-07.ru"
      - 0-day.us"
      - 000001.ink"
      - 00005ik.rcomhost.com"

example from the raw list:

0.0.0.0	"	rapidshare2download.net"

**Comment by blocklistproject** [comment]
This has been fixed and pushed to master
