### ISSUE TITLE
[Remove Request] - Crypto

### ISSUE THREAD

**Issue by Titomrock21** [blocklistproject/Lists#403]
URL you wish to be removed:

`coinmarketcap.com`
`coinbase.com`
`www.binance.com`

Why you believe this to be a false positive:

This sites are serious crypto exchange platform

List it is on:

Crypto

Other info you think we should know:

**Comment by fishcharlie** [comment]
I think this issue should be closed. The README clearly states `Can break normal "good" crypto sites`. As it stands right now, I don't think we should be in the business of determining good vs bad, or serious vs not serious.
