### ISSUE TITLE
[Add request] - Abuse

### ISSUE THREAD

**Issue by Titomrock21** [blocklistproject/Lists#405]
URL you wish to be added:

`real-debrid.com`

Why you believe this should be added:

site to create premium link

Add to list:

Abuse

Other info you think we should know:

**Comment by blocklistproject** [comment]
How does this constitute abuse? No doubting it but would like further explanation

**Comment by Titomrock21** [comment]
"Alldebrid" is in the abuse list, "real-debrid" is a similar site (premium link generator), but "alldebrid" is the onlyone to be in the block list (a lot of domains are similar).
Two choice, add real-debrid and other domains or remove alldebrid from list ?
