### ISSUE TITLE
[Add request]Add these porn sites

### ISSUE THREAD

**Issue by ahmed-tasaly** [blocklistproject/Lists#406]
Aloha there ,

URL you wish to be added:
```
8muses.net
toppornguide.com
ilikecomix.com
xlecx.org
milftoon.site
myhentaicomics.com
hdporncomics.com
gilftoon.com
porncomixone.net
porncomicsfree.net
wporncomics.com
www.porncomichub.com
cartoonxxx.in
hornyson.com
bestporncomix.com
www.kenyaadultblog.com
erocomicsxxx.com
comicspornoxxx.com
savitahd.net
indianpornlist.com
www.velammacomics.vip
www.comicsporn.xxx
comicporns.com
worldporncomix.com
wsexcomics.com
fotonovelasxxx.com
newpornsites.org
allpornsite.net
hotporn.today
www.familycuckolds.com
www.epicafri.com
www.localcamgirls.net
www.mylked.com
www.bffs.com
www.bracefaced.com
www.cospuri.com
www.lollipopgirls.jp
www.scoreland.com
www.tittyattack.com
www.gingerpatch.com
www.shoplyfter.com
downtofuckdating.com
abbiemaley.com
www.pervmom.com
hotmilfsfuck.com
fist4k.com
genuinesin.com
theflourishfetish.com 

```

Why you believe this should be added: **Porn Websites**

Add to list: **Porn**

### Edited:
I think this is  as you wanted

### Edited 2 : 
I removed  /  as you stated

**Comment by Titomrock21** [comment]
Hi,

please write the domain names between `` and delete "https://"
for example:   `www.domanexample.com`

**Comment by ahmed-tasaly** [comment]
@Titomrock21 
OK

**Comment by Titomrock21** [comment]
> @Titomrock21
> OK

please write the domain names between `` like `www.domanexample.com`

**Comment by ahmed-tasaly** [comment]
> > @Titomrock21
> > OK
> 
> please write the domain names between `` like `www.domainexample.com`
> delete /

OK, done

Thanks in advance

**Comment by iam-py-test** [comment]
@ahmed-tasaly `8muses.net` has already been added

**Comment by ahmed-tasaly** [comment]
> @ahmed-tasaly `8muses.net` has already been added

@Titomrock21 
@iam-py-test 

No, I didnt find it in the list

**Comment by iam-py-test** [comment]
It was added in https://github.com/blocklistproject/Lists/commit/8c0ed8461642496a263bba5ce05c6e4e44d01458.
![image](https://user-images.githubusercontent.com/84232764/126080101-f059fe59-3c12-4671-8076-1a1b42eb1ba3.png)

**Comment by iam-py-test** [comment]
I can open a PR to fix this
