### ISSUE TITLE
[Add request] - img.molimao.top, p.qlogo.cn

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [blocklistproject/Lists#407]
URL you wish to be added:
`img.molimao.top`
`p.qlogo.cn`

Why you believe this should be added:
NSFW ad

Add to list:
Porn, ad

Other info you think we should know:
Source of 18+ ad

[Sample 1](https://img.molimao.top/jm/upload/vod/20210703-1/6602026046a3115288f5e131d17cb376.gif)
[Sample 2](https://p.qlogo.cn/qqmail_head/ajNVdqHZLLC2ykfRHXCwU8kvibMQG7R0Uhbs9ibJA0onVzPm8HF5O3bDTMuw1o0AMevUIn8NZPDvQ/0)

**Comment by blocklistproject** [comment]
Unable to confirm this. I am on a secure network right now. Can you @fishcharlie confirm this one?

**Comment by fishcharlie** [comment]
@SodaWithoutSparkles There is not enough information to verify this. Making a request to this domain results in a 403 error.

Can you provide more details about where you found this domain? And some evidence or links to specific content on the domain that demonstrates these claims?

**Comment by SodaWithoutSparkles** [comment]
Found ad on a pirate site:
`https://jumi.tv/vod/24639.html`

If you want the direct ad, [here](https://img.molimao.top/jm/upload/vod/20210703-1/6602026046a3115288f5e131d17cb376.gif)
And I also discoverex another NSFW ad in the progress. Will edit the post later.

**Comment by SodaWithoutSparkles** [comment]
I think they are supposed to be porn ads, so shouldnt they be added to list porn **and** list advert as well?

**Comment by SodaWithoutSparkles** [comment]
browse 

```
https://jumi.tv/vod/115229.html
```
On mobile for qlogo.cn

**Comment by SodaWithoutSparkles** [comment]
https://user-images.githubusercontent.com/64138578/129074068-a373c6e1-b8c4-40d3-941e-9a93353af1a3.mp4

I got an app that shows elements on mobile. According to that I saw the qlogo.cn

Also I saw that in my pihole query, and after blocking it I dont see the banner ad
