### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by iam-py-test** [blocklistproject/Lists#413]
URL you wish to be added:
```
0.0.0.0 name-usa.info
0.0.0.0 s.lletlee.com
0.0.0.0 b.xyzgame.cc
0.0.0.0 xyzgame.cc
0.0.0.0 lletlee.com
0.0.0.0 incasso-fod.su
```
Why you believe this should be added:
These are malware domains, probably C2s.
Add to list:
Malware
Other info you think we should know:
These were contacted by https://www.virustotal.com/gui/file/e5a2f1f92189919272d6a14bbd16934ee66464a6cb90f30f00abaf0a204e4307/relations

**Comment by blocklistproject** [comment]
These have been added
