### ISSUE TITLE
[Remove Request] - Abuse and Malware

### ISSUE THREAD

**Issue by Dennisbonke** [blocklistproject/Lists#417]
URL you wish to be removed: duo.nl

Why you believe this to be a false positive: this site is ran by the Dutch Ministry of Education and students use this site to manage their student loans.

List it is on: It’s on the abuse and malware list as far as I know, it might be on others but I don’t have all lists in my pi-hole.

Other info you think we should know:

**Comment by blocklistproject** [comment]
This has been resolved
