### ISSUE TITLE
[Remove Request] - opensearch.org in malware and abuse lists

### ISSUE THREAD

**Issue by Homas** [blocklistproject/Lists#419]
URL you wish to be removed:
opensearch.org

Why you believe this to be a false positive:
The domain was registered in 2003 and it is not know as malicious by TI vendors and antiviruses (checked on virus total).
It is an opensource and related to IT category.

List it is on:
malware and abuse

Other info you think we should know:

**Comment by blocklistproject** [comment]
This has been removed. Thank you
