### ISSUE TITLE
Use a GitHub Pages site to host lists

### ISSUE THREAD

**Issue by Wxfisch** [blocklistproject/Lists#42]
The use of raw.githubusercontent URLs is considered bad form for PiHole since it will re-download the list every time it updates. you should set up a GitHub Pages site and then use those URLs to point to the lists. This will include the last-modified data in the header preventing PiHole from pulling the list if nothing has changed. The addresses for the lists would then be similar to:

https://blocklistproject.github.io/Lists/Malware

These are smaller URLs as well which are easier to read on the web interface (while also reducing wear on an SD card for PiHole hosted on actual Raspberry Pi hardware due to not downloading unless there are changes). This would not break anyone that is currently using the raw.githubusercontent URLs, but would provide a better source for anyone that wants to change them over as well as new users.

More Information:
https://discourse.pi-hole.net/t/i-concatenated-every-blocklist-i-could-find/5184/2
https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site

**Comment by blocklistproject** [comment]
I have to admit, I am VERY new to GitHub. Let me see what I can figure out.

**Comment by blocklistproject** [comment]
I think I got it figured out.
