### ISSUE TITLE
[Remove Request] - Abuse

### ISSUE THREAD

**Issue by Titomrock21** [blocklistproject/Lists#425]
URL you wish to be removed:

`Alldebrid.com`

Why you believe this to be a false positive:

Premium link generator

List it is on:

Abuse

Other info you think we should know:

**Comment by blocklistproject** [comment]
This issue has been fixed. I did leave it on the "redirect" list because it is a redirect site.

**Comment by spirillen** [comment]
@blocklistproject 

Can you show an example of that? as I can't find anyone else who blacklist this domain

`hosts-sources$ git grep 'Alldebrid.com'`
