### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by saumyakswain** [blocklistproject/Lists#426]
URL you wish to be added: 
`www.xvideos.com`
`www.xhamster.com`
`xhamster13.desi`

Why you believe this should be added: These subdomains of the porn sites are missing in the list. While, for example, access to `xvideos.com` is blocked, the same thing is accesible through `www.xvideos.com`.

Add to list: porn

Other info you think we should know:

**Comment by saumyakswain** [comment]
> @saumyakswain please update your comment & put ` around the domains as to prevent them from being autolinked

Updated, thanks.

**Comment by blocklistproject** [comment]
These have been added. Thank you
