### ISSUE TITLE
[Remove Request] - metrics.icloud.com

### ISSUE THREAD

**Issue by fishcharlie** [blocklistproject/Lists#433]
**URL you wish to be removed:**

```
metrics.icloud.com
```

**Why you believe this to be a false positive:**

Couple of things here.

1. I can find no evidence that this domain is used for serving ads. It looks solely dedicated to metrics and telemetry.
2. Apple's privacy policies and ease of opting out of these metrics/analytics are incredibly easy (simple toggle in settings).

I guess you could make an argument that it belongs on the tracking list. But with Apple's focus on things like differential privacy, it's hard to argue that it's tracking related.

Therefore I think it should be removed entirely.

**List it is on:**

- Ads

**Other info you think we should know:**

**Comment by blocklistproject** [comment]
This has been removed from ads but added to tracking. Thank you
