### ISSUE TITLE
[Remove Request] -  Blocking Amazon Cognito - cognito-identity.us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by p1r473** [blocklistproject/Lists#437]
**URL you wish to be removed**: cognito-identity.us-east-1.amazonaws.com

**Why you believe this to be a false positive:**
Amazon Cognito is required for some AWS apps.
For me, it is breaking SensorPush app.
"Amazon Cognito helps you create unique identifiers for your end users that are kept consistent across devices and platforms. Amazon Cognito lets you add user sign-up, sign-in, and access control to your web and mobile apps quickly and easily.

**List it is on:**
https://raw.githubusercontent.com/blocklistproject/Lists/master/ads.txt

**Comment by blocklistproject** [comment]
This has been fixed. Thank you!
