### ISSUE TITLE
Ip addresses in a hosts file?

### ISSUE THREAD

**Issue by spirillen** [blocklistproject/Lists#438]
Hey guys, as I have been monitoring your repo for some time and used it as a indexing / lookup in my [hosts-sources](https://github.com/Import-External-Sources/hosts-sources) I was updating the import script with your alt-version (saving me the process time of cleaning up the hosts file) I spotted the following IP's in the lists.

https://github.com/blocklistproject/Lists/blob/2472bed677f1b269970ba9e25cd857d393d32b5f/alt-version/tracking-nl.txt#L132-L136

For what I understand from your scripts, this is primarily a hosts file project, hence the above is wrong.

------

Next to this I think we have a common base for which we should be thinking of collaborating with each other as our project have a lot of similarity. Give it a though and lets get back to this else where,

**Comment by fishcharlie** [comment]
@spirillen I don't think this is the most urgent issue. I've yet to hear of any reports of this causing errors or problems for popular DNS servers, and there might be someone who wants to make use of that data (I'm currently in the process of updating my DNS server to check responses against the block lists IP addresses).

I don't think there is anywhere that says this claims to be a host lists file, does it? It advertises itself as a block list.

It should be pretty easy to filter out that data tho on your side.

I vote we close this issue, but I'll leave it up to @blocklistproject incase there is anything to add that I missed.

**Comment by spirillen** [comment]
> DNS server to check responses against the block lists IP addresses).

Are you speaking of RPZ??

> I don't think there is anywhere that says this claims to be a host lists file, does it? It advertises itself as a block list.

That is why I wrote

>> For what I understand from your scripts, this is primarily a hosts file project, hence the above is wrong.

**Comment by blocklistproject** [comment]
This has been addressed in a pull. Please let us know if the issue still remains. Thank you!
