### ISSUE TITLE
pishing site viaemail.bunwaejrx.com

### ISSUE THREAD

**Issue by nasatome** [blocklistproject/Lists#44]
Pishing Paypal site in MX

domain to block: viaemail.bunwaejrx.com

![image](https://user-images.githubusercontent.com/18271791/89809932-e617ef80-db01-11ea-8764-2e0bcbf18e65.png)

will it be good to add the root domain?
bunwaejrx.com

**Comment by blocklistproject** [comment]
Thank you for helping
