### ISSUE TITLE
[Add request] Porn

### ISSUE THREAD

**Issue by kprkpr** [blocklistproject/Lists#441]
URL you wish to be added:
cdnlt3.serviporno.com
cdnlt2.serviporno.com
pics2.serviporno.com
pics.serviporno.com
www.serviporno.com
onlyfans.com
www.gifs-porno.com
img.porn18videos.com
porn18videos.com
cdn77-vid.xvideos-cdn.com
www.fapvidhd.com
www.pasionmujeres.com
www.pornogaygratis.net
www.canalporno.com
static.pornogratisdiario.com
embed.pornogratisdiario.com
www.pornogratisdiario.com
api.ozeex.com
ozeex.com
elmundoporno.com

Why you believe this should be added:
They have porn

**Comment by spirillen** [comment]
As you might find additional info on the links below I'll thanks for the rest as new for [Porn Records](https://mypdns.org/my-privacy-dns/porn-records)

serviporno.com: https://mypdns.org/my-privacy-dns/porn-records/-/issues/182
onlyfans.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/1812 (Tracking), https://mypdns.org/my-privacy-dns/porn-records/-/issues/25 (Adult)
xvideos-cdn.com: https://mypdns.org/my-privacy-dns/porn-records/-/issues/185
pornogratisdiario.com: https://mypdns.org/my-privacy-dns/porn-records/-/issues/190

**Comment by kprkpr** [comment]
Sorry for duplicating someones.. Seems that opnsense with so much hosts files didn't blocked it, but maybe its because its a 61MB hosts file 😂 I hate hosts files, so large

**Comment by spirillen** [comment]
> Sorry for duplicating someones.. Seems that opnsense with so much hosts files didn't blocked it, but maybe its because its a 61MB hosts file joy I hate hosts files, so large

Then switch to DNS with full [RPZ](https://mypdns.org/mypdns/support/-/wikis/rpz) support.... like powerdns recursor then you have build in recursor, blacklist and whitelist and no more f**ked up dumb hosts files. That what [mypdns](https://mypdns.org/my-privacy-dns/matrix) is all about.

Never mind, there are maybe not dubles as I haven't checked within this project, only the linked ones
