### ISSUE TITLE
[Remove Request] - ||amazonaws.com^

### ISSUE THREAD

**Issue by peredoxx** [blocklistproject/Lists#452]
URL you wish to be removed:
||amazonaws.com^

Why you believe this to be a false positive:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/cxmbKPH/false-positive-amazonaws1.png" alt="false-positive-amazonaws1" border="0"></a>

<a href="https://ibb.co/56S5mYS"><img src="https://i.ibb.co/t4vbgZv/false-positive-amazonaws2.png" alt="false-positive-amazonaws2" border="0"></a>

<a href="https://ibb.co/CHTfRty"><img src="https://i.ibb.co/ZMk0qJr/false-positive-amazonaws3.png" alt="false-positive-amazonaws3" border="0"></a>

<a href="https://ibb.co/qJGS6hM"><img src="https://i.ibb.co/8Y3CkGD/false-positive-amazonaws4.png" alt="false-positive-amazonaws4" border="0"></a>

List it is on:
https://github.com/blocklistproject/Lists/blob/master/adguard/crypto-ags.txt

Other info you think we should know:

**Comment by blocklistproject** [comment]
This issue has been resolved. Thank you!
