### ISSUE TITLE
Why is the US Green Party's site blocked?

### ISSUE THREAD

**Issue by oelmekki** [blocklistproject/Lists#453]
www.gp.org is blocked in phishing.txt.

I've bissected the repository for it, and there is no explanation, it's been introduced in 0f11189d6338bb0695d8dae5c2ae7ec6e27fe541 when the list was created, with thousands of other domains.

I can't either find any reference to a phishing problem with that site - current or historical - which means it looks like the site was blocked for political reasons, while making it look like a technical reason. This is a serious and grave issue.

Please explain.

**Comment by stuaxo** [comment]
After from re-adding this, it potentially means the whole list should be checked entries that shouldn't be there.

**Comment by nero** [comment]
Torch and Pitchfork store opened at https://news.ycombinator.com/item?id=28114503

**Comment by austinheap** [comment]
It’s also listed in VirusTotal. Content like this puts the conspiracy to rest: https://webcache.googleusercontent.com/search?q=cache:HWH6z4cPUYMJ:https://www.gp.org/shamim4s/_streaming-live_-_2020_tokyo_olympic_games_live_free_23th_july_2021+&cd=15&hl=en&ct=clnk

**Comment by hentaij666** [comment]
Just saw your post and I have no problem accessing the US site with and without a VPN, so I am not sure if the problem that you reported on has been fixed.

**Comment by blocklistproject** [comment]
We have absolutely no political bias represented in these lists. Now I would be more than happy to look into this issue. If you don't mind listing which list you say the domain has been included in and properly filling out the issue form.

**Comment by blocklistproject** [comment]
This issue will be closed so that you can redo the issue request. Lease feel free to link this issue in your new request. In the mean time I will look through the lists for the domain. Thank you
