### ISSUE TITLE
[Remove Request] - acorns-statements-production.s3-us-west-1.amazonaws.com

### ISSUE THREAD

**Issue by Nick2bad4u** [blocklistproject/Lists#457]
URL you wish to be removed: https://acorns-statements-production.s3-us-west-1.amazonaws.com

Why you believe this to be a false positive: This is a server/url used to download PDF statements from Acorns Investing.

List it is on: Crypto list

Other info you think we should know:

**Comment by blocklistproject** [comment]
This should have been fixed with issue #452. Please let us know.
