### ISSUE TITLE
[Remove Request] - 

### ISSUE THREAD

**Issue by sathyacs** [blocklistproject/Lists#460]
URL you wish to be removed: netflixreality.com

Why you believe this to be a false positive:

Netflix recently launched a reality casting site for consumers to upload their casting video: http://netflixreality.com/ . The domain netflixreality.com is recorded in some of your files as suspicious. We received reports from consumers that they are not able to load the site due to warning messages. We can guarantee that the site does not contain any malicious content. Request you to kindly remove our domain from your block lists so our consumers can continue using the site without any issues.

Thanks
Sathya

Senior Security Engineer
Netflix

List it is on:

Our domain was found in the following files from this project: https://github.com/badmojr/1Hosts

Pro/adblock.txt
Pro/wildcards.txt
Pro/hosts.txt
Pro/rpz.txt
Pro/unbound.conf
Pro/dnsmasq.conf
Pro/domains.wildcards
Pro/hosts.win
Pro/domains.txt
Xtra/adblock.txt
Xtra/wildcards.txt
Xtra/rpz.txt
Xtra/hosts.txt
Xtra/unbound.conf
Xtra/dnsmasq.conf
Xtra/hosts.win
Xtra/domains.wildcards
Xtra/domains.txt

Other info you think we should know:

**Comment by spirillen** [comment]
To Netflix, Senior Security Engineer @sathyacs 

Please secure your site contents from malicious software like:

SpyWare
```html
    <!-- OneTrust Cookies Consent Notice start for netflixreality.com -->
    <script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js" type="text/javascript" charset="UTF-8" data-domain-script="2d6d20f0-24d0-4353-8ca5-e9d5c04bda13"></script>
    <script type="text/javascript">function OptanonWrapper(){}</script>
    <!-- OneTrust Cookies Consent Notice end for netflixreality.com -->
```

```html
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XJBLHCCS0F"></script>
    <script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","G-XJBLHCCS0F")</script>
```

ScamWare
```html
<strong>You.</strong></h1> <div class="the-home-hero__subtitle">The Largest Reality Casting Call. <strong>Ever.</strong>
```

So your consumers can using the site without any issues.

**Comment by blocklistproject** [comment]
This has been removed. Thank you!
