### ISSUE TITLE
[Add request] - Malware ? redirect ?

### ISSUE THREAD

**Issue by Titomrock21** [blocklistproject/Lists#462]
URL you wish to be added:

`secure.protect-pc-plus.xyz`

Why you believe this should be added:

![image](https://user-images.githubusercontent.com/76562017/129598828-233b709f-d34a-478f-bfcd-8d483bd66db2.png)

Add to list:

Malware ? redirect ?

Other info you think we should know:

**Comment by spirillen** [comment]
Seems unneeded

```shell
curl -I 'secure.protect-pc-plus.xyz'
HTTP/1.1 301 Moved Permanently
Date: Mon, 16 Aug 2021 19:23:57 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Mon, 16 Aug 2021 20:23:57 GMT
Location: https://secure.protect-pc-plus.xyz/
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=dQHBIpz0tufV4fQOtLFF3xaz4vM38NuFoOiGRoR3AF%2FWsAyIf4mTNsEpurO6bLn6qnLqP%2BxshSwfoypNWyO9otDtOwX2xWW2W%2F9hRvoa6T7Rb7VCF%2FjwSksAoVC%2FBb2GdoffuL%2BMgmt0muGwvg%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 67fd0a465b7e10b5-CPH
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
```

![image](https://user-images.githubusercontent.com/44526987/129618637-e2438f7a-e348-4363-be2c-0750fac2acce.png)

**Comment by Titomrock21** [comment]
Site seems offline

**Comment by spirillen** [comment]
> Site seems offline

HTTP status code 403 is not offline, it means ONLINE, it just tells you, you shall not pass, thanks Gandalph :mage:
