### ISSUE TITLE
[Remove Request] - zombo.com

### ISSUE THREAD

**Issue by p1r473** [blocklistproject/Lists#463]
URL you wish to be removed: zombo.com

Why you believe this to be a false positive: Its not a malicious site. Its more of a joke site

List it is on: ads.txt 

Other info you think we should know:

**Comment by iam-py-test** [comment]
@blocklistproject this website does seem just to be a joke site (it is rated as Entertainment by most AVs and is not detected as malware/ads by any)
See https://www.virustotal.com/gui/url/a3a20d3bf1f255d7943c079dd818dad170cad00d985387d8ab8d196187495f97/community
Maybe there are ads/adfiltes on other parts of it?

**Comment by blocklistproject** [comment]
This has been fixed, Thank you!
