### ISSUE TITLE
[Add request] Malware domains

### ISSUE THREAD

**Issue by iam-py-test** [blocklistproject/Lists#468]
URL you wish to be added:
```
0.0.0.0 google-analitics91.com
0.0.0.0 xsph.ru
0.0.0.0 a0568605.xsph.ru
0.0.0.0 dubem.top
0.0.0.0 2freeprivacytoolsforyou.xyz
```
Why you believe this should be added:
These are malware
Add to list:
Malware
Other info you think we should know:
These domains are from my blocklists and were verified before adding

**Comment by blocklistproject** [comment]
These have been added, Thank you
