### ISSUE TITLE
[Remove Request] - ads-twitter[.]com

### ISSUE THREAD

**Issue by iam-py-test** [blocklistproject/Lists#469]
URL you wish to be removed:
`ads-twitter.com`

Why you believe this to be a false positive:
I am pretty sure this is not malware; I think it is twitter ads.
See https://www.virustotal.com/gui/url/5af5a554e0645a6d33343a2b713d63e336e54e9b952edc779cb4ae6bd3c628cf/community

List it is on: Antimalware

Other info you think we should know: 
Thank you for maintaining malware, phishing, ad, porn, etc blocklists!

**Comment by spirillen** [comment]
Yes this is AdWare: 

Link to my archive of the domain: https://mypdns.org/my-privacy-dns/matrix/-/issues/873

**Comment by iam-py-test** [comment]
> Yes this is AdWare:
> 
> Link to my archive of the domain: https://mypdns.org/my-privacy-dns/matrix/-/issues/873#relevant-logs-andor-screenshots

@spirillen 
Domains used for advertising should not be blocked as malware, they should be blocked as ads

I am not in any way on the side of the ad guys; please do not interpret this as saying ads should not be blocked

**Comment by fishcharlie** [comment]
@iam-py-test I do not believe we should be relying so heavily on 3rd party tools to determine if a domain should or shouldn't be included on these lists. Those 3rd party tools are not reliable at all, and open the door to a world of problems.

cc/ @blocklistproject

**Comment by spirillen** [comment]
@iam-py-test Yes they are only used by twitter to serve ads. and I have no collected information that indicates anything else.

@fishcharlie this "third-party" "tool" which is a declared information collecting about domains and there purpose: https://archive.mypdns.org/project/view/15/

**Comment by iam-py-test** [comment]
I guess this issue can be closed?

**Comment by cryptogap** [comment]
At this time this will be closed. Please feel free to open another issue request if you feel you have additional info. Thank you very much for being a valued contributing member of the community!
