### ISSUE TITLE
[Remove Request] - a-msedge.net

### ISSUE THREAD

**Issue by Wunderharke** [blocklistproject/Lists#473]
URL you wish to be removed:

a-msedge.net

Why you believe this to be a false positive:

Several Microsoft websites are served as subdomains via CNAME so blocking this prevents e.g login at www.live.com (a-0010.a-msedge.net). 

List it is on:

ads.txt

Other info you think we should know:

I'm aware that there are possibly also ads served at this domain however (at least for me) this list is not usable when major services stop working.

**Comment by cryptogap** [comment]
This has been fixed. Thank you!
