### ISSUE TITLE
PLEASE BAN payin7.com THIS IS scam website 

### ISSUE THREAD

**Issue by bgman111111** [blocklistproject/Lists#478]
PLEASE help. we try buy hard disk and it cost 200 euros so payin7.com get from us money 48.xx euros for 4 monts to pay for hard disk from speedler.com and when i hear it will on my computer so i cancel hard disk. include they have phone that DONT have humankind support,. and th has e-mail that DON'T work tiendas@payin7.com this is email only for shops and THERE THEY SCREAM if peoples are NOT FROM SHOPS. speedler has canceled hard disk AND now payin7.com DONT WANT to return money. on web site they comment send license photos and passport we send them to they and now THEY try foce send SELFIE in SPANISH LAWS this is crime. On all website that payin7.com Comment only spanish identificati and passport and no selfi. THIS IS CRIME. now we are in denounce payin7.com PLEASE share it if necessary i will send documentation. Here you can see much PEOPLES complaint from payin7.com:

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES00836529-01 - Scam when charging first installment of non-existent financing

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES01330900-60 - Western Digital WD40EFZX 4TB SATA3 Red Plus financing payin7.com DISASTER

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES00865607-76 -
RETURN OF THE CHARGES MADE and LOW FINANCING FOR NEVER RECEIVING THE ARTICLE
Claim
PAYIN7, S.L.
Claim closed Resolved Managed with the intervention of OCU

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES00868214-64 - behind
Problem with the purchase item

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES01129071-88 - behind
I want my € 199.31 that has been stolen from me

there is MUCH PEOPLES SCREAMING FROM THIS shit crime website.

**Comment by cryptogap** [comment]
I have reviewed what happened. I am truly sorry for the issues you have had to deal with but unfortunately we are not able to deem the site a scam base on this singular issue. I hope that you are able to find a solution.

**Comment by spirillen** [comment]
The domainname it self should have sounded the big red suspicious alarm ...

**Comment by bgman111111** [comment]
> I have reviewed what happened. I am truly sorry for the issues you have had to deal with but unfortunately we are not able to deem the site a scam base on this singular issue. I hope that you are able to find a solution.

Are you blind. There is much peoples complaining against this shit. 


Here you can see much PEOPLES complaint from payin7.com:

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES00836529-01 - Scam when charging first installment of non-existent financing

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES01330900-60 - Western Digital WD40EFZX 4TB SATA3 Red Plus financing payin7.com DISASTER

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES00865607-76 -
RETURN OF THE CHARGES MADE and LOW FINANCING FOR NEVER RECEIVING THE ARTICLE
Claim
PAYIN7, S.L.
Claim closed Resolved Managed with the intervention of OCU

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES00868214-64 - behind
Problem with the purchase item

https://www.ocu.org/reclamar/lista-reclamaciones-publicas/reclamacion-publica?referenceId=CPTES01129071-88 - behind
I want my € 199.31 that has been stolen from me

In google there is much peoples complaining.  You have to make links to all scam website so every peoples can see github link this has to stop

**Comment by spirillen** [comment]
I understand your frustration, but this issue is for now not a scam problem as it is seriously bad costumer relation.

I have also visited the page, but I do not understand Spanish/portogese, so what is it who have "paid for?? the entire site loos spokie to me.

And the whois information is withheld. So why is it you transferred any money to them and for what in exchange?
