### ISSUE TITLE
[Remove Request] - behance.net

### ISSUE THREAD

**Issue by CYB3RL4MBD4** [blocklistproject/Lists#482]
URL you wish to be removed:
behance.net

Why you believe this to be a false positive:
It is a site for graphical creative works, designer work.

List it is on:
abuse.txt
ads.txt

Other info you think we should know:
A graphical designer gave me his link to show me his work and as I could not access it, I checked in my pi-hole why and it was on these two lists.

**Comment by cryptogap** [comment]
Fixed, Thank you
