### ISSUE TITLE
[Remove Request] - api.punchh.com

### ISSUE THREAD

**Issue by chiefgecko** [blocklistproject/Lists#484]
https://blocklistproject.github.io : api.punchh.com

blocks Pei Wei (peiwei.com) online ordering @api.punchh.com
=====
 Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:
   go.punchh.com 
 Match found in https://blocklistproject.github.io/Lists/ads.txt:
   api.punchh.com       <<<<< whitelisting just this one returns peiwei online ordering to working state
   apidq.punchh.com 
   cdn.punchh.com 
   dl.punchh.com 
   focusdl.punchh.com 
   focusios.punchh.com 
   hooks.punchh.com 
   isl.punchh.com 
   mobileandroidapi.punchh.com 
   mobileiosapi.punchh.com 
   pinger.punchh.com 
   pos.punchh.com 
   poslogs.punchh.com

**Comment by cryptogap** [comment]
Fixed, Thank you
