### ISSUE TITLE
[Remove Request] - everydayhealth.com

### ISSUE THREAD

**Issue by alihasan** [blocklistproject/Lists#486]
URL you wish to be removed:
everydayhealth.com

Why you believe this to be a false positive:
I work for EverydayHealth (a health and wellness content company) and recently had PiHole deployed on my home network; I was surprised to find everydayhealth.com on the malware and abuse blocklists.  Can I request for our domain to be reviewed and removed from these lists?  EverydayHealth seeks to provide high-quality health and wellness content written under a well documented editorial policy: https://www.everydayhealth.com/editorial-policies/.  All of our content is expertly written and goes through a rigorous Medical Review process to ensure that all content is factually and medically accurate.

List it is on:
malware
abuse

Other info you think we should know:

**Comment by cryptogap** [comment]
Fixed, Thank you
