### ISSUE TITLE
[Remove Request] - CDBurnerXP

### ISSUE THREAD

**Issue by Trainax** [blocklistproject/Lists#488]
URL you wish to be removed:

- `cdburnerxp.se`
- `www.cdburnerxp.se`

Why you believe this to be a false positive:

CDBurnerXP is a software to burn CDs and DVDs and it's not malware. [Wikipedia page](https://en.wikipedia.org/wiki/CDBurnerXP)

List it is on:

- Abuse
- Malware

Other info you think we should know:

**Comment by cryptogap** [comment]
Fixed, Thank you
