### ISSUE TITLE
[Add request] PUP

### ISSUE THREAD

**Issue by iam-py-test** [blocklistproject/Lists#497]
URL you wish to be added:
```
0.0.0.0 pcspeedup.en.softonic.com
```
Why you believe this should be added:
This is a PUP/Scam:
VT scan: https://www.virustotal.com/gui/file/f4c52b111e5b8a3314c123f7403d165f46f082822720d68031aec82cf36b0b85/detection
It detected a ton of (fake) issues on a safe (apart from it) VM:
![image](https://user-images.githubusercontent.com/84232764/133928081-20448f07-bc93-4cdd-a53e-4e431907dfb3.png)
To fix them, you need to sign up:
![image](https://user-images.githubusercontent.com/84232764/133928105-54539030-924e-4548-8b40-423c4f6c4673.png)
Their website is blocked by my security solution as _malware_.
Real AV scans of the VM:
![image](https://user-images.githubusercontent.com/84232764/133928157-7deacfb5-280a-4f17-9ec7-9f48d0fcbf05.png)

Add to list:
Not sure. Maybe malware, scam, fraud?
Other info you think we should know:
If you want to check out the sample on a VM, I uploaded it [here](https://github.com/iam-py-test/malware_samples/blob/main/SAMPLES/PUPs/pc-speed-up-setup.malware)
The installer was actually detected by Windows Defender on the VM, and I had to exclude it just to check
More information: 
https://answers.microsoft.com/en-us/protect/forum/all/pupoptionaltweakbit/e19128db-c9bc-4b53-877f-f93f8f63446a
https://forums.malwarebytes.com/topic/190111-removal-instructions-for-tweakbit-driver-updater/
https://www.bleepingcomputer.com/forums/t/617805/tweakbit/
Thank you for providing your free lists!

**Comment by spirillen** [comment]
Not that I've tested which might be active, but here is what i got in the DB from a very old import (some can be FP's)


|id|name|type|
|--|----|----|
|3464668|tweakbit.com|CNAME|
|3464669|static.tweakbit.com|CNAME|
|3464670|downloads.tweakbit.com|CNAME|
|3464671|dynamicdownloads.tweakbit.com|CNAME|
|3464672|www.tweakbit.com|CNAME|

|id|name|type|content|
|--|----|----|-------|
|3000485|en.softonic.com|CNAME|.|
|3245617|softonic.com|CNAME|.|
|3245618|pub.softonic.com|CNAME|.|
|3245619|gsf-cf.softonic.com|CNAME|.|
|3245620|serenescreen-marine-aquarium.en.softonic.com|CNAME|.|
|3245621|adserver.softonic.com|CNAME|.|
|3245622|freesoftonic.com|CNAME|.|
|3245623|www.freesoftonic.com|CNAME|.|

**Comment by iam-py-test** [comment]
@spirillen I got rid of the redundant domain
Thanks for pointing that out. I just completely forgot to check

**Comment by iam-py-test** [comment]
@cryptogap maybe it should go into Malware as well?

**Comment by iam-py-test** [comment]
I guess this can be closed as it has already been fixed...
