### ISSUE TITLE
"Github" string on torrent.txt got github.com DNS request blocked by firewall

### ISSUE THREAD

**Issue by vboufleur** [blocklistproject/Lists#51]
URL you wish to be removed: `0.0.0.0	div>Hosted On GitHub` 

Why you believe this to be a false positive: I was using this blocklist as a source for a firewall solution to drop torrent websites DNS packets. Having that line on the file caused DNS requests to github.com to be dropped. That line sounds like a defect which demanded me to stop using this blocklist on my firewall. Can't trust this list anymore.

List it is on:  https://github.com/blocklistproject/Lists/blob/master/torrent.txt#L1853

Other info you think we should know: This is a good blocklist and I intend to keep using it, but can't set my code to auto-fetch it and use it as a valid source due to this issue.

**Comment by gap579137** [comment]
That has been fixed. I apologize for any issue you ran into. I will also scan our other lists for issues like this.
