### ISSUE TITLE
[Add request] - scam

### ISSUE THREAD

**Issue by ghost** [blocklistproject/Lists#512]
URL you wish to be added:

`d2020yrahex7kc.cloudfront.net`

Why you believe this should be added:

![Capture](https://user-images.githubusercontent.com/76562017/136424335-7875df1b-80b7-475b-ad23-a6e49ad5605e.PNG)

Add to list:

scam

Other info you think we should know:

**Comment by iam-py-test** [comment]
This domain seems to be dead
Probably taken down by the scammers once the scammers realized they were figured out

**Comment by iam-py-test** [comment]
It might not matter
It is possible that the scammers would have taken it down anyway
I'd recommend reporting it as soon as possible

**Comment by spirillen** [comment]
Even that I'm not a fan of `cloudfront.net` I'll have to give them, they do take down illegal domains rather fast when reported to them.

So @Titomrock21 in the future you should send a secondary report to them on 

Registrar Abuse Contact Email: abusecomplaints@markmonitor.com
