### ISSUE TITLE
[Remove Request] - Ads

### ISSUE THREAD

**Issue by Titomrock21** [blocklistproject/Lists#532]
URL you wish to be removed:

`api.stream.proxad.net`
`media.stream.proxad.net`

Why you believe this to be a false positive:

it's "Free" internet access provider, if this domains are blocked, Freebox TV don't work

List it is on:

ads

Other info you think we should know:

**Comment by cryptogap** [comment]
Researched this and would recommend just whitelisting these. I am going to close this issue for now.
