### ISSUE TITLE
[Remove Request] - api.ad.intl.xiaomi.com

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [blocklistproject/Lists#536]
URL you wish to be removed:
(www.)api.ad.intl.xiaomi.com

Why you believe this to be a false positive:
Upon research and testing, this domain is part of the MIJA eco-system. For the app and the smart home feature to work, this is needed.

List it is on:
https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt

Other info you think we should know:
I havent tested if this would result in more ads or not. But unblocking this definately results in the app being much smoother and faster. The app just wont load the icons or the controls to the smart devices if this was not whitelisted.

**Comment by cryptogap** [comment]
Because it does specifically reference "ad" we are going to continue to block this domain and recommend just making sure it is whitelisted. Issue will be closed
