### ISSUE TITLE
[Remove Request] - chaturbate on ads.txt

### ISSUE THREAD

**Issue by jw243** [blocklistproject/Lists#541]
URL you wish to be removed:
chaturbate.com
de.chaturbate.com

Why you believe this to be a false positive:
The whole site does not work anymore. These are not per se ad-URLs, they are porn-URLs. They should not be on ads.txt.

List it is on:
ads.txt

Other info you think we should know:
ads.txt is used by dnsforge.de, a dns-service. By using this dns-service, chaturbate.com cannot be used anymore.

**Comment by cryptogap** [comment]
Fixed and closed, thank you!
