### ISSUE TITLE
[Add request] Crypto Scam

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#543]
URL you wish to be added:
```
https://connectwalletnow.com/live/
```

Why you believe this should be added: Crypto Scam. 

Add to list:
Fraud, Scam

Other info you think we should know: 
Reported on Reddit : https://preview.redd.it/wap5yaq83nw71.png?width=720&format=png&auto=webp&s=881685dd2ce2276019524e0ef9f6f1275f119638

**Comment by iam-py-test** [comment]
@alanjacobmathew the link you posted is dead:
![image](https://user-images.githubusercontent.com/84232764/140503729-95895e11-46cb-4bf9-9dff-c4c0328ea641.png)
