### ISSUE TITLE
[Remove Request] - app.link

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#546]
URL you wish to be removed: ```app.link```

Why you believe this to be a false positive: This URL helps users on Android devices be redirected to the appropriate App installed on the device. For example if I see a search result in Google which for example might be for a Reddit thread I can click on the result and a popup will show asking if I want to open this URL in the Reddit App. Currently when trying to do this it fails as I am using a blocklist associated with this project which is blocking the URL.

List it is on: Block List Project: Ads

Other info you think we should know: N/A

**Comment by cryptogap** [comment]
Fixed and closed, Thank you
