### ISSUE TITLE
[Remove Request] - nab.com.au

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#547]
URL you wish to be removed: ```nab.com.au```

Why you believe this to be a false positive: National Australia Bank (abbreviated NAB, branded nab) is one of the four largest financial institutions in Australia (colloquially referred to as "The Big Four") in terms of market capitalisation, earnings and customers.[5][6] NAB was ranked 21st-largest bank in the world measured by market capitalisation[7] and 52nd-largest bank in the world as measured by total assets in 2019.

List it is on: The Block List Project - Phishing

Other info you think we should know: How did a bank website end up on a phishing list?

**Comment by gyCfjSnO** [comment]
Any update on this? It's a legitimate website, still can't understand how or why it is blocked.

**Comment by cryptogap** [comment]
Fixed and closed, Thank you
