### ISSUE TITLE
[Remove Request] -  assets-jpcust.jwpsrv.com videos-fms.jwpsrv.com

### ISSUE THREAD

**Issue by p1r473** [blocklistproject/Lists#548]
URL you wish to be removed: assets-jpcust.jwpsrv.com videos-fms.jwpsrv.com

Why you believe this to be a false positive:
These domains block embedded videos
Here is an example of the embedded video i could not play
https://forums.androidcentral.com/droid-bionic/130214-battery-symbol-question-mark-inside.html

List it is on: ads.txt 

Other info you think we should know:

**Comment by cryptogap** [comment]
Fixed and closed, Thank you
