### ISSUE TITLE
[Remove Request] - js.intercomcdn.com

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#549]
URL you wish to be removed: ```js.intercomcdn.com```

Why you believe this to be a false positive: Unable to use or see Live Chat feature on websites running software/cloud solution 'Intercom'

List it is on: The Block List Project - Basic Starter List

Other info you think we should know: N/A

**Comment by cryptogap** [comment]
Fixed and closed, Thank you
