### ISSUE TITLE
[Remove Request] - trk.klclick.com

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#551]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):
```trk.klclick.com```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail: Unable to unsubscribe from marketing emails I am receiving to my email address. Picture attached of my AdGuard Home blocking ```trk.klclick.com``` as the domain ```klclick.com``` is on a blocklist I am using. I crosschecked other lists using ```https://blocklist-tools.developerdan.com/entries/search``` which brought me to your list which has the domain blocked.

![image](https://user-images.githubusercontent.com/49738152/140669540-5670e828-cb43-46c9-bf9a-396342d2bb83.png)

**Comment by cryptogap** [comment]
I would recommend whitelisting this so that you can unsubscribe. Removing this would do more harm than good.
