### ISSUE TITLE
[Remove Request] - settings-win.data.microsoft.com

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#552]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):

```settings-win.data.microsoft.com```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail:

> This endpoint is used to remotely configure diagnostics-related settings and data collection. For example, we use the settings endpoint to remotely block an event from being sent back to Microsoft. We do not recommend disabling this endpoint. This endpoint does not upload Windows diagnostic data.
> https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization

**Comment by cryptogap** [comment]
Will remove it from ads but not tracking

**Comment by cryptogap** [comment]
Fixed and closed, Thank you
