### ISSUE TITLE
[Remove Request] - download.windowsupdate.com.c.footprint.net

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#553]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):

```download.windowsupdate.com.c.footprint.net```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail:

Endpoint ```download.windowsupdate.com.c.footprint.net``` is used to download operating system patches and updates.

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions

**Comment by cryptogap** [comment]
Please provide supporting information

**Comment by gyCfjSnO** [comment]
Documentation here says the URL needs to be allowed so the OS can download patches and updates.

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions

**Comment by cryptogap** [comment]
Removed, thank you
