### ISSUE TITLE
[Remove Request] - self.events.data.microsoft.com

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#555]
### Issue(s):

- Website Broken

### Domain(s):

- Domain(s):

```self.events.data.microsoft.com```

### Your Config:

- Client: AdGuard Home
- Version: v0.107.0-b.14

### Detail:

- Your Issue Detail:

Endpoint ```self.events.data.microsoft.com``` is used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. If you turn off traffic for these endpoints, users won't be able to save documents to the cloud or see their recently used documents.

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

**Comment by cryptogap** [comment]
Fixed and closed, Thank you
