### ISSUE TITLE
[Remove Request] -  au.download.windowsupdate.com.c.footprint.net

### ISSUE THREAD

**Issue by IcedEagle** [blocklistproject/Lists#557]
URL you wish to be removed: 
au.download.windowsupdate.com.c.footprint.net

Why you believe this to be a false positive:
This domain is used to download Windows Updates. With this blocked, Windows will be unable to download any updates. This domain is a cname of the main domain listed here: https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions

List it is on:
abuse-nl
malware-nl

Other info you think we should know:
This document has the list of Windows endpoints, including this one for Windows Update: https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1709-non-enterprise-editions

**Comment by cryptogap** [comment]
Fixed and closed, Thank you
