### ISSUE TITLE
Issue + Request:

### ISSUE THREAD

**Issue by LucianAndries** [blocklistproject/Lists#56]
Hey!

Request first:
We need lists for "Spyware, AdWare, Popups, Popunders, Overlay".
Also, fix the filter names on some, to match the txt file name, because there are duplicates...

ISSUE:
There's an issue that keeps coming back, and I don't know how to stop it. It's genius design.....evil, but genius.
When watching online movies, you sometimes get in the top left corner of the video "2 new push messages", i.e.: some woman wants to do stuff.

Using the adblocker (uBlock Origin), it does not pick up the damn ads. Also, they are visible only in full screen, and hide in window. Logger does not help. And creating a custom filter for it based on "inspect page", does not work, because the page element doesn't have a name, it's just "div"...........
So you understand how frustrating this is.

There's this domain always showing up "inpagepush.com". I blocked it Globally, but the push things still show up... So maybe it's not it.

I will give you a link to a movie episode. If you guys can actually dissect it and come up with something, I'll frigging donate!!!
Well, you have some nice and well made filters, too! 👍👍

Here's the link:
https://vidcloud9.com/loadserver.php?id=MzI2MDc2&title=The+100+-+Season+7+Episode+11+-+Etherea&typesub=SUB&sub=L3RoZS0xMDAtc2Vhc29uLTctZXBpc29kZS0xMS1ldGhlcmVhL3RoZS0xMDAtc2Vhc29uLTctZXBpc29kZS0xMS1ldGhlcmVhLnZ0dA==&cover=Y292ZXIvdGhlLTEwMC1zZWFzb24tNy5wbmc=

Thank you!

**Comment by gap579137** [comment]
OK... I was able to get a block list create for that site. https://blocklistproject.github.io/Lists/CR-0001.txt 

Load that into you blocking device and see if it works.

**Comment by LucianAndries** [comment]
> OK... I was able to get a block list create for that site. https://blocklistproject.github.io/Lists/CR-0001.txt
> 
> Load that into you blocking device and see if it works.

LoL, those things are already blocked by default.
I need a custom Page Element block, not a list of domains..............

I need something like this that actually works(these are examples):
- vidcloud9.com##html > iframe:nth-child(7)
or
- vidcloud9.com##.vjs-overlay-background.hidden-xs-down.vjs-overlay-center.vjs-overlay

That's why I said to "dissect" the page and the ad... I thought you guys knew some java scripting or something. Coz I can't get the element's name or path. :(((((
Here, I attached some screenshots.

![Ad on Movie](https://user-images.githubusercontent.com/59364663/90435553-d8510400-e0d7-11ea-82cb-91dab8dfa5b3.png)
![Ad with Inspect tool 1](https://user-images.githubusercontent.com/59364663/90435588-e1da6c00-e0d7-11ea-9345-474ac4351da6.png)
![Ad with Inspect tool 2](https://user-images.githubusercontent.com/59364663/90435611-e7d04d00-e0d7-11ea-915a-5a94a85bd062.png)

**Comment by LucianAndries** [comment]
> OK... I was able to get a block list create for that site. https://blocklistproject.github.io/Lists/CR-0001.txt
> 
> Load that into you blocking device and see if it works.

LoL, those things are already blocked by default.
I need a custom Page Element block, not a list of domains..............

I need something like this that actually works(these are examples):
- vidcloud9.com##html > iframe:nth-child(7)
or
- vidcloud9.com##.vjs-overlay-background.hidden-xs-down.vjs-overlay-center.vjs-overlay

That's why I said to "dissect" the page and the ad... I thought you guys knew some java scripting or something. Coz I can't get the element's name or path. :(((((
Here, I attached some screenshots.

![Ad on Movie](https://user-images.githubusercontent.com/59364663/90436410-45b16480-e0d9-11ea-8649-72fa83926dde.png)
![Ad with Inspect tool 1](https://user-images.githubusercontent.com/59364663/90436414-49dd8200-e0d9-11ea-82b4-76e916f73a4d.png)
![Ad with Inspect tool 2](https://user-images.githubusercontent.com/59364663/90436418-4d710900-e0d9-11ea-915d-b68fc0dea4b3.png)

**Comment by gap579137** [comment]
This is going to be outside our purview at the moment. Currently, we are focusing on creation and maintenance of our lists.

**Comment by LucianAndries** [comment]
Oh, ok.

Then at least do the request? A lists for "Spyware, AdWare, Popups, Popunders, Overlay".
And also, fix the filter names on some of them, to match the .txt file name, because there are duplicates...

**Comment by LucianAndries** [comment]
Hey, it's me again... There are still mixed up lists, especially the Abuse and Malware lists. Both are named as "Malware List" inside, have the same number of filters inside 181664, in uBlock are reported with 456,027 filters, but inside both have 456,372... :O
They are broken. :(

Please fix, thank you.

PS: I'm trying the Porn filter list. Damn 2+ mil filters slows down uBlock....... And I have a fast system. :|
What I wanted to say is, with 2 mil filters it still misses some. Can't believe there are trillions of porn crap out there............. 😨😱💩
