### ISSUE TITLE
[Remove Request] - Outliers in Facebook list

### ISSUE THREAD

**Issue by wafles38** [blocklistproject/Lists#560]
I was looking through the facebook list to find every domain that Facebook owns, and I found four odd outliers that I think have no relation to Facebook. I come here find out why they were added to this list and how are they related to Facebook.

I would appreciate your insight.

URL you wish to be removed:
platform.foursquare.com
static.licdn.com  (Owned by Microsoft)

Why you believe this to be a false positive:
I have no idea if they are related to Facebook, and I can find any info from this project's page and issues on whether they are related or why they were added.

List it is on:
Facebook

Other info you think we should know:
It may be worth considering adding more foursquare urls into this list (That's just my paranoia talking, based solely on the fact that Facebook gave them millions, they are not working together officially I think)

I don't really care whether it's removed or not, I just want to find answers

**Comment by cryptogap** [comment]
Fixed and closed, thank you!

**Comment by wafles38** [comment]
wow, really? So they were legitimetely false positives? okay then, it caught me by surprise.

hootsuite and addtoany are also on the list, I believe this is because they integrate facebook services into their services (by this I mean, addtoany makes it easy to share a blog post to facebook, and hootsuite uses facebook for analytics). I believe those should be kept on the list but it's up to you guys
