### ISSUE TITLE
[Remove Request] - nppa.com.au

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#564]
URL you wish to be removed: nppa.com.au

Why you believe this to be a false positive: The New Payments Platform (nppa.com.au) is an industry-wide payments platform for Australia, national infrastructure for fast, flexible, data rich payments in Australia. The NPP is owned and operated by NPPA, a public company limited by shares. The RBA is a shareholder of NPPA along with 12 initial participating financial institutions.

List it is on: The Block List Project - Phishing

Other info you think we should know: N/A

**Comment by cryptogap** [comment]
Fixed and closed, thank you!
