### ISSUE TITLE
[Add request] - Gambling

### ISSUE THREAD

**Issue by Titomrock21** [blocklistproject/Lists#566]
URL you wish to be added:

`www.wildsultan.com`
`www.dublinbet1.com`
`www.jack-21.com`
`www.arlequincasino.com`
`www.luckyluke.com`
`www.cafecasino.lv`
`www.luckycreek.com`
`www.betbigdollar.com`
`euro.grandfortunecasino.com`
`www.p7campaign.com`
`www.slotocash.im`
`uptownaces.eu`
`www.vegascrestcasino.ag`
`www.mybcasino.ag`
`www.winamax.fr`
`www.parionssport.fdj.fr`
`www.netbet.fr`
`www.france-pari.fr`
`www.betclic.fr`
`www.zeturf.fr`
`www.playzax-top.com`
`www.casinointense-slots.com`
`www.jumbabet.com`
`www.drakecasino.eu`
`cherryjackpot.com`
`www.slotocash.im`
`roaring21.com`
`www.lincolncasino.eu`
`www.grandeaglecasino.com`
`diamondreels.com`
`libertyslots.eu`
`games.bet365.com`
`www.bitstarz.com`
`www.slotsmillion.com`
`www.mummysgold.com`
`www.box24games.com`
`www.riverbellecasino.com`
`www.spartansslots.net`
`www.luxurycasino.com`
`www.villento.com`
`www.captaincookscasino.eu`
`www.ukcasinoclub.eu`
`www.blackjackballroom.eu`
`www.blackdiamond4u.com`
`www.casino-classic.eu`
`www.7sultanscasino.com`
`www.slots.com`
`www.spinpalace.com`

Why you believe this should be added:

Add to list:

Gambling

Other info you think we should know:

**Comment by cryptogap** [comment]
These have been added, thank you
