### ISSUE TITLE
[Remove Request]　Malware List&ads list

### ISSUE THREAD

**Issue by Akulinas** [blocklistproject/Lists#567]
Domain you wish to be removed:
e-words.jp
nic.ad.jp

List it is on:
Malware List(e-words.jp)
Ads list(nic.ad.jp)

Other info you think we should know:
e-words.jp is a website that explains technical terms in IT.

nic.ad.jp is the domain of the Japan Network Information Center.
https://www.nic.ad.jp/en/profile/history/

**Comment by cryptogap** [comment]
Removed, thank you
