### ISSUE TITLE
False positive uguu.se/pomf.se

### ISSUE THREAD

**Issue by nokonoko** [blocklistproject/Lists#57]
URL you wish to be removed: a.uguu.se/a.pomf.se/pomf.se/uguu.se

Why you believe this to be a false positive: because I own both the sites and they are file sharing websites which are not malicious however people can upload malicious content that is removed as soon as it is reported.

List it is on: malware

Other info you think we should know: nope, feel free to contact me if more info is needed.

**Comment by gap579137** [comment]
This has been fixed
