### ISSUE TITLE
[Remove Request] - r3.o.lencr.org OCSP responder for Let's Encrypt

### ISSUE THREAD

**Issue by pepsimaxfan1** [blocklistproject/Lists#570]
URL you wish to be removed:  

r3.o.lencr.org

Why you believe this to be a false positive:  

This domain is owned by Let's Encrypt (https://letsencrypt.org/docs/lencr.org/) . When it's blocked, oscp queries fail and users encounter a lot of certificate issues when browsing the web.

List it is on: 

malware-nl

Other info you think we should know:

Another user requesting the same thing on another blocklist https://github.com/DandelionSprout/adfilt/issues/361

**Comment by thomasmerz** [comment]
Wow, this was fast… I've also seen this on one of my Pi-Holes with really less traffic - otherwise I would have overlooked it:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/18568381/143288660-d501cdf8-9525-4e1e-aa5d-7acc6e27a4c5.png">

**Comment by thomasmerz** [comment]
@blocklistproject , is there any progress to be reported? When will this be fixed, so someon can remove this domain from his/her/its whitelists again… 💭

**Comment by donald2612** [comment]
And again malware.txt, that is blocking legitimate and in this case security-important sites. Who is responsible for checking validity  and possible poisoning here? I'll opt out of this list as I type, as I think, it is more harm- than helpful.

**Comment by CYB3RL4MBD4** [comment]
> @blocklistproject , @FDrebin , is there any progress to be reported? When will this be fixed, so someon can remove this domain from his/her/its whitelists again… 💭 

Same question here...

**Comment by Deepcuts** [comment]
17 days and r3.o.lencr.org still in BL.
It is not like we are talking about a major certificate auth.
Safe to say these lists are not worth the trouble.

**Comment by CYB3RL4MBD4** [comment]
agree... as said in another post, if help is needed maintaining the lists, I may be able to help.

**Comment by spirillen** [comment]
> agree... as said in another post, if help is needed maintaining the lists, I may be able to help.

Don't waste your time on these lists, they are just bulk imported and then left. and stuff are added in bulks without any check or versification. 

I'm only here as a `blind hen also can fine a grain`. If you are bored there are plenty of space for more maintainer / contributors at mypdns.

**Comment by CYB3RL4MBD4** [comment]
Oh great... so I did well retire my Patreon contribution here...

**Comment by CYB3RL4MBD4** [comment]
> > agree... as said in another post, if help is needed maintaining the lists, I may be able to help.
> 
> 
> 
> Don't waste your time on these lists, they are just bulk imported and then left. and stuff are added in bulks without any check or versification. 
> 
> 
> 
> I'm only here as a `blind hen also can fine a grain`. If you are bored there are plenty of space for more maintainer / contributors at mypdns.

Oh great... so I did well retire my Patreon contribution here..

**Comment by spirillen** [comment]
> Oh great... so I did well retiring my Patreon contribution here..

To my opinion.

**Comment by thomasmerz** [comment]
Hey @blocklistproject , please merge my [PR](https://github.com/blocklistproject/Lists/pull/590) - thanks a lot 😘

**Comment by gyCfjSnO** [comment]
Any update on this?

**Comment by gianniferrai** [comment]
Still waiting for removal.........

**Comment by gyCfjSnO** [comment]
Hello any update on this it is still on the Malware List

**Comment by BrettDikeman** [comment]
@cryptogap you seem to be the only active maintainer as of late - are you able to fix this, please? This breaks LetsEncrypt.

**Comment by spirillen** [comment]
I would call this repository (project) for dead, leaving a issue like this for 21 days, that equal no a unmaintained project

**Comment by donald2612** [comment]
Would you consider all lists maintained here as unmaintained? Excuse my ignorance, but it is a problem to find "one-source"-supplier of any kind of block-lists. I use pi-hole for local blocking, and a commercial supplier in chain with TLS. I would happily pay for a good curated list of everything, before it hits the net....

**Comment by spirillen** [comment]
> Excuse my ignorance

Actually not,  a lot taken; as there are several project for which you are free to buy some coffee and who maintain there filters on a daily basis and not on a monthly basis.

> commercial supplier in chain with TLS.

Supplier of what? fish and chips? gummy beers?
