### ISSUE TITLE
[Remove Request] - invalid domains due to IDN instead of punycode

### ISSUE THREAD

**Issue by thomasmerz** [blocklistproject/Lists#571]
URL you wish to be removed:
There are some (7) IDN domains in the blocklist that should be or already are converted to punycode:
     - госулуги.рф
      - госуслуги-ру.рф
      - гослуги.рф
      - госсуслуга.рф
      - госсуслуугии.рф

Why you believe this to be a false positive:
Output from Pi-Hole preparing new gravity database:
```
  [i] Target: https://raw.githubusercontent.com/blocklistproject/Lists/master/phishing.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 190258 domains, 7 domains invalid!
      Sample of invalid domains:
      - госулуги.рф
      - госуслуги-ру.рф
      - гослуги.рф
      - госсуслуга.рф
      - госсуслуугии.рф
  [i] List has been updated
```

List it is on:
phishing

**Comment by spirillen** [comment]
wouldn't it be better to translate them into punycode?

```
xn--c1aapkosob.xn--p1ai
xn----etbaunrsdatce.xn--p1ai
xn--c1aapkosp.xn--p1ai
xn--80afa5aosaarc.xn--p1ai
xn--c1aapamrvaatca.xn--p1ai
```

**Comment by thomasmerz** [comment]
Yes, sure, I'm currently running a script on **all** lists (`*.txt`) that convert them from IDN to Punycode. But this takes a lot of time on my i5 linux desktop… 😱  For example:
```
IFS=$'\n'
for f in a*.txt b*.txt c*.txt; do
  rm -f $f.idn
  echo working on $f
  for line in $(cat $f); do
    echo "$line"|grep -q ^# && \
    echo $line >> $f.idn || \
    echo $line|idn2 -d >> $f.idn
  done
done
```
Later I will check by `sdiff -s` if something got lost…

**Comment by spirillen** [comment]
pip install pyfunceble
pyfunceble --syntax -f file1.txt file2.txt

- https://pypi.org/project/PyFunceble/
- https://github.com/funilrys/PyFunceble the tool you are looking for you can append `--hierarchical` to sort the output with relation to each other (pr domain)

**Comment by spirillen** [comment]
PS: Questions to related to the docs (only) should be posted here: https://mypdns.org/spirillen/PyFunceble/-/issues

**Comment by thomasmerz** [comment]
Well, I feel more comfortable with `bash` than `python` 😉  
And my script is running in the background and when it's done, it's done 🤣

**Comment by spirillen** [comment]
I prefer bash as well but that doesn't change the facay @funilrys have made @PyFunceble in python and it is working and even convertin to ponycode by it self :open_mouth: You coul have found and removed all inactive domains at the same time as well :)

I would have used `while read line` instead for `for lines in` it is faster an uses less resources as you are only working though the file once vs one time for each line in `$f`

**Comment by thomasmerz** [comment]
> I would have used `while read line` instead for `for lines in` it is faster an uses less resources as you are only working though the file once vs one time for each line in `$f`

That's damn true! 😵‍💫 I'll keep this in mind for the next time (because it's nearly finished) 🤣

**Comment by thomasmerz** [comment]
Well this quickshot doesn't work well (and fast) enough 😞   
So could any maintainer please review my https://github.com/blocklistproject/Lists/pull/574 ? Thanks!

**Comment by spirillen** [comment]
> > I would have used `while read line` instead for `for lines in` it is faster an uses less resources as you are only working though the file once vs one time for each line in `$f`
> 
> That's damn true! face_with_spiral_eyes I'll keep this in mind for the next time (because it's nearly finished) rofl

PS: This is not limited by the cpu but disk I/O, meaning you will have a HUGE gain by using ramFS or tmpFS dirs to benefit from the RAM I/O speed over the very limited SSD (Spindel) I/O limitation compared to NVMe or ramFS.

> of time on my i5 linux desktop

**Comment by funilrys** [comment]
Hi there, there is [domain2idna](https://pypi.org/project/domain2idna/).
It's not perfect (yet?) but it's the underlying Python module that PyFunceble uses for the conversion.

If you are fluent with Python, here is the way with PyFunceble:

```python
from domain2idna import domain2idna

with open('awesome_file', 'r', encoding="utf-8") as input_file_stream, open('awesome_output_file', 'w', encoding="utf-8") as output_file_stream:
    for line in input_file_stream:
        output_file_stream.write(domain2idna(line.strip()) + "\n")

```

 **Disclaimer**: I'm the author of it 😄

**Comment by thomasmerz** [comment]
@blocklistproject , @FDrebin , is there any progress to be reported? When will this be fixed? ⏳

**Comment by iam-py-test** [comment]
test

**Comment by iam-py-test** [comment]
By the way, I don't think @FDrebin is affiliated with this project

**Comment by thomasmerz** [comment]
@cryptogap , can you please review and merge linked PR #574 if ok? Thanks a lot!

**Comment by fishcharlie** [comment]
@thomasmerz This issue is already closed. So I don't understand what you mean.

**Comment by thomasmerz** [comment]
Ups, I left this issue open in my browser for a while and didn't reload and therefore didn't notice - sorry for the inconvenience 🤷🏻‍♂️

**Comment by fishcharlie** [comment]
No problem! @thomasmerz
