### ISSUE TITLE
[Remove Request] - www.xvideos-español.com due to IDN instead of punycode

### ISSUE THREAD

**Issue by thomasmerz** [blocklistproject/Lists#572]
URL you wish to be removed:
There is one IDN domains in the blocklist that should be or already is converted to punycode:
      - www.xvideos-español.com

Why you believe this to be a false positive:
Output from Pi-Hole preparing new gravity database:
```
  [i] Target: https://raw.githubusercontent.com/blocklistproject/Lists/master/porn.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 1907959 domains, 1 domains invalid!
      Sample of invalid domains:
      - www.xvideos-español.com
  [i] List has been updated
```

List it is on:
porn

**Comment by spirillen** [comment]
ponycided
```
xn--xvideos-espaol-1nb.com
www.xn--xvideos-espaol-1nb.com
```

**Comment by thomasmerz** [comment]
@blocklistproject , @FDrebin , is there any progress to be reported? When will this be fixed? ⏳

**Comment by thomasmerz** [comment]
@cryptogap , can you please review and merge linked PR #573 if ok? Thanks a lot!
