### ISSUE TITLE
[Remove Request] - Malware List (NL)

### ISSUE THREAD

**Issue by Akulinas** [blocklistproject/Lists#575]
URL you wish to be removed:
b.hatena.ne.jp

Why you believe this to be a false positive:

List it is on:
Malware List (NL)

Other info you think we should know:
This is the domain of a Japanese blog service.

**Comment by cryptogap** [comment]
Please provide a malware scan screenshot

**Comment by Akulinas** [comment]
@cryptogap
[https://sitecheck.sucuri.net/results/b.hatena.ne.jp](url)
![screenshot,2022/01/02](https://user-images.githubusercontent.com/55057707/147876990-f5493671-58f3-4468-b8d8-f0cfbc5560e6.jpg)

**Comment by cryptogap** [comment]
This has been removed
