### ISSUE TITLE
www.refinery29.com

### ISSUE THREAD

**Issue by mkb2091** [blocklistproject/Lists#58]
URL you wish to be removed: www.refinery29.com

Why you believe this to be a false positive: It's a website with articles such as https://www.refinery29.com/en-gb/2020/08/9929778/notifications-causing-anxiety?utm_source=pocket-newtab-global-en-GB which aren't adverts, but do contain adverts

List it is on: ads.txt

Other info you think we should know:

**Comment by gap579137** [comment]
This has been fixed
