### ISSUE TITLE
[Remove Request] - stripe.network

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#580]
URL you wish to be removed: `stripe.network`

Why you believe this to be a false positive: Used for Stripe’s fraud detection - https://stripe.com/au/privacy-center/legal#stripejs

List it is on: Block List Project: Ads

Other info you think we should know: N/A

**Comment by cryptogap** [comment]
This will be added to malicious. As it is currently setup to auto download a file to users computer.

**Comment by eur0pa** [comment]
```
m.stripe.network
checkout.stripe.com
js.stripe.com
```

These need to be removed from Adobe.txt, as they break check out and payments on websites that use Stripe as a payment provider.
