### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by sojudu** [blocklistproject/Lists#582]
URL you wish to be added: https://github.com/blocklistproject/Lists

Why you believe this should be added: kindly add all the lists from there, currently rethink dns dosn't do good job of blocking porn , but in that list, you are able to block 2.1 million porn sites, kindly add there other lists as well

Add to list: 
https://blocklistproject.github.io/Lists/ads.txt
https://blocklistproject.github.io/Lists/fraud.txt
https://blocklistproject.github.io/Lists/malware.txt
https://blocklistproject.github.io/Lists/phishing.txt
https://blocklistproject.github.io/Lists/porn.txt
https://blocklistproject.github.io/Lists/ransomware.txt
https://blocklistproject.github.io/Lists/tracking.txt

Other info you think we should know:
Thank you so much

**Comment by spirillen** [comment]
That is not 2.1 mill porn urls, it's just 2.1 mill lines of domain names to appear as a big list while the fact is in the first ~100 lines I can, without testing, say there are a high number of FP.

just try and do a search on there `*.blogspot.*` and it is based on the same records as `porn.host.srv` by spamhaus (test results: https://github.com/dns-test/porn.host.rpz)
