### ISSUE TITLE
[Remove Request] - autistici.org in abuse malware list 

### ISSUE THREAD

**Issue by maninthemiddle01** [blocklistproject/Lists#583]
URL you wish to be removed:
autistici.org

Why you believe this to be a false positive:
This grassroot "provides services and tools [e.g. mail] to achieve anonymous and secure communication".

List it is on:
abuse malware

Other info you think we should know:
If this is blocked, people cannot access their mails

**Comment by cryptogap** [comment]
This has been removed, Thank you
