### ISSUE TITLE
[Remove Request] blog.xuite.net

### ISSUE THREAD

**Issue by yummypixza** [blocklistproject/Lists#584]
URL you wish to be removed:
blog.xuite.net 
www.blog.xuite.net 
xuite.net

Why you believe this to be a false positive:
xuite.net (隨意窩) is a Taiwanese BSP (blog service provider) backed by Taiwanese ISP Hinet (Chunghwa Telecom Co. Ltd.)

List it is on:
malware list.
```
Match found in https://blocklistproject.github.io/Lists/malware.txt:
  blog.xuite.net 
  www.blog.xuite.net 
```

Other info you think we should know:
I believe this may caused by what I saw on dnschecker.org which says the domain were got blocked in dnsbl.spfbl.net
https://dnschecker.org/all-dns-records-of-domain.php?query=blog.xuite.net&rtype=ALL&dns=google

As far as I know, xuite.net and hinet.net, as ISP mailboxes had a history of serving as spam mail delivery proxy many years ago, but it shouldn't be the cause to include them in browser block list.

I can provide help and willing to do if you need further info and validation on this.

**Comment by cryptogap** [comment]
These have been removed, Thank you
