### ISSUE TITLE
[Remove Request] - pp.ua

### ISSUE THREAD

**Issue by krittykitty** [blocklistproject/Lists#587]
URL you wish to be removed:

*.pp.ua
www.*.pp.ua

Why you believe this to be a false positive:

The whole second level domain has been blocked this way.  That is a little too restrictive. 

List it is on:

https://blocklistproject.github.io/Lists/abuse.txt

Other info you think we should know:

**Comment by spirillen** [comment]
> The whole second level domain 

don't you mean third level domain??

First level = UA
Second level = PP
Third level = `*` (usually wildcard)
Fourth Level = WWW

**Comment by krittykitty** [comment]
Well, all Domains ending with  .pp.ua are blocked and that includes also pp.ua, which is a second level domain.

So to be correct:  pp.ua is blocked and all *.pp.ua domains registered at nic.ua are blocked.

If I had written it misleading: pp.ua is like co.uk with its own registry, not a normal domain.
https://nic.ua/en/domains/.pp.ua

**Comment by spirillen** [comment]
That's clarifies a lot I most admit I wasn't aware of the `pp.ua` or at least forgotten it :shrug: as it haven't crossed [my filters](https://mypdns.org/search?search=pp.ua&nav_source=navbar) yet.

But since the rule `0.0.0.0 pp.ua` can blacklist all domains below, which software are you loading the list into?

Or did you only tried these urls?

```
0.0.0.0 alternativa.pp.ua
0.0.0.0 blackhill.pp.ua
0.0.0.0 avrlife.pp.ua
0.0.0.0 comlive.pp.ua
0.0.0.0 ebaybase.pp.ua
0.0.0.0 flashgorod.pp.ua
0.0.0.0 kronus.pp.ua
0.0.0.0 projka.pp.ua
0.0.0.0 www.avrlife.pp.ua
0.0.0.0 www.ebaybase.pp.ua
0.0.0.0 www.flashgorod.pp.ua
0.0.0.0 www.kronus.pp.ua
0.0.0.0 www.pp.ua
0.0.0.0 www.projka.pp.ua
0.0.0.0 www.xxxart.pp.ua
0.0.0.0 xxxart.pp.ua
0.0.0.0 a-p-k.pp.ua
0.0.0.0 www.a-p-k.pp.ua
0.0.0.0 home.thomas.pp.ua
```

Extraction code:
```bash
wget -qO- https://blocklistproject.github.io/Lists/abuse.txt | grep -E '\.pp.ua$'
```

**Comment by krittykitty** [comment]
Good morning!
I have set dnsforge.com as my DNS server 
on my devices and Have noticed confused that my little board game page is blocked.

So I have written the admin, had my site whitelisted, but asked from which list the blocking was, response:

https://blocklistproject.github.io/Lists/abuse.txt:
0.0.0.0 alternativa.pp.ua
0.0.0.0 blackhill.pp.ua
0.0.0.0 avrlife.pp.ua
0.0.0.0 comlive.pp.ua
0.0.0.0 ebaybase.pp.ua
0.0.0.0 flashgorod.pp.ua
0.0.0.0 kronus.pp.ua
0.0.0.0 pp.ua
0.0.0.0 projka.pp.ua
0.0.0.0 www.avrlife.pp.ua
0.0.0.0 www.ebaybase.pp.ua
0.0.0.0 www.flashgorod.pp.ua
0.0.0.0 www.kronus.pp.ua
0.0.0.0 www.pp.ua
0.0.0.0 www.projka.pp.ua
0.0.0.0 www.xxxart.pp.ua
0.0.0.0 xxxart.pp.ua
0.0.0.0 a-p-k.pp.ua
0.0.0.0 www.a-p-k.pp.ua
0.0.0.0 home.thomas.pp.ua

Looked it up myself, as you have,
and this line seems to be the problem:
0.0.0.0 pp.ua

As it not only blocks pp.ua, which is also wrong, as it is not an abuse site, but an official site from nic.ua. But also all domains registered there.

**Comment by iam-py-test** [comment]
> So please remove the entry:

@spirillen can't remove it, they don't have access.
I can confirm it is blocked and shouldn't be blocked

**Comment by spirillen** [comment]
@iam-py-test Good call, as I found it in my DB from a very very early import from external sources.... should never had done that, it keeps cursing FP's.

The main question is, what about those I do not have on previously my list, which should be added, and which are simply yet other FP's.

The list got this [issue](https://mypdns.org/my-privacy-dns/matrix/-/issues/3802), please share your knowledge to it


> @spirillen can't remove it, they don't have access.
> I can confirm it is blocked and shouldn't be blocked

You get me confused here, not sure why you addresses me about removal on this project?

Who is `they`?

**Comment by iam-py-test** [comment]
> @iam-py-test Good call, as I found it in my DB from a very very early import from external sources.... should never had done that, it keeps cursing FP's.
> 
> The main question is, what about those I do not have on previously my list, which should be added, and which are simply yet other FP's.
> 
> The list got this [issue](https://mypdns.org/my-privacy-dns/matrix/-/issues/3802), please share your knowledge to it
> 
> > @spirillen can't remove it, they don't have access.
> > I can confirm it is blocked and shouldn't be blocked
> 
> You get me confused here, not sure why you addresses me about removal on this project?

I was addressing the OP, as the OP seemed to be addressing you. 
> Who is `they`?

'They' meaning you, I didn't want to say 'he' or 'she' because I wasn't sure which one was appropriate.

**Comment by spirillen** [comment]
> I was addressing the OP, as the OP seemed to be addressing you.

Yes I was trying to understand the full picture of this issue, as it turns out, that was a good idea as I actually had some FP as you can see in issue :arrow_up: 

That why we had a talk inside this issue.

> They' meaning you, I didn't want to say 'he' or 'she' because I wasn't sure which one was appropriate.

AAAhhhhh now I get the line....  I was reading they as third person (not my self) as I was already mentioned.

Spillen is a male mammon the female if weirdly enough named spirillA :wink:

**Comment by cryptogap** [comment]
This has been removed, Thank you all
