### ISSUE TITLE
[Remove Request] - widget-mediator.zopim.com

### ISSUE THREAD

**Issue by CYB3RL4MBD4** [blocklistproject/Lists#589]
URL you wish to be removed:
widget-mediator.zopim.com

Why you believe this to be a false positive:
It blocks loading of zendesk chat widget.

List it is on:
ads.txt

Other info you think we should know:
was also on the StevenBlack list and then removed after check.
https://github.com/StevenBlack/hosts/issues/1625

**Comment by cryptogap** [comment]
This has been removed, Thank you
