### ISSUE TITLE
[Remove Request] - geo2.adobe.com

### ISSUE THREAD

**Issue by jamesplease** [blocklistproject/Lists#592]
### URL you wish to be removed:

`geo2.adobe.com`

### Why you believe this to be a false positive:

This prevents the main Adobe website, www.adobe.com, from functioning properly. More specifically, the header at the top of the page that allows you to access things such as account settings will not display when this is on. The header not loading makes it so that users cannot sign in to their Adobe account from the website. The only way to manage subscriptions/payments/billing for Adobe services is through their website.

Note: to test this you will want to clear all browser cache (including local application data such as LocalStorage), as it appears that a successful request to this domain is cached locally in the browser.

To test:

1. Enable this list as usual
2. Go to `adobe.com` and observe that the header does not render
3. Disable Pi Hole and refresh the page. Observe that the header renders
4. Re-enable pi hole. The header should continue to render, as the browser has cached the response from this domain locally.
5. Either clear the entire cache for this browser/domain or use a new browser to observe that the header does not display when Pi Hole is enabled
6. With Pi Hole enabled, add `geo2.adobe.com` to the whitelist.
7. Observe that the header always displays, even when the cache is cleared or new browsers are used

### List it is on:

ads.txt

### Other info you think we should know:

N/A

**Comment by spirillen** [comment]
That domain is used for tracking your current location and bind to you adobe profile

**Comment by jamesplease** [comment]
If it breaks normal functionality of the Adobe website is it still something that should be kept on the list? My personal opinion is that items on the list should protect privacy as much as possible without breaking the regular functionality of the service.

**Comment by spirillen** [comment]
@jamesplease that is a fair opinion and it suit you and wont debate that one, but here is my view on the topic :wink: https://mypdns.org/my-privacy-dns/matrix#faq

According to my view, I added the information for the domain, it wasn't an argument for removal or not as this isn't my list.

**Comment by jamesplease** [comment]
Thanks for sharing that perspective, @spirillen . I can definitely see both sides on this issue. I’m curious what the maintainers of this list feel is best? I’m fine with either decision.

**Comment by spirillen** [comment]
@jamesplease Come to think of: How would you feel adding your original comments about this sub domain to https://mypdns.org/my-privacy-dns/matrix/-/issues/3059, that is for sure a thing that would be welcomed as shared knowledge

**Comment by iam-py-test** [comment]
If using a browser based blocker, it might be possible to block the specific urls used for tracking without breaking anything.
In my opinion, this domain should be unblocked.

**Comment by jamesplease** [comment]
> @jamesplease Come to think of: How would you feel adding your original comments about this sub domain to https://mypdns.org/my-privacy-dns/matrix/-/issues/3059, that is for sure a thing that would be welcomed as shared knowledge

Normally I would, but I took a quick look and couldn’t figure it out. Sorry!

**Comment by spirillen** [comment]
> > @jamesplease Come to think of: How would you feel adding your original comments about this sub domain to https://mypdns.org/my-privacy-dns/matrix/-/issues/3059, that is for sure a thing that would be welcomed as shared knowledge
> 
> Normally I would, but I took a quick look and couldn’t figure it out. Sorry!

When you have signed in you just go to the bottom of the tread and at your reply

**Comment by cryptogap** [comment]
This was removed from ads and placed on tracking, Thank you
