### ISSUE TITLE
[Remove Request] - api.bazaarvoice.com

### ISSUE THREAD

**Issue by Iconology** [blocklistproject/Lists#594]
URL you wish to be removed:
api.bazaarvoice.com
photos-us.bazaarvoice.com

Why you believe this to be a false positive:
It's needed for the ability to view reviews on multiple sites.
It could be blocked for a good reason, but it's only found on lists in this repo and blocks a somewhat important functionality of websites.

List it is on:
Match found in https://blocklistproject.github.io/Lists/ads.txt:
   api.bazaarvoice.com

Other info you think we should know:
Example site would be go to petco.com, click on any product, and go to the reviews tab.
Photos in reviews is also blocked, photos-us.bazaarvoice.com

**Comment by spirillen** [comment]
https://mypdns.org/my-privacy-dns/matrix/-/issues/2301

**Comment by cryptogap** [comment]
These two have been removed but other remain.
