### ISSUE TITLE
[Remove Request] - pilahorti.com

### ISSUE THREAD

**Issue by janmg** [blocklistproject/Lists#596]
URL you wish to be removed:
pilahorti.com
www.pilahorti.com

Why you believe this to be a false positive:
PILA Horti is a brand from Signify, the website is used for sales of lights used for farming, there is no indication of malware ever reported for these hostnames.

List it is on:
malware, alt, adguard

Other info you think we should know:
Commit 2834d0fc33962d047c443bac7f2f543f55c6090b added these hostnames seem to have been a mass import from threatcrowd.org without any sign of malware served by the domain. As this is website is served through Akamai, one of the IP addresses may have been used by other Akamai customers for malware.

**Comment by blocklistproject** [comment]
This has been fixed and will be included in the next push
