### ISSUE TITLE
[Remove Request] - forum.ragezone.com

### ISSUE THREAD

**Issue by exmex** [blocklistproject/Lists#598]
URL you wish to be removed:
forum.ragezone.com

Why you believe this to be a false positive:
I'm a moderator on that forum. There are download links to applications and games, we always look if somebody posted malware. So this is not a site who distributes malware. Proof we actually disallow malwares:
https://forum.ragezone.com/f788/section-rules-please-read-1019115/

> 10. No Warez / viruses / hacks / cracks / malicious code allowed.
> 23. Because of recent events every release that contains binaries need to have a virustotal and jotti scan! If you don't have one, your thread gets deleted and, you will receive an infraction! (Binaries such as: EXE, BAT, CMD, REG, DLL, LIB), because bigger *.rar files cannot be scanned every thread must have a SHA256 hash of the file

List it is on:
malware

Other info you think we should know:

**Comment by iam-py-test** [comment]
>  (Binaries such as: EXE, BAT, CMD, REG, DLL, LIB)

What about ELF and APK files? Python, JavaScript, HTML, VBS? We aren't all on WindowsOS and Linux, MacOS, and Android have tons of threats as well:
![image](https://user-images.githubusercontent.com/84232764/147416088-54889d36-eb97-4fb3-9a1e-856d7c7e5c74.png)

I'd also recommend you implement some checking, as I was able to sign up with the password 'password' and a fake email - and nothing stopped me.  I was able to post a spam post
> we always look if somebody posted malware

Adding some automatic server-side checking for malware might help. You can use https://bazaar.abuse.ch/export/ or https://urlhaus.abuse.ch/ as that's free

**Comment by iam-py-test** [comment]
I can not investigate further as someone banned my test account:
![image](https://user-images.githubusercontent.com/84232764/147416996-3077972f-8a02-4d58-882e-0bf07bfcf7e7.png)
Username: sectest

**Comment by blocklistproject** [comment]
At this time due to the nature of the site and personally finding malware on the site, this site will remain on the block list. Please resubmit when you are better able to ensure there is no malware or illegally pirated software. Thank you
