### ISSUE TITLE
[Remove Request] - mystats.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [blocklistproject/Lists#601]
URL you wish to be removed: `https://www.mystats.com`

Why you believe this to be a false positive: I can’t see any malware

List it is on: `https://raw.githubusercontent.com/blocklistproject/Lists/master/malware.txt`

Other info you think we should know: https://github.com/uBlockOrigin/uAssets/issues/11139

**Comment by cryptogap** [comment]
This has been removed
