### ISSUE TITLE
Header Dates on Lists

### ISSUE THREAD

**Issue by RicoHeat** [blocklistproject/Lists#610]
@blocklistproject
Please update the dates on the lists because if one is to open from a website like filterlists.com then users may think that the lists aren't being updated.. For example https://raw.githubusercontent.com/blocklistproject/Lists/master/alt-version/basic-nl.txt was updated 15 days ago but the list says June 2020. Thank you for your work and have a great day! 👍

**Comment by fishcharlie** [comment]
This is something I can work on taking care of when I get some time. Assigning to myself.

**Comment by fishcharlie** [comment]
It looks like most lists have removed the dates. So when I get time to work on this I'll add a step to the lint job to ensure that no dates exist in the headers, and remove them from the `basic` list (and others if necessary).

**Comment by thomasmerz** [comment]
- [x] Removed dates from `basic` and `crypto` lists: PR #647 
- [ ] add a step to the lint job

**Comment by thomasmerz** [comment]
@fishcharlie and @cryptogap - WHO will close any issue if it's solved by a merged PR? The creator of the issue or the merger? 🤷🏻‍♂️ This would really help to keep track of what-to-do and what-is-done. 😗

**Comment by fishcharlie** [comment]
@thomasmerz I don't have permissions to close issues (yet). Will ensure this gets done soon tho.

**Comment by thomasmerz** [comment]
Well, anyone with merge-permissions should also be able to close issues as well. I upvote this 😄

**Comment by thomasmerz** [comment]
Or a [GH action](https://github.com/marketplace/actions/closes-issues-related-to-a-merged-pull-request) could do this automatically!? Do you want a PR for this? 😜

**Comment by fishcharlie** [comment]
I forgot they moved the close button on the mobile app
