### ISSUE TITLE
[Add request] domains to tiktok

### ISSUE THREAD

**Issue by smcclosr** [blocklistproject/Lists#612]
URL you wish to be added:

api16-core-useast5.us.tiktokv.com
api16-normal-useast5.us.tiktokv.com
api19-core-useast5.us.tiktokv.com
api19-normal-useast5.us.tiktokv.com
dig.us.tiktokv.com
frontier.us.tiktokv.com
hotapi16-platform-useast5.us.tiktokv.com
im16-platform-useast5.us.tiktokv.com
image.us.tiktokv.com
jsb16-normal-c-useast1a.tiktokv.com
lf16-effectcdn-va.tiktokcdn.com
lf19-effectcdn-va.tiktokcdn.com
lf21-effectcdn-va.tiktokcdn.com
libra16-platform-useast5.us.tiktokv.com
log16-applog-useast5.us.tiktokv.com
log16-applog-useast5.us.tiktokv.com.localdomain
mon-sg.tiktokv.com
mon16-platform-useast5.us.tiktokv.com
mssdk16-platform-useast5.us.tiktokv.com
p16-sign.tiktokcdn-us.com
p16.tiktokcdn-us.com
p19-sign.tiktokcdn-us.com
p19.tiktokcdn-us.com
pull-c5-va01.tiktokcdn.com
pull-cmaf-f16-gcp01.tiktokcdn.com
pull-cmaf-f16-tt01.fcdn.us.tiktokv.com
pull-cmaf-f16-tt01.tiktokcdn.com
pull-cmaf-f16-va01.tiktokcdn.com
pull-cmaf-f16.tiktokcdn.com.localdomain
pull-cmaf-f77-va01.tiktokcdn.com
pull-cmaf-f77-va01.tiktokcdn.com.localdomain
pull-cmaf-l16-va01.tiktokcdn.com
pull-cmaf-l77-va01.tiktokcdn.com
pull-f5-gcp01.tiktokcdn.com
pull-f5-tt01.fcdn.us.tiktokv.com
pull-f5-va01.tiktokcdn.com
pull-flv-l16-va01.tiktokcdn.com
pull-hls-f16-tt01.fcdn.us.tiktokv.com
pull-hls-f16-tt01.tiktokcdn.com
pull-hls-f77-va01.tiktokcdn.com
pull-hls-l16-va01.tiktokcdn.com
pull-hls-l77-va01.tiktokcdn.com
pull-hls-q16-gcp01.tiktokcdn.com
pull-hls-q16-va01.tiktokcdn.com
pull-hls-w16-va01.tiktokcdn.com
pull-hls-w16-va01.tiktokcdn.com.localdomain
pull-hls-w5-va01.tiktokcdn.com
pull-q5-va01.tiktokcdn.com
pull-rtmp-l16-va01.tiktokcdn.com
pull-w5-va01.tiktokcdn.com
push-rtmp-f5-gcp01.tiktokcdn.com
push-rtmp-f5-va01.tiktokcdn.com
push-rtmp-l16-va01.tiktokcdn.com
push-rtmp-l77-va01.tiktokcdn.com
sf16-ies-music-sg.tiktokcdn.com
sf16-ies-music-va.tiktokcdn.com
sf16.tiktokcdn-us.com
sf19.tiktokcdn-us.com
tnc16-platform-alisg.tiktokv.com
tnc16-platform-useast1a.tiktokv.com
tnc16-platform-useast5.us.tiktokv.com
v16m.tiktokcdn-us.com
v19.tiktokcdn-us.com
v25.tiktokcdn-us.com
v39.tiktokcdn-us.com
vcs16-platform-useast5.us.tiktokv.com
video-useast5.tiktokv.com
webcast16-normal-useast5.us.tiktokv.com
webcast19-normal-useast5.us.tiktokv.com

Why you believe this should be added:

These are tiktok domains

Add to list:

https://blocklistproject.github.io/Lists/alt-version/tiktok-nl.txt

Other info you think we should know:

**Comment by thomasmerz** [comment]
I've made PR #648 for this. Please review and merge.
