### ISSUE TITLE
Blocklisted Reason please[Add request]

### ISSUE THREAD

**Issue by vijov47** [blocklistproject/Lists#614]
URL you wish to be added:https://intercityindustrial.com/

Why you believe this should be added: The above URL listed for malware and the Wi-Fi is blocking .Need to know the reason please

Add to list:

Other info you think we should know:
We need to remove our URL from the malware list ASAP
Please help to figure it out

**Comment by cryptogap** [comment]
I looks like your site at some point has malicious code. I have scanned it and removed it from our lists

**Comment by vijov47** [comment]
Thank you so much.
Any chance to know how the code may came?
What kind of code it was?
Which tool used to scan and remove it?
The website was done by a company Shout-media.

Thanks again for your time invested for this.
