### ISSUE TITLE
[Remove Request] - asknet.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [blocklistproject/Lists#616]
URL you wish to be removed: `asknet.de`

Why you believe this to be a false positive: I see no malware on this domain it just redirect to `https://asknet-solutions.com/de/`

List it is on: 
https://blocklistproject.github.io/Lists/malware.txt 
https://blocklistproject.github.io/Lists/abuse.txt

**Comment by thomasmerz** [comment]
I made PR #649 for this issue. Please review and merge.
