### ISSUE TITLE
[Remove Request] - ow-api.com

### ISSUE THREAD

**Issue by PikaDude** [blocklistproject/Lists#618]
URL you wish to be removed:
ow-api.com
www.ow-api.com

Why you believe this to be a false positive:
It's just an unofficial JSON API for Overwatch stats.

List it is on:
malware and abuse (maybe more?)

Other info you think we should know:
Malwarebytes had it as a false positive at some point https://forums.malwarebytes.com/topic/265688-ow-apicom/

**Comment by cryptogap** [comment]
These have been removed
