### ISSUE TITLE
Removal of Blacklisted Domain

### ISSUE THREAD

**Issue by sampatrick123** [blocklistproject/Lists#62]
URL you wish to be removed: 
123greetings.com
oascentral.123greetings.com
www.123greetings.com
www.www123greetings.com
www123greetings.com

Why you believe this to be a false positive: This domain does not host any malware

List it is on: https://blocklistproject.github.io/Lists/malware.txt

Other info you think we should know:

**Comment by gap579137** [comment]
This has been reviewed. 123greetings.com, www.123greetings.com & oascentral.123greetings.com were removed. the other 2 we were not able to verify and were left on the list. Thank you
