### ISSUE TITLE
[Remove Request] - www.docmorris.de + docmorris.de

### ISSUE THREAD

**Issue by thomasmerz** [blocklistproject/Lists#620]
# URL you wish to be removed:
www.docmorris.de
docmorris.de

# Why you believe this to be a false positive:
See https://nl.wikipedia.org/wiki/DocMorris
> DocMorris is a Dutch mail-order pharmacy that delivers medicines mainly to customers in Germany after receiving an order by phone, mail or via the Internet. The company was founded in 2000 by Dutch pharmacist Jacques Waterval and German Ralf Däinghaus and has been part of the Swiss Zur Rose Group since 2012.

(translated from german to english by www.deepl.com)

# List it is on:
https://raw.githubusercontent.com/blocklistproject/Lists/master/drugs.txt

# Other info you think we should know:
Have a look at their (german) blog to get an impression that they are not selling DRUGS, but medicine in Germany: https://www.docmorris-blog.de/

**Comment by thomasmerz** [comment]
Please review and merge my PR: https://github.com/blocklistproject/Lists/pull/621

**Comment by cryptogap** [comment]
These have been removed
