### ISSUE TITLE
[Remove Request] - scriptjunkie.us

### ISSUE THREAD

**Issue by scriptjunkie** [blocklistproject/Lists#624]
URL you wish to be removed: scriptjunkie.us

Why you believe this to be a false positive: It doesn't launch any attacks or other malicious behavior, and it's my site.

List it is on: malware

Other info you think we should know: I don't see any reason why it was added so I'm not sure what to say. It's just not bad. I have explained cyber security topics and hacking techniques on the site, so maybe there was confusion there, but I don't do anything malicious with it.

**Comment by thomasmerz** [comment]
I made PR #652 for this issue. Please review and merge.

**Comment by blocklistproject** [comment]
This has been fixed
