### ISSUE TITLE
[Remove Request] - 2 domains invalid on phishing list

### ISSUE THREAD

**Issue by usr-dot-com** [blocklistproject/Lists#628]
URL you wish to be removed:  
- госуспуги.рф
- госуслуги-госномера.рф

Why you believe this to be a false positive:  Updating gravity on Pi-hole returns `2 domains invalid!`

List it is on: phishing.txt

Other info you think we should know:

**Comment by spirillen** [comment]
Shall e IDNA converted according to RFC:952


```
госуспуги.рф = xn--c1aapwflapc.xn--p1ai
госуслуги-госномера.рф = xn----8sbhabmswnjffb4aeag2ac.xn--p1ai
```

**Comment by cryptogap** [comment]
These have been removed and converted versions added

**Comment by thomasmerz** [comment]
@cryptogap , I wonder why my Pi-hole with this current phishing-list still contains the first one (госуспуги.рф)!?

<img width="613" alt="grafik" src="https://user-images.githubusercontent.com/18568381/156259372-7db1729f-abc7-4b48-9134-ad5c0b086cfd.png">

```
pihole_updateGravity.log:  [i] Analyzed 190245 domains, 1 domains invalid!
pihole_updateGravity.log:      Sample of invalid domains:
pihole_updateGravity.log-      - госуспуги.рф
```

```
$ grep госуспуги.рф phishing.txt -n
42818:0.0.0.0 госуспуги.рф
```

I open this PR #683 - please review and merge. Thanks!
