### ISSUE TITLE
[Remove Request] - ask.metafilter.com

### ISSUE THREAD

**Issue by majick** [blocklistproject/Lists#629]
URL you wish to be removed:
ask.metafilter.com

Why you believe this to be a false positive:
This is not only a reputable site, it's one of the original reputable sites.  It absolutely should not appear on a list of "sites designed to deceive," as abuse.txt is described.

List it is on:
https://raw.githubusercontent.com/blocklistproject/Lists/master/abuse.txt

Other info you think we should know:
I've seen this site pop false positive on other lists before, but was never able to find the error upstream.

**Comment by cryptogap** [comment]
This has been removed in our next push
