### ISSUE TITLE
[Add request] Redirect / Tracking

### ISSUE THREAD

**Issue by techroy23** [blocklistproject/Lists#631]
URL you wish to be added:

extoso.com
tjcttxdfelb.com
cdexvangxfarwl.com
aaotpokaquathii.com
worldcoolfeed.com
srghsmpyvvko.com
hidelen.com

Why you believe this should be added:

links utilized for redirects.

Add to list:

[redirect.txt](https://github.com/blocklistproject/Lists/blob/master/redirect.txt)

Other info you think we should know:

**Comment by cryptogap** [comment]
This has been added and will be included in the next push
