### ISSUE TITLE
[Add request] Ads List

### ISSUE THREAD

**Issue by Akulinas** [blocklistproject/Lists#632]
URL you wish to be added:
a.line.me
sch.line.me
crs-event.line.me
lap-click.tr.line.me
ga2.line.naver.jp
ga2x.line.naver.jp
gs2.line.naver.jp
gs2x.line.naver.jp
gw.line.naver.jp
ns1.line.naver.jp
ns2.line.naver.jp
adns1.line.naver.com
adns2.line.naver.com
nelo2-col.linecorp.com
d.line-scdn.net
obs.line-scdn.net
appresource.line-scdn.net
vos.line-scdn.net
static.line-scdn.net
ci.line-apps.com
cix.line-apps.com
scdn.line-apps.com
ch-news.line-apps.com
torimochi.line-apps.com
aax-us.amazom-adsystem.com
aax-us-pdx.amazom-adsystem.com

Why you believe this should be added:

Add to list:
Ads List

Other info you think we should know:
This domain is an ads for LINE Messenger.

**Comment by cryptogap** [comment]
This has been completed and will be included in the next push
