### ISSUE TITLE
[Remove Request] - project-rainbowcrack.com

### ISSUE THREAD

**Issue by majick** [blocklistproject/Lists#636]
URL you wish to be removed:
project-rainbowcrack.com

Why you believe this to be a false positive:
This is the well-known site for a standard security analysis tool.  The site is not malicious nor is the software it distributes. There are no indications of compromise to the site itself, its supply chain, or the downloaded artifacts.  It does not meet this list's definition of "sites intended to deceive" as no deception is taking place.  

List it is on:
https://raw.githubusercontent.com/blocklistproject/Lists/master/abuse.txt

Other info you think we should know:
This issue was edited due to being submitted malformed.

**Comment by thomasmerz** [comment]
I agree. See https://en.wikipedia.org/wiki/RainbowCrack 👍🏻

**Comment by thomasmerz** [comment]
I've created PR #656 for this issue. Please review and merge.

**Comment by blocklistproject** [comment]
This has been fixed
