### ISSUE TITLE
[Remove Request] - mail.gandi.net

### ISSUE THREAD

**Issue by PeterDaveHello** [blocklistproject/Lists#637]
## URL you wish to be removed:

mail.gandi.net

## Why you believe this to be a false positive:

It's Gandi's mail server, not sure why it's banned?

Reference:

- https://docs.gandi.net/en/gandimail/standard_email_settings/

## List it is on:

- malware
- everything

**Comment by PeterDaveHello** [comment]
cc #108

**Comment by thomasmerz** [comment]
I've created PR #657 for this issue. Please review and merge.

**Comment by thomasmerz** [comment]
@PeterDaveHello It is indeed actively maintained. Please be patient - the maintainers do this in their spare time, it's not their job.

**Comment by blocklistproject** [comment]
This has been fixed

**Comment by thomasmerz** [comment]
Hooray! @PeterDaveHello 🎉
