### ISSUE TITLE
[Remove Request] - HackForums.net (abuse)

### ISSUE THREAD

**Issue by labrocca** [blocklistproject/Lists#639]
URL you wish to be removed: hackforums.net

Why you believe this to be a false positive:  Legit site, not meant to deceive. Has hundreds of thousands of members.

List it is on: abuse

Other info you think we should know:

**Comment by Sheffybarbe** [comment]
Agreed, site isn't harmful at all.

**Comment by ProofHF** [comment]
Agree as well, block should be removed. Will not bother using an MBAM solutions meanwhile.

**Comment by labrocca** [comment]
Well the list is "abuse" and label is for "Lists of sites created to deceive" domains, which HF is completely inaccurate.

**Comment by NintendoHF** [comment]
Best forum out there I'm a active user of the community and I agree this should be removed from the list.

**Comment by marktopper** [comment]
Vouching for HackForums as a legitimate forum. The site doesn't allow nor support any illegal activity, it's a community to learn about cybersecurity.

**Comment by PURE-CODER-1** [comment]
I vouch for HackForums. One of the Best Websites on the Internet for learning cybersecurity for FREE.

**Comment by thomasmerz** [comment]
Guys, don't complain, feel free to make a PR next time. This time I did it for you: #658
This took only few minutes:
```
s=hackforums.net
vim $(ack -l $s|grep -vE "alt-version|dnsmasq-version")
```
