### ISSUE TITLE
jaleco.com

### ISSUE THREAD

**Issue by mkb2091** [blocklistproject/Lists#64]
URL you wish to be removed: jaleco.com

Why you believe this to be a false positive: It blocks https://mirror.jaleco.com/gimp/gimp/v2.10/windows/gimp-2.10.20-setup-1.exe which is the download link for GIMP an image processing program

List it is on: malware.txt

Other info you think we should know:

**Comment by gap579137** [comment]
This has been fixed, thank you for your help!
