### ISSUE TITLE
[Remove Request] - doc.emergingthreats.net

### ISSUE THREAD

**Issue by Jakes-Lab** [blocklistproject/Lists#640]
URL you wish to be removed: 

doc.emergingthreats.net

Why you believe this to be a false positive: 

This is the documentation wiki for ProofPoint's IDS/IPS rulesets. Was quite surprised to find it was blocked on the malware domain list.

List it is on:

malware

**Comment by blocklistproject** [comment]
This has been fixed. Thank you
