### ISSUE TITLE
[Add request] Various NSFW imagebooru sites

### ISSUE THREAD

**Issue by xjrb10** [blocklistproject/Lists#641]
URL you wish to be added:
rule34.paheal.net
konachan.com
yande.re

Why you believe this should be added: NSFW

Add to list: https://blocklistproject.github.io/Lists/porn.txt

Other info you think we should know:
konachan.net is a filtered version of the website

**Comment by spirillen** [comment]
@xjrb10  did you know Dante have made a browser [add-on](https://mypdns.org/infrastructure/mypdns-report) for this?

**Comment by thomasmerz** [comment]
I created PR #659 for this issue. Please review and merge.

**Comment by fishcharlie** [comment]
@xjrb10 How did you come across these domains? There is some discussion about ripping concerns here: https://github.com/blocklistproject/Lists/pull/678#pullrequestreview-894538826.

**Comment by xjrb10** [comment]
@fishcharlie *my profile pic was from one lmao*

I'm not ripping anyone here, these are some well-known imagebooru sites... I don't know how these lists contain the most obscure domains and subdomains out there, but not these
