### ISSUE TITLE
[Remove Request] - cdn.cookielaw.org

### ISSUE THREAD

**Issue by Tricky-M** [blocklistproject/Lists#644]
URL you wish to be removed: cdn.cookielaw.org

Why you believe this to be a false positive: Some websites break when blocked (scrolling [on here](https://www.sweatybetty.com/) as cookie banner blocked), regarding regulations, etc. 

List it is on: [ads](https://blocklistproject.github.io/Lists/ads.txt)

Other info you think we should know: Has been removed from gambling list already #33

**Comment by thomasmerz** [comment]
Please review and merge my PR #660

**Comment by blocklistproject** [comment]
This has been fized
