### ISSUE TITLE
6 etxra p*rn websites that are not yet blocked

### ISSUE THREAD

**Issue by TruthfullEdward** [blocklistproject/Lists#662]
URL you wish to be added: www.goldpornfilms.com www.bestandfree.com www.tubexclips.com www.lusthero.com www.teenda.com and gfpimps.com

Why you believe this should be added: To let the ones who use this filter to be safer on the internet.

Add to list: all URL's linked above.

Other info you think we should know: Reachability of sites tested in Linux. And confirmed that they are still reachable. (PS:. don't remove the www from the URL's. Only the last one is written without www)

**Comment by spirillen** [comment]
- goldpornfilms.com (https://mypdns.org/my-privacy-dns/porn-records/-/issues/2455)
- bestandfree.com (https://mypdns.org/my-privacy-dns/porn-records/-/issues/6319)
- tubexclips.com (https://mypdns.org/my-privacy-dns/porn-records/-/issues/2494)
- lusthero.com ()
- teenda.com (https://mypdns.org/my-privacy-dns/porn-records/-/issues/57476)

Just a friendly note, this looks like you have taken these records from mypdns.org and if you do you are free to do so by crediting the source and inform about the [license cc-by-nc 4.0](https://mypdns.org/my-privacy-dns/porn-records/-/blob/master/LICENSE)

**Comment by TruthfullEdward** [comment]
@spirillen I just copied these URL's from the URL bar but not from the page you mentioned (mypdns.org) I do not know how this could have happened. But I still hope you will add those to your list.

**Comment by blocklistproject** [comment]
> * goldpornfilms.com (https://mypdns.org/my-privacy-dns/porn-records/-/issues/2455)
> * bestandfree.com (https://mypdns.org/my-privacy-dns/porn-records/-/issues/6319)
> * tubexclips.com (https://mypdns.org/my-privacy-dns/porn-records/-/issues/2494)
> * lusthero.com ()
> * teenda.com (https://mypdns.org/my-privacy-dns/porn-records/-/issues/57476)
> 
> Just a friendly note, this looks like you have taken these records from mypdns.org and if you do you are free to do so by crediting the source and inform about the [license cc-by-nc 4.0](https://mypdns.org/my-privacy-dns/porn-records/-/blob/master/LICENSE)

I am not sure that just because those URLs are on the mypdns.org website means they must be credited as found by that means.

**Comment by blocklistproject** [comment]
These have been added and will be in the next push

**Comment by TruthfullEdward** [comment]
@blocklistproject Thanks a lot for adding these URL's!

**Comment by spirillen** [comment]
That all ok, the reason is as you might suspect, the hit frequency 4 out of 5. We leave it here as a honest commit :+1: 

@blocklistproject wrote: 

> I am not sure that just because those URLs are on the mypdns.org website means they must be credited as found by that means.

It only applies as it comes from another project licensed under any FOSS license they do by default all requires information about the LICENSE + credit to source

I can then inform I do use the CC-BY-NC-4 for the PR + matrix lists, as I share for free, I do not work for free.
-------------

This said, allow me to do a little commercial for @dante's Browser add-on: https://mypdns.org/infrastructure/mypdns-report which makes reporting a right click report as.

**Comment by TruthfullEdward** [comment]
@spirillen You can trust me, I didn't copy it from the 'mypdns' site.

**Comment by spirillen** [comment]
> @spirillen You can trust me, I didn't copy it from the 'mypdns' site.

I do as I tried to say before :) and you are always welcome at mypdns

**Comment by TruthfullEdward** [comment]
@spirillen Looks an interesting tool! But can it also make an add request to the 'blocklistproject Github'?

**Comment by spirillen** [comment]
> @spirillen Looks an interesting tool! But can it also make an add request to the 'blocklistproject Github'?

mypdns is a piracy democracy, all man are equal until the battle, then the Captain rules  :skull_and_crossbones:  unlike somewhere else at the moment.... :sob: 

Yes you can make the request, but as MyPDNS is my baby i would of curse advocate that all [PR](https://mypdns.org/my-privacy-dns/porn-records) blacklist maintainers forced their commit to one place, (guess where); this is related to my dream of [matrix.rocks](https://mypdns.org/infrastructure/matrix-rocks/www.matrix.rocks)  which isn't a blacklist but domain knowledge to help the individual project to build an maintain their list from shared knowledge. The [Matrix](https://mypdns.org/my-privacy-dns) is only the beginning of this as @pyfunceble (@funilrys) and other sources have to connect in one big Eco system, oh, and the project sure need a web developer to launch some functional pages :smirk: 

---------------------------

@blocklistproject how about share our resources as long with IE @shadowwhisper ?? there are 1. the browser add-on 2. there is a moderator script in Development (brainstorm face right now) https://mypdns.org/mypdns/support/-/issues/620, comments are always welcome and we are still open for helpers.

An after all, I have the documentations for near 100.000 p**n domain already on hand and they are not going to be deleted numerous times by [Github](https://mypdns.org/my-privacy-dns/porn-records/-/issues/1347) and Gitlab, they are safe, and constantly backed up 3 places.

See also the old https://github.com/clefspeare13/pornhosts now safely running at https://mypdns.org/clefspeare13/pornhosts
