### ISSUE TITLE
518 + 260 additional URL's for p*rn-blocklist

### ISSUE THREAD

**Issue by TruthfullEdward** [blocklistproject/Lists#664]
URL you wish to be added:  see documents below

Why you believe this should be added: To make internet for the Pi-Hole user a lot safer

Add to list: all the URL's below

Other info you think we should know:
One .txt file contains URL's with WWW (518) and the second one has URL's from the same list without www (260). All URL's have been tested in Linux for reachability. All of them are still reachable (all URL's from both documents). Please add them all to your blocklist!
[alpha sort FAIL_check (www).txt](https://github.com/blocklistproject/Lists/files/8121311/alpha.sort.FAIL_check.www.txt)
[alpha sort FAIL_check (point).txt](https://github.com/blocklistproject/Lists/files/8121313/alpha.sort.FAIL_check.point.txt)

**Comment by thomasmerz** [comment]
Sorry, I had to remove some lines 🤷🏻‍♂️ 
`domain.tld/some_url` can't be filtered in host-format by Pi-hole and Co. This was the case for some reddit.com URLs.

**Comment by TruthfullEdward** [comment]
@thomasmerz OK, hope you didn't had to remove too many of them. I checked the URL's with a bash. command and they were all reachable. If you would have some tips for me to avoid this 'mistake', please let me know.

**Comment by thomasmerz** [comment]
@TruthfullEdward 
I don't remember the exact number - but it hasn't been less than 10. No problem 😉 

Remove these domains/lines and check domains afterwards:
```
$ sed -i '/\//d' file-with-domains.txt
$ for d in $(cat file-with-domains.txt); do curl $d &>/dev/null || sed -i "/$d/d" file-with-domains.txt; done
```

**Comment by TruthfullEdward** [comment]
@thomasmerz oh ok, I'm happy you didn't had to remove like half of it. I'll try the commands right away.

**Comment by TruthfullEdward** [comment]
@thomasmerz The command you gave me deleted the entire content of file-with-domains.txt. (I'm not sure, but think this is caused by the pipe-command) No worries, I have backup.

**Comment by thomasmerz** [comment]
Over here it worked fine 🤷🏻‍♂️

**Comment by TruthfullEdward** [comment]
Ah, no, just made a little error (wrote $ d instead of $d). Took a bit of time to process the file. I've put the outcome in a .txt file. Please have a look at it and tell me if this time it's good.
[test2 new code.txt](https://github.com/blocklistproject/Lists/files/8127374/test2.new.code.txt)

**Comment by thomasmerz** [comment]
No need to test - I included everything that was possible (99,999% 😄 ) of your input into PR #666  👍🏻

**Comment by TruthfullEdward** [comment]
@blocklistproject Thank you for adding those URL's to your blocklist! Appreciate your quick reaction to my add request!

**Comment by TruthfullEdward** [comment]
@thomasmerz Why can't such URL's be added to the blocklist?
![image](https://user-images.githubusercontent.com/99840866/160294975-faaa025b-3307-4571-a0d5-dd45a6f45aad.png)

**Comment by thomasmerz** [comment]
The screenshot should already explain WHY some "domains" couldn't be added:
Pi-hole can only use and filter `sub.domain.tld` ("hostnames" and/or domainnames) and not URLs (the part after `https://somehost.somedomain.topleveldomain` like `/somepath/`).
