### ISSUE TITLE
[Remove Request] - soundindepth.com

### ISSUE THREAD

**Issue by Rexadev** [blocklistproject/Lists#668]
URL you wish to be removed: soundindepth.com

Why you believe this to be a false positive: Famous music website

List it is on: abuse, malware

Other info you think we should know:

**Comment by cryptogap** [comment]
This has been fixed and will be included in the next push

**Comment by Rexadev** [comment]
> This has been fixed and will be included in the next push

Update NextDNS Intelligence Feed blocks it.
