### ISSUE TITLE
xnxx.com

### ISSUE THREAD

**Issue by p1r473** [blocklistproject/Lists#67]
URL you wish to be removed: xnxx.com

Why you believe this to be a false positive: This is an adult film website, and is not malicious nor an advertiser

List it is on: abuse, ads, malware

**Comment by gap579137** [comment]
This has been fixed, thank you for your help!

**Comment by spirillen** [comment]
And it does... try `games.xnxx.com` that redirect to??

<details><summary>The answer for dummies</summary>
<p>

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +5 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/3699/thumbnail_image/w270_webp-832c8a4dbb372e99b3070804bb58a423.webp` |
| +5 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/3550/thumbnail_image/w270_webp-d0ce76de78c827512860723a950a4c32.webp` |
| +5 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/3557/thumbnail_image/w270_webp-39f30feb6d2019a05f08aee87556cbe2.webp` |
| +5 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/3564/thumbnail_image/w270_webp-514ee0aacebe2186f7090c9d532ed0d0.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | script | `https://assets-cdn.xnxx-games.com/packs/commons-fb74c2c5d4980a4c8d7d.js` |
| +4 | \|\|tracking.sexcash.com^ | -- | xnxx-games.com | 3 | get | script | `https://tracking.sexcash.com/tracking-script.js` |
| +4 |  |  | xnxx-games.com | 3 | get | image | `https://assets-cdn.skynetworkcdn.com/assets/svg/flags/en-8c81a6a0207c597531b44a921bdd6dcca85d048f900f0fa3530a16da138bcb75.svg` |
| +4 | /matomo.js$from=~github.com | -- | xnxx-games.com | 1 | get | script | `https://track.xnxx-games.com/matomo.js` |
| +4 |  |  | xnxx-games.com | 1 | get | script | `https://assets-cdn.xnxx-games.com/packs/xnxx/application-fb74c2c5d4980a4c8d7d.js` |
| +4 |  |  | xnxx-games.com | 1 | get | script | `https://assets-cdn.xnxx-games.com/packs/xnxx/disclaimer-fb74c2c5d4980a4c8d7d.js` |
| +4 |  |  | xnxx-games.com | 1 | get | script | `https://assets-cdn.xnxx-games.com/packs/xnxx/item_index-fb74c2c5d4980a4c8d7d.js` |
| +4 |  |  | xnxx-games.com | 1 | get | script | `https://assets-cdn.xnxx-games.com/packs/commons-fb74c2c5d4980a4c8d7d.js` |
| +4 | \|\|tracking.sexcash.com^ | -- | xnxx-games.com | 3 | get | script | `https://tracking.sexcash.com/tracking-script.js` |
| +4 |  |  | xnxx-games.com | 1 | get | css | `https://assets-cdn.xnxx-games.com/assets/xnxx/packs/item_index-bc506c5a2e8da52de39d04a277a6da65ef4bf4534e38059ee54f76d65e875c9c.css` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/3706/thumbnail_image/w370_webp-8c85b3d78c84a15cd07922e4692b3261.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/3727/thumbnail_image/w370_webp-a0da456ad0e9aece0ab69068bc0008f7.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/3734/thumbnail_image/w370_webp-02888d3c5bcedf6b7c96ac7194341853.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/3398/thumbnail_image/w370_webp-0b8f8a0fa7e676e2f5b9459c53153330.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/9063/thumbnail_image/w370_webp-6f870c737b4dd8ded75027b4c9a0b38b.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/8563/thumbnail_image/w370_webp-8ba81fd55bacfe284be1260f930480a2.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/8671/thumbnail_image/w370_webp-3abfb50b6a73fda2921714aa46907e7b.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/4807/thumbnail_image/w370_webp-4019ed237f75697729fad9f0e071775c.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/4913/thumbnail_image/w370_webp-d4dad0bfa1ca6f56bb6dfd6e08eb68d2.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/9015/thumbnail_image/w370_webp-f73bb6403ff9a108e0c0d2d2e097e98d.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/8464/thumbnail_image/w370_webp-1d740fab833296aa9fe0b21c5aa8ca6b.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/video_preview/8959/thumbnail_image/w370_webp-b417b3908872a39e702ae0ce01affe91.webp` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets-cdn.xnxx-games.com/assets/xnxx/icons/menu-white-bd1cbf98b31f018ffda58289f192f23657bf3f131cbf7bdbcc8ee5ab2ef7c233.svg` |
| +4 |  |  | xnxx-games.com | 1 | get | image | `https://assets.xnxx-games.com/website/3/logo_picture/fea18c3fdba782d8697d858d466abc23.svg` |
| +4 | /matomo.js$from=~github.com | -- | xnxx-games.com | 1 | get | script | `https://track.xnxx-games.com/matomo.js` |
| +4 |  |  | xnxx-games.com | 1 | get | css | `https://assets-cdn.xnxx-games.com/assets/xnxx/packs/application-34752353a98611cd47275c07302682363ef0b3c44227980b114378f4b8468bf4.css` |
| +3 |  |  | xnxx-games.com | 1 | get | doc | `https://xnxx-games.com/?xt=none` |
| +1 |  |  | games-auth.xnxx.com | 1 | get | doc | `https://games-auth.xnxx.com/` |
| +1 |  |  | behind-the-scene | 0,3 | get | xhr | `https://games.xnxx.com/public/landing-gh/background-landscape.png` |
| +1 |  |  | behind-the-scene | 0,3 | get | xhr | `https://games.xnxx.com/public/landing-gh/background-mobile.png` |
| +1 |  |  | behind-the-scene | 0,3 | get | xhr | `https://games.xnxx.com/public/landing-gh/play.png` |
| +1 |  |  | behind-the-scene | 0,3 | get | xhr | `https://games.xnxx.com/public/landing-gh/background-desktop.png` |
| +1 |  |  | behind-the-scene | 0,3 | get | xhr | `https://games.xnxx.com/public/images/icons/ios.png` |
| +1 |  |  | behind-the-scene | 0,3 | get | xhr | `https://games.xnxx.com/public/images/icons/android.png` |
| +1 |  |  | behind-the-scene | 0,3 | get | xhr | `https://games.xnxx.com/public/images/icons/desktop.png` |
| +1 | ##+js(abort-on-property-read, fuckAdBlock) |  | games.xnxx.com |  | get | scriptlet | `https://games.xnxx.com/` |
| +1 | ##+js(set-local-storage-item, xvutils.nb_tabs_opened, 1) |  | games.xnxx.com |  | get | scriptlet | `https://games.xnxx.com/` |
| +1 | \|\|mc.yandex.ru^ | -- | games.xnxx.com | 3 | get | script | `https://mc.yandex.ru/metrika/watch.js` |
| +1 |  |  | games.xnxx.com | 1 | get | script | `https://games.xnxx.com/public/objectFitPolyfill.min.js` |
| +1 |  |  | games.xnxx.com | 1 | get | script | `https://games.xnxx.com/public/modernizr-custom.js` |
| +1 |  |  | games.xnxx.com | 1 | get | script | `https://games.xnxx.com/public/bootstrap.min.js` |
| +1 |  |  | games.xnxx.com | 1 | get | script | `https://games.xnxx.com/public/jquery.min.js` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/footer/submit-en.png` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/footer/footer.png` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/cxl.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/fallen.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/chuchu.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/pzp.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/nakadashi.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/detective-masochist.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/wild-school-new-en.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/lust-of-apartement-wives.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/unbreaker_en.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/tld.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/rlws.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/hldx_en.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/gods-of-hentai.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/ppx_xnxx.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/gray_en.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/dg.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/hentai-heroes.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/rdc.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/lois_en.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/tlw_en.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/nfs_xnxx.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/cq.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/bitc.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/banners/ha-logo.png` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/banners/ha-banner.jpg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/icons/right-chevron.svg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/icons/menu.svg` |
| +1 |  |  | games.xnxx.com | 1 | get | image | `https://games.xnxx.com/public/images/logo-xnxx.png` |
| +1 |  |  | games.xnxx.com | 1 | get | script | `https://games.xnxx.com/public/redirection-xnxx.js` |
| +1 |  |  | games.xnxx.com | 1 | get | css | `https://games.xnxx.com/public/style.css` |
| +1 |  |  | games.xnxx.com | 1 | get | css | `https://games.xnxx.com/public/bootstrap.min.css` |
| +1 | \|\|googleapis.com^ | -- | games.xnxx.com | 3 | get | css | `https://fonts.googleapis.com/css?family=Roboto:400,500,500italic,700,400italic,700italic` |
| +0 |  |  | games.xnxx.com | 1 | get | doc | `https://games.xnxx.com/` |
| +0 |  |  | games.xnxx.com | 1 | get | doc | `http://games.xnxx.com/` |
</details>


</p>
</details>
