### ISSUE TITLE
axeol-shop.com

### ISSUE THREAD

**Issue by orosseel** [blocklistproject/Lists#68]
This is a fake website without any products or contact information. It is used to mislead people on facebook. Users that buy products via direct links have to pay with iDeal or bancontact. There is no option to use visa, mastercard, paypal, ... Unfortunately, buyers do not receive their order.

**Comment by hapx101** [comment]
Please check the [CONTRIBUTING.md](https://github.com/blocklistproject/Lists/blob/master/CONTRIBUTING.md) and add the URLs in the respective list.

**Comment by gap579137** [comment]
If you are unsure of how to use git. Please let us know and include the list you think the url should go on and we can investigate.

**Comment by orosseel** [comment]
Done. I hope in the correct way.
