### ISSUE TITLE
[Remove Request] - inflation.us

### ISSUE THREAD

**Issue by p1r473** [blocklistproject/Lists#680]
URL you wish to be removed: inflation.us

Why you believe this to be a false positive: This is a false positive. This is a website related to inflation statistics. Not malicious.

List it is on: abuse.txt malware.txt

**Comment by thomasmerz** [comment]
When I'm trying to open this URL I get the following info (outside Pi-hole) 🤷🏻‍♂️ 

<img width="674" alt="grafik" src="https://user-images.githubusercontent.com/18568381/156263473-0a024bb0-03d9-4b03-9d9a-af6fd109f6f5.png">

**Comment by p1r473** [comment]
Works for me 
![Screenshot_20220301-194233](https://user-images.githubusercontent.com/9235633/156272958-4fa1888c-eda8-4515-a999-844b9b3f4828.png)

**Comment by blocklistproject** [comment]
This has been fixed
