### ISSUE TITLE
Pihole warning

### ISSUE THREAD

**Issue by Dynasty-Dev** [blocklistproject/Lists#681]
Hello, i added your phishing protection list but i get the error when updating pihole gravity
![image](https://user-images.githubusercontent.com/89283708/155910849-90e63e8e-f3f2-45f0-91a4-ee94971c3cba.png)

**Comment by cryptogap** [comment]
Will look into this right now

**Comment by SodaWithoutSparkles** [comment]
I think the Φ is the problem?

**Comment by thomasmerz** [comment]
@Dynasty-Dev , this IDN domains should have been removed in issue #628, but something didn't work!? I already made a new PR 😁

**Comment by Garrison88** [comment]
I just used this list today and am seeing this error in the phishing list:
Number of invalid domains on this list: 1

Last update was March 1st

**Comment by thomasmerz** [comment]
> I just used this list today and am seeing this error in the phishing list: Number of invalid domains on this list: 1
> 
> Last update was March 1st

See my PR from Mar 1st.

**Comment by Dynasty-Dev** [comment]
> @Garrison88
> 
> > I just used this list today and am seeing this error in the phishing list: Number of invalid domains on this list: 1
> > Last update was March 1st
> 
> See my PR from Mar 1st.

is this list no longer updated? it seems dead

**Comment by thomasmerz** [comment]
From their Discord Server:
> @everyone welcome. We are working on a few changes on the backend regarding how the lists are put together and delivered. You may see some issues and pull requests sitting untouched for a couple more days to a week while we finish up these changes

https://discord.com/channels/945007498186879016/945007498665017366/956908948794015744
