### ISSUE TITLE
[Remove Request] - `smarturl.it` / `www.smarturl.it`

### ISSUE THREAD

**Issue by PeterDaveHello** [blocklistproject/Lists#684]
URL you wish to be removed:

- `smarturl.it`
- `www.smarturl.it`

Why you believe this to be a false positive:

It's a URL redirect service, just like the other short url services, not unusual to be leveraged by attackers, but the service itself it's not harmful.

None of of these secure DNS below blocked it:

 - OpenDNS
 - Cloudflare
 - Yandex
 - AkamaiETP
 - SafeDNS
 - CleanBrowsing
 - Neustar
 - Comodo
 - CONTROL D
 - Quad9

More info:

AlienVault - Open Threat Exchange
 - https://otx.alienvault.com/indicator/domain/smarturl.it
Google Safe Browsing
 - https://transparencyreport.google.com/safe-browsing/search?url=smarturl.it
McAfee SiteAdvisor
 - https://siteadvisor.com/sitereport.html?url=smarturl.it
Norton Safe Web
 - https://safeweb.norton.com/report/show?url=smarturl.it
OpenDNS
 - https://domain.opendns.com/smarturl.it
URLVoid
 - https://www.urlvoid.com/scan/smarturl.it/
VirusTotal
 - https://www.virustotal.com/en/domain/smarturl.it/information/
Yandex Site safety report
 - https://yandex.com/safety/?l10n=en&url=smarturl.it

List it is on:

phishing (https://blocklistproject.github.io/Lists/alt-version/phishing-nl.txt)

Other info you think we should know:

Also reported here:

- https://github.com/mitchellkrogza/Phishing.Database/issues/306

**Comment by spirillen** [comment]
@PeterDaveHello It is tracking, all url redirector (shorteners) is about tracking user activities, and most of them uses cookies for this. To avoid the third party cookie blocking, they uses this redirect to become first party cookie.

And personally, I would never follow a link I can't see the destination of. https://mypdns.org/mypdns/support/-/wikis/contributing/Writing-Guide#links

**Comment by PeterDaveHello** [comment]
Hi @spirillen, thanks for your feedback, I fully understand that part, just thinking about if URL shorteners are simply equal to or categorized into phishing?

If it's clear that a tracker is not equal to a phishing site, distinguishing them may be important?

**Comment by spirillen** [comment]
> Hi @spirillen, thanks for your feedback, I fully understand that part, just thinking about if URL shorteners are simply equal to or categorized into phishing?
> 
> If it's clear that a tracker is not equal to a phishing site, distinguishing them may be important?

personally I add these as `Redirector` and `Tracking` by default as you can see in this issue template (https://mypdns.org/my-privacy-dns/matrix/-/blob/master/.gitlab/issue_templates/Redirecting.md) If you think of two other typically use cases there are AdWare and SpyWare, But I believe this as default out of the general scope.

**Comment by thomasmerz** [comment]
BTW: It's also on other blocklists:
```
$ pihole pihole -q "$s"
 Match found in https://raw.githubusercontent.com/blocklistproject/Lists/master/phishing.txt:
   smarturl.it
   www.smarturl.it
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe:
   smarturl.it
   www.smarturl.it
 Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection:
   smarturl.it
   www.smarturl.it
```

**Comment by PeterDaveHello** [comment]
RPiList seems to have a more False Positive cases, including `opensea.io` and other URL shorteners 😅

**Comment by thomasmerz** [comment]
@PeterDaveHello , feel free to report those in an [issue](https://github.com/RPiList/specials/issues/new) or fix them with a PR 😃

**Comment by PeterDaveHello** [comment]
@thomasmerz sure, I'll send a few, but can't do for all those FPs I found, too many though 😅

**Comment by thomasmerz** [comment]
If you've already found them: why not remove them all instead of only some of them? 😕
Open an issue with all false positive domains to be removed and I'll be thinking about a PR… Deal?

**Comment by blocklistproject** [comment]
These have been moved
