### ISSUE TITLE
[Remove Request] - shifen.com

### ISSUE THREAD

**Issue by MySoul182** [blocklistproject/Lists#686]
URL you wish to be removed:shifen.com

Why you believe this to be a false positive:阻止了这个域名会访问不了www.baidu.com

List it is on:https://blocklistproject.github.io/Lists/adguard/tracking-ags.txt

Other info you think we should know:因为shifen.com和baidu.com两台域服务器其实是同一台服务器，而baidu.com对www.baidu.com进行别名转换的时候，其实是会直接返回shifen.com域服务器的ip的

**Comment by thomasmerz** [comment]
Agree, it has also been removed from other lists some time ago 👍🏻 
https://blocklist-tools.developerdan.com/entries/search?q=shifen.com

The "[Quantum Ad List](https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/commits/master)" from this link had its last commit about 10 months ago - seems to be unmaintained… 🤷🏻‍♂️
