### ISSUE TITLE
[Remove Request] - taylorandng.com

### ISSUE THREAD

**Issue by IcedEagle** [blocklistproject/Lists#687]
URL you wish to be removed: taylorandng.com and www.taylorandng.com

Why you believe this to be a false positive: This is an Asian cookware company. I was trying to buy a wok from them.

List it is on: fraud-nl.txt

Other info you think we should know:

**Comment by thomasmerz** [comment]
Agree - see https://www.startpage.com/sp/search?q=taylorandng.com 👍🏻  

<img width="867" alt="grafik" src="https://user-images.githubusercontent.com/18568381/162063141-ef5ef873-4d11-4fe7-bb0d-7e2daa18f29d.png">
