### ISSUE TITLE
[Remove Request] - torproject.org

### ISSUE THREAD

**Issue by ethnh** [blocklistproject/Lists#689]
URL you wish to be removed:

torproject.org
checktorproject.org
*.checktorproject.org

Why you believe this to be a false positive:
These sites are far from redirect sites, I'd think😅

List it is on:
All in redirect.txt

**Comment by thomasmerz** [comment]
I agree with `torproject.org` but not with `*.checktorproject.org`because:
```
$ pihole pihole -q torproject.org
 Match found in https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt:
   checktorproject.org
   magento.checktorproject.org
   shop.checktorproject.org
   staging.checktorproject.org
   test.checktorproject.org
   thor.checktorproject.org
   ww1.checktorproject.org
   ww16.checktorproject.org
   ww38.checktorproject.org
   www.checktorproject.org
```

**Comment by EthanHindmarsh** [comment]
RE: Thomas
Fair enough, allowing torproject alone will solve my issue anyway 👍
