### ISSUE TITLE
[Remove Request] - competera.net

### ISSUE THREAD

**Issue by kprkpr** [blocklistproject/Lists#690]
URL you wish to be removed: competera.net

Why you believe this to be a false positive: It's a business for see competence prices and compare it

List it is on: Fraud

Other info you think we should know:
I searched the page in Google and it's good voted in different pages of reviews and seems a legit page, like others that does this type of business

**Comment by thomasmerz** [comment]
https://www.startpage.com/do/dsearch?query=competera.net looks good 👍🏻 

<img width="891" alt="grafik" src="https://user-images.githubusercontent.com/18568381/162071439-9cff59b2-05df-4d15-98ce-ca68e1575a2a.png">
