### ISSUE TITLE
[Add request] Ad + Fraud(Borderline)

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#693]
URL you wish to be added:
`https://mcafee.software-reminder.cloud/WW/utility/mcf/promo/LP03/V09d.php?lpkey=1608470e78a5731f94&domain=cnvpro.xyz&region=Assam&bb=0&isp=Jio&language=en-IN&uclick=h9ojqdxo0&uclickhash=h9ojqdxo0-h9ojqdxo0-wfrn-0-bzm7-ktvc-rn17-9eb7d0`

Why you believe this should be added:
`Ads promoted by McAfee's Affiliate partners `

Add to list:
Ad

Other info you think we should know:

![McAfee Fraud ad](https://user-images.githubusercontent.com/33965848/159166853-c98208cd-976d-4970-a31b-f0ca7169a5bb.gif)

**Comment by iam-py-test** [comment]
I think this should be added to the Scam list, based on your screenshots.
Where did you get this from? The link seems to be locked to your IP/browser, [so just returns a blank page](https://app.any.run/tasks/3e4acd4e-a879-422a-b12e-29f792f52a27)

**Comment by spirillen** [comment]
Wee long time since I saw scareware...

**Comment by spirillen** [comment]
I'm drawing a black page as well

**Comment by spirillen** [comment]
> I think this should be added to the Scam list, based on your screenshots. Where did you get this from? The link seems to be locked to your IP/browser, [so just returns a blank page](https://app.any.run/tasks/3e4acd4e-a879-422a-b12e-29f792f52a27)

Hmm gives me spyware

![image](https://user-images.githubusercontent.com/44526987/159170368-5cdc05a4-a9e2-4ec9-84c7-ad716713fe03.png)

**Comment by iam-py-test** [comment]
> > I think this should be added to the Scam list, based on your screenshots. Where did you get this from? The link seems to be locked to your IP/browser, [so just returns a blank page](https://app.any.run/tasks/3e4acd4e-a879-422a-b12e-29f792f52a27)
> 
> Hmm gives me spyware
> 
> ![image](https://user-images.githubusercontent.com/44526987/159170368-5cdc05a4-a9e2-4ec9-84c7-ad716713fe03.png)

Probably because you are using Tor Browser (far too many pages think anyone using Tor is trying to DDoS them :( )

**Comment by spirillen** [comment]
> Probably because you are using Tor Browser (far too many pages think anyone using Tor is trying to DDoS them :( ) But that doesn't matter, I see the same thing as you on a real machine

It is all about ClaoudFlare and the censorship and anti democracy acts. If you like there are actually some people who have spend some hours of the life to write more about this, nor saying I'm all into it, but there are for sure some good pointers: https://mypdns.org/admin/projects/counterculture/right-to-be-offline & https://mypdns.org/dCF/deCloudflare

**Comment by iam-py-test** [comment]
> https://mypdns.org/admin/projects/counterculture/right-to-be-offline

Returns 404

**Comment by spirillen** [comment]
> 

not 404 but request sign in... weird he just posted it yesterday

**Comment by iam-py-test** [comment]
> > 
> 
> Of curse... notice the /admin/ in the link :P
> 
> Here> this one is working https://mypdns.org/counterculture/right-to-be-offline

Ok, that one works. Thanks
However, there isn't anything I can do about Cloudflare, and that isn't relevant is any way to this malicious website

**Comment by spirillen** [comment]
> there isn't anything I can do about Cloudflare, and that isn't relevant to this malicious website

Try this one, it is a start :smile: 

`*.ns.cloudflare.com.rpz-nsdname CNAME .` in your RPZ zone file

**Comment by alanjacobmathew** [comment]
>Where did you get this from? The link seems to be locked to your IP/browser, [so just returns a blank page](https://app.any.run/tasks/3e4acd4e-a879-422a-b12e-29f792f52a27)

Even I'm getting a blank page now. Source: A pop-up redirect from tamilmv.unblockit.app

**Comment by thomasmerz** [comment]
@alanjacobmathew , can this be closed due to this?
```
Host mcafee.software-reminder.cloud not found: 3(NXDOMAIN)
```

**Comment by cryptogap** [comment]
This will be closed until more info can be provided, if any
