### ISSUE TITLE
[Add request] Piracy

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#694]
URL you wish to be added:

```
https://www.1tamilmv.cool
https://tamilblasters.icu
https://unblockit.day/ 
https://unblockit.kim/
https://pirate-proxy.pw/
https://tpb23.ukpass.co/
https://piratez.xyz/
https://tpb.surf/
https://arrrr.ga/
https://pirate-bay-proxy.org/eng1/
https://pirate.cfd/
https://piraat.xyz/
https://wearethereal.ninja/
https://thepb.cyou/
https://thepiratebay.cam/
https://5mins.shop/
https://www3.yggtorrent.re/
https://tpb.monster/
https://knaben.ru/thepiratebay.php
https://mirrorbay.top/
https://tpb.wtf/
https://tpb.cnp.cx/index.php
https://tpb.skynetcloud.site/
https://piratetoday.xyz/
https://piratebayo3klnzokct3wt5yyxb2vpebbuyjl7m623iaxmqhsd52coid.onion.pet/
https://piratebayo3klnzokct3wt5yyxb2vpebbuyjl7m623iaxmqhsd52coid.onion.ly
```

Why you believe this should be added:
Torrent proxies

Add to list:
Piracy / Torrent

Other info you think we should know:

**Comment by thomasmerz** [comment]
How does anyone test/validate these requested domains? 🤷🏻‍♂️

**Comment by thomasmerz** [comment]
@cryptogap , what tools do you use to validate so many domains/requests?

**Comment by cryptogap** [comment]
Currently, I manually validate them on a firewall VM

**Comment by thomasmerz** [comment]
@cryptogap , you closed this issue, but I can't find the requested domains being added anywhere? There's also no PR… 🤷🏼‍♂️

**Comment by spirillen** [comment]
These

```
https://unblockit.day/ 
https://unblockit.kim/
```

redirects to `https://unblockit.pet/`...

`https://tpb23.ukpass.co/` redirects to `https://tpb25.ukpass.co/`... (https://mypdns.org/my-privacy-dns/matrix/-/issues/970547)

`https://tpb.surf/` redirects to `https://piratenow.xyz/` (https://mypdns.org/my-privacy-dns/matrix/-/issues/1164879)

`https://arrrr.ga/` ?? Seems more dead than alive (https://mypdns.org/my-privacy-dns/matrix/-/issues/970529)

`https://pirate-bay-proxy.org` redirects to `https://pirate-bay-proxy.org` (https://mypdns.org/my-privacy-dns/matrix/-/issues/2607026)

`pirate.cfd` No IP assigned (https://mypdns.org/my-privacy-dns/matrix/-/issues/970530)

`piraat.xyz` redirects to `https://piratenow.xyz/` (https://mypdns.org/my-privacy-dns/matrix/-/issues/1164879)

wearethereal.ninja Pirated.... (https://mypdns.org/my-privacy-dns/matrix/-/issues/970549) 

thepb.cyou also pirated (https://mypdns.org/my-privacy-dns/matrix/-/issues/970535)

thepiratebay.cam also pirated (https://mypdns.org/my-privacy-dns/matrix/-/issues/970543)

5mins.shop also pirated (https://mypdns.org/my-privacy-dns/matrix/-/issues/970528)

yggtorrent.re ACTIVE (Reported/Added)

tpb.monster Pirated (https://mypdns.org/my-privacy-dns/matrix/-/issues/970540)

knaben.ru (https://mypdns.org/my-privacy-dns/matrix/-/issues/970533)

mirrorbay.top ALIVE (https://mypdns.org/my-privacy-dns/matrix/-/issues/970532)

tpb.wtf redirects to https://piratenow.xyz/

tpb.cnp.cx dead (https://mypdns.org/my-privacy-dns/matrix/-/issues/970538)

tpb.skynetcloud.site ACTIVE (https://mypdns.org/my-privacy-dns/matrix/-/issues/970536)

piratetoday.xyz redirects to https://piratenow.xyz/

piratebayo3klnzokct3wt5yyxb2vpebbuyjl7m623iaxmqhsd52coid.onion.pet ACTIVE (https://mypdns.org/my-privacy-dns/matrix/-/issues/970539)

piratebayo3klnzokct3wt5yyxb2vpebbuyjl7m623iaxmqhsd52coid.onion.ly  ACTIVE (https://mypdns.org/my-privacy-dns/matrix/-/issues/970544)
