### ISSUE TITLE
[Remove Request] - 

### ISSUE THREAD

**Issue by Yasin0ps** [blocklistproject/Lists#698]
URL you wish to be removed:
point3.net

Why you believe this to be a false positive:
Not a porn website. Security Related website offering training and bootcamps. 

List it is on:
https://blocklistproject.github.io/Lists/porn.txt

Other info you think we should know:
https://twitter.com/point3sec

**Comment by thomasmerz** [comment]
Sorry, I couldn't find `point3.net` in this repo over here… 🤔 
https://github.com/blocklistproject/Lists/search?q=point3.net

**Comment by blocklistproject** [comment]
This has been fixed
