### ISSUE TITLE
[Remove Request] - Samsung newer smart TVs FOTA and app store

### ISSUE THREAD

**Issue by rh-fcristin** [blocklistproject/Lists#703]
URL you wish to be removed:
osb-v2.samsungqbe.com
osb-apps-v2.samsungqbe.com

Why you believe this to be a false positive:
blocking those domains breaks OTA firmware updates (osb-v2.samsungqbe.com) and the app store (osb-apps-v2.samsungqbe.com) on newer samsung smart TV, tested on Q60 and QN90 series (both on latest fw). It possibly break also initial TV configuration, my initial issue was found when reinstalling of the Q60 via smartthings android app, the procedure was failing. After unlocking both records it works flawlessly.

List it is on:
https://github.com/blocklistproject/Lists/blob/master/smart-tv.txt

Other info you think we should know:
none

**Comment by blocklistproject** [comment]
This is as expected please WL if needed
