### ISSUE TITLE
[Remove Request] - graph.instagram.com

### ISSUE THREAD

**Issue by Dynasty-Dev** [blocklistproject/Lists#704]
URL you wish to be removed:

graph.instagram.com
Why you believe this to be a false positive:

List it is on:
Ads

Other info you think we should know:

**Comment by thomasmerz** [comment]
It's also on some other blocklists that I know/use:
```
$ pihole pihole -q graph.instagram.com
 Match found in https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/MobileAppAds/appadsblocklist.txt:
   graph.instagram.com
 Match found in https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt:
   graph.instagram.com
```

**Comment by thomasmerz** [comment]
@cryptogap , should we also add `graph.facebook.com`, too?
```
$ pihole pihole -q graph.facebook.com
 Match found in exact blacklist
   graph.facebook.com
 Match found in https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt:
   a-graph.facebook.com
```

**Comment by nickp85** [comment]
Blocking graph.facebook.com has stopped Facebook from working. There is a separate Facebook list so I recommend removing it from the Ads list

**Comment by thomasmerz** [comment]
@nickp85 , this is partly true:
This PR breaks Facebook App (on iOS in my case).
But on my desktop computer everything still works fine.

Therefore `graph.facebook.com` should be removed from `ads.txt`.
But it's still valid for `facebook.txt` so anyone interested in blocking all Facebook can do this.

@cryptogap , please review and merge my bugfix in PR #744
