### ISSUE TITLE
[Remove Request] - lehne.de

### ISSUE THREAD

**Issue by spirillen** [blocklistproject/Lists#706]
URL you wish to be removed:

Why you believe this to be a false positive:https://mypdns.org/my-privacy-dns/porn-records/-/issues/146378

List it is on:porn

Other info you think we should know:

**Comment by thomasmerz** [comment]
I checked this out - it's about stock markets:
> Stefan Lehne
Börse Finanzen Megatrends
Speaker Autor Coach Mentor

**Comment by blocklistproject** [comment]
This is not located on our lists
