### ISSUE TITLE
[Remove Request] - absolut.com

### ISSUE THREAD

**Issue by spirillen** [blocklistproject/Lists#707]
URL you wish to be removed:

Why you believe this to be a false positive:https://mypdns.org/my-privacy-dns/porn-records/-/issues/146400

List it is on:porn

Other info you think we should know:

**Comment by thomasmerz** [comment]
Alcohol/Vodka is no porn 👍🏻

**Comment by thomasmerz** [comment]
But I couldn't find `absolut.com` in any lists…!? 🤔

**Comment by blocklistproject** [comment]
This is not on any of the lists
