### ISSUE TITLE
[Remove Request] - 123-counter.net

### ISSUE THREAD

**Issue by spirillen** [blocklistproject/Lists#710]
URL you wish to be removed:

Why you believe this to be a false positive:https://mypdns.org/my-privacy-dns/matrix/-/issues/978636

List it is on:porn

Other info you think we should know:

**Comment by thomasmerz** [comment]
Sorry, but I couldn't find this in any list over here… 🤔

**Comment by thomasmerz** [comment]
@spirillen , did you see my comment? Can you please clarify where you saw `123-counter.net` in this project?
BTW: Why is your GitLab down since some days/weeks? I couldn't also check your linked issue…

**Comment by blocklistproject** [comment]
Unable to find this on the lists
