### ISSUE TITLE
Invalid Domains

### ISSUE THREAD

**Issue by dtavilez** [blocklistproject/Lists#712]
I'm brain dead at the moment and can't figure out why I'm getting 15 invalid domains when adding this list. 

<html>
<body>

Health status of this list: | List download was successful (OK)
-- | --
This list was added to Pi-hole | a few seconds ago (2022-04-04 10:33:16)
Database entry was last modified | a few seconds ago (2022-04-04 10:33:16)
The list contents were last updated | a few seconds ago (2022-04-04 10:33:22)
Number of domains on this list: | 33
Number of invalid domains on this list: | 15
Database ID of this list: | 3

</body>
</html>

**Comment by spirillen** [comment]
It can be a mixed line ending

LF != CRLF

**Comment by thomasmerz** [comment]
@dtavilez , which list(s) in detail did you use?
```
  [i] Target: https://raw.githubusercontent.com/blocklistproject/Lists/master/fraud.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 196092 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/blocklistproject/Lists/master/phishing.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 190245 domains, 1 domains invalid!
      Sample of invalid domains:
      - госуспуги.рф
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/blocklistproject/Lists/master/gambling.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 2479 domains
  [i] List stayed unchanged

  [i] Target: https://raw.githubusercontent.com/blocklistproject/Lists/master/piracy.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 2128 domains
  [i] List stayed unchanged
```

Regarding `госуспуги.рф` there already a PR #683 waiting to be merged (properly this weekend as @cryptogap wrote on Discord).

**Comment by thomasmerz** [comment]
BTW:
Did you know?
```
https://raw.githubusercontent.com/blocklistproject/Lists/master/ransomware.txt is already in dbl.oisd.nl
https://raw.githubusercontent.com/blocklistproject/Lists/master/porn.txt is already in dbl.oisd.nl
```
Have a look at https://oisd.nl/includedlists/

**Comment by dtavilez** [comment]
I got it figured out! Sorry for the inconvenience and appreciate the follow up's!

**Comment by thomasmerz** [comment]
So this issue is no issue any more and you'll close it?

**Comment by dtavilez** [comment]
It’s been closed.  From: thomasmerzSent: Wednesday, April 6, 2022 3:04 PMTo: blocklistproject/ListsCc: Duncan; MentionSubject: Re: [blocklistproject/Lists] Invalid Domains (Issue #712) So this issue is no issue any more and you'll close it?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
