### ISSUE TITLE
firebaseremoteconfig.googleapis.com

### ISSUE THREAD

**Issue by p1r473** [blocklistproject/Lists#72]
URL you wish to be removed: firebaseremoteconfig.googleapis.com

Why you believe this to be a false positive:
Firebase Remote Config is a cloud service that lets you change the behaviour and appearance of your app without requiring users to download an app update. It is not malicious not advertising.

List it is on: Ads

**Comment by srathbone** [comment]
Same as codepush.azurewebsites.net.

It's a domain used by developers to update apps, not an ad domain.

**Comment by gap579137** [comment]
This has been fixed, Thank you!
