### ISSUE TITLE
api.tiles.mapbox.com

### ISSUE THREAD

**Issue by srathbone** [blocklistproject/Lists#73]
URL you wish to be removed:

api.tiles.mapbox.com

Why you believe this to be a false positive:

This breaks websites/apps that use mapbox to display maps. I don't think this domain serves any adverts?

List it is on:

https://github.com/blocklistproject/Lists/blob/master/ads.txt

Other info you think we should know:

**Comment by gap579137** [comment]
This has been fixed, Thank you!
