### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by what-aboot** [blocklistproject/Lists#730]
URL you wish to be added: www.songlytics.net

Why you believe this should be added:
An offline music player on my phone is sending packets to a song choice analytics site which openly admits to tracking songs chosen by listeners (even if the music library used is a personal one, and the "share to cloud" options in settings are switched off) with the view to notifying Spotify to update playlists. Detail below.

Add to list:
I don't know what list this should be added to. 

Other info you think we should know:
On android I've used an offline music player (Rocket Music Player, JRT Studios) for years, to play a music library I have in my phone. The music on the phone are all rips of CDs I have purchased, a total of 89GB. I choose specifically not to use sites that track my listening choice because it is my business what I choose to listen to. Anyway, I have the philosophy that if it ain't broke don't fix it, so I have not updated that music player in over a year, but by an inadvertent finger slip last week it got updated. Immediately I saw Blokada reporting 3 connects to www.songlytics.net every minute while I was playing my library, and doing nothing else. On checking out the website www.songlytics.net the site owner freely admits that he is collecting data on what tracks are played - this despite the "share to cloud"options on my version of Rocket Player (JRT Studios) being set to Off. I sent him an email complaining that it violates my rights, to which he replied that he had sold the music player to mumastudios.com, but retained www.songlytics.net. I left a comment on Play Store objecting to this tracking, and mumastudios.com have asked that I communicate via email. The fact is my music library is my own, it is no one's business what I choose to play, how many times I play it, and at what hours I play it. I am a big data analyst by profession and I know very well how much meta data can be inferred from seemingly random source data combinations. I do not believe any software has the right to send packets to the mother ship about my behavior, hence I have Blokada on my phone, and pi-hole on my router.

**Comment by cryptogap** [comment]
This will be included in the next push
