### ISSUE TITLE
[Add request] typo in gambeling list

### ISSUE THREAD

**Issue by korkmazk** [blocklistproject/Lists#731]
URL you wish to be added:
staatsloterij.nederlandseloterij.nl

Why you believe this should be added:
Typo in list: statsloterij.nederlandseloterij.nl should be st**aa**tsloterij.nederlandseloterij.nl

Add to list:
staatsloterij.nederlandseloterij.nl

Other info you think we should know:
The list already contains this website, however with a typo so not being blocked.

**Comment by kevinholtkamp** [comment]
"Add to list" probably should be gambling.txt, right?
