### ISSUE TITLE
[Add request] Discord scam/phishing site

### ISSUE THREAD

**Issue by kevinholtkamp** [blocklistproject/Lists#733]
URL you wish to be added:
discorcl-nltro.xyz

Why you believe this should be added:
This is a scam site, luring in people by advertising free discord nitro

Add to list:
scam.txt / phishing.txt

Other info you think we should know:
A friend of mine got hacked and sent everyone a link to this website (discorcl-nltro.xyz/giftcode to be exact)

**Comment by cryptogap** [comment]
This will be included in the next push
