### ISSUE TITLE
[Remove Request] - 

### ISSUE THREAD

**Issue by vsabavat** [blocklistproject/Lists#740]
[i] Target: https://blocklistproject.github.io/Lists/phishing.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 190245 domains, 1 domains invalid!
      Sample of invalid domains:
      - госуспуги.рф

**Comment by thomasmerz** [comment]
@vsabavat PR #683 has already removed `госуспуги.рф`.

**Comment by thomasmerz** [comment]
@cryptogap But there still some fragments left in those files that should not be edited in any PR because they're managed by some GitHub Actions - please check this out: 
```
✔ ~/temp/PRs/Lists [master|✔]
22:35 $ ack госуспуги.рф
adguard/phishing-ags.txt
42818:||госуспуги.рф^

adguard/everything-ags.txt
398164:||госуспуги.рф^

alt-version/phishing-nl.txt
42818:госуспуги.рф

alt-version/everything-nl.txt
398164:госуспуги.рф

dnsmasq-version/phishing-dnsmasq.txt
42818:server=/госуспуги.рф/

dnsmasq-version/everything-dnsmasq.txt
398164:server=/госуспуги.рф/

everything.txt
398164:0.0.0.0 госуспуги.рф
🦎🖥  ✔ ~/temp/PRs/Lists [master|✔]
22:35 $
```

The root cause seems to be that the [CI job](https://github.com/blocklistproject/Lists/actions/runs/2271917648) is failing due to:
```
fatal: not in a git directory
```

**Comment by techroy23** [comment]
[i] Target: https://blocklistproject.github.io/Lists/alt-version/phishing-nl.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 190245 domains, 1 domains invalid!
      Sample of invalid domains:
      - госуспуги.рф

**Comment by thomasmerz** [comment]
@techroy23 , please read my previous comment. This is a fragment being left over by a failing GitHub Action that should have removed this "invalid domain" from some more files in some more directories…
@cryptogap , can you please check [this failing CI job](https://github.com/blocklistproject/Lists/actions/runs/2271917648)? Thanks!

**Comment by blocklistproject** [comment]
This should be resolved
