### ISSUE TITLE
[Remove Request] - cdn.plyr.io

### ISSUE THREAD

**Issue by tobifroe** [blocklistproject/Lists#741]
URL you wish to be removed:
cdn.plyr.io

Why you believe this to be a false positive:
This CDN serves static files needed for [plyr](https://github.com/sampotts/plyr), breaking video playback (or rather layout, depending on the implementation) across multiple sites for me.

List it is on:
[ads.txt](https://github.com/blocklistproject/Lists/blob/master/ads.txt)

Other info you think we should know:

**Comment by blocklistproject** [comment]
This has been fixed
