### ISSUE TITLE
[Remove Request] - eu-auth2.samsungosp.com

### ISSUE THREAD

**Issue by mastermc0** [blocklistproject/Lists#742]
URL you wish to be removed:

eu-auth2.samsungosp.com

Why you believe this to be a false positive:

Appears to be used to authenticate Samsumg smart home services.

List it is on:

https://blocklistproject.github.io/Lists/smart-tv.txt

Other info you think we should know:

**Comment by blocklistproject** [comment]
Recommend WL if this services is needed.
