### ISSUE TITLE
[Remove Request] - ts.market.mi-img.com

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [blocklistproject/Lists#747]
URL you wish to be removed: 
`ts.market.mi-img.com`

Why you believe this to be a false positive:
It is required to save settings and download updates on some xiaomi products

List it is on:
Ads

Other info you think we should know:
https://blocklist-tools.developerdan.com/entries/search?q=ts.market.mi-img.com

**Comment by blocklistproject** [comment]
Moved to tracking
