### ISSUE TITLE
[Add request] Add Banload ransomware to list Ransomware

### ISSUE THREAD

**Issue by JuanRodenas** [blocklistproject/Lists#752]
URL you would like to see added:
.jdhhuf.es
.uddhkdlp.es
104.21.91.56
172.67.167.81
31.184.204/24

Why you think it should be added:
- Banload banking ransomware

Add to list:
- /Lists/master/ransomware.txt

Other information you think we should know:

**Comment by cryptogap** [comment]
Sites have been taken down
