### ISSUE TITLE
false positive blog.libero.it

### ISSUE THREAD

**Issue by stefanostatuti** [blocklistproject/Lists#76]
URL you wish to be removed:
https://blog.libero.it/

Why you believe this to be a false positive:
this websites offers a news page, mostly of these news are for italian people (gossip for example)

List it is on:
https://blocklistproject.github.io/Lists/malware.txt

Other info you think we should know:
libero was an italian ISP , https://it.wikipedia.org/wiki/Libero_(portale)

**Comment by gap579137** [comment]
This has been fixed, Thank you!
