### ISSUE TITLE
Crypto Scam Websites for Mina Protocol

### ISSUE THREAD

**Issue by Makalfo** [blocklistproject/Lists#769]
URL you wish to be added:
https://mlnaprolocol.com/
rewardmina.com

Why you believe this should be added:
The website is a spoof of the following website in an attempt to scam:
https://minaprotocol.com/

rewardmina.com redirects to the scam website above.

Add to list:
crypto.txt

Other info you think we should know:
Another website to consider is https://mainnet.clori.io/ but it appears to be taken down. May be worth adding as well

**Comment by cryptogap** [comment]
This site is no longer online
