### ISSUE TITLE
[Remove Request] - wistia.com

### ISSUE THREAD

**Issue by Gitoffomalawn** [blocklistproject/Lists#773]
**URL you wish to be removed:**
`wistia.com`

**Why you believe this to be a false positive:**
In order to block tracking it is only necessary to block 2 subdomains: `*.distillery.wistia.com` and `*.pipedream.wistia.com`. Blocking the entire `wistia.com` domain breaks functionality for many websites for legitimate uses.

**List it is on:**
[Tracking List](https://raw.githubusercontent.com/blocklistproject/Lists/master/tracking.txt)

**Other info you think we should know:**
N/A

**Comment by spirillen** [comment]
Hey  @Gitoffomalawn is it possible you can bring some examples?

**Comment by blocklistproject** [comment]
This has been updated to reflect just the subdomains. Will research further.
