### ISSUE TITLE
[Remove Request] - mandrillapp.com

### ISSUE THREAD

**Issue by Gitoffomalawn** [blocklistproject/Lists#774]
**URL you wish to be removed:**
`mandrillapp.com`

**Why you believe this to be a false positive:**
This has many legitimate uses that are broken by this block.

**List it is on:**
[Tracking List](https://raw.githubusercontent.com/blocklistproject/Lists/master/tracking.txt)

**Other info you think we should know:**
Resubmitted from issue #770 due to missing labels and assignments.

**Comment by blocklistproject** [comment]
This application does indeed track and will be left on the list
