### ISSUE TITLE
[Remove Request] - Samsung update and internet check broken

### ISSUE THREAD

**Issue by mrkskwsnck** [blocklistproject/Lists#777]
URL you wish to be removed:

cdn.samsungcloudsolution.com

Why you believe this to be a false positive:

I need to whitelist the above mentioned URL so

- checking for internet connection and
- checking for new software update

(both through the TV on-screen menu) will work properly.

List it is on:

https://blocklistproject.github.io/Lists/smart-tv.txt

Other info you think we should know:

Tested with my Samsung Smart TV (UE48JS8590TXZG)

**Comment by blocklistproject** [comment]
Because the list is doing as expected this will not be removed. I recommend WL if you need this domain
