### ISSUE TITLE
[Remove Request] - photofairy.de

### ISSUE THREAD

**Issue by der-echte-paul** [blocklistproject/Lists#780]
URL you wish to be removed: photofairy.de

Why you believe this to be a false positive: It has been listet since initial commit. We recently started using the domain for our app https://photofairy.tuvsud.com/de/ (see https://apps.apple.com/de/app/photofairy-360/id1403807374 )

List it is on: phising.txt

Other info you think we should know:

**Comment by spirillen** [comment]
As it is listed on a Phishing list, I'll suggest there will be a followup on whether there still is phis bates like screeners, images, dumps etc,  maybe request a scan in at one of the following dedicated phishing projects

- https://github.com/mitchellkrogza/Phishing.Database
- https://github.com/mitchellkrogza/phishing

Ping @mitchellkrogza

**Comment by blocklistproject** [comment]
Please provide more details prior to removal and valid ownership. Closed until then
