### ISSUE TITLE
[Remove Request] - 34.75.2o2.lol as owned by KnowBe4 now

### ISSUE THREAD

**Issue by doomed099** [blocklistproject/Lists#781]
URL you wish to be removed:
34.75.2o2.lol

Why you believe this to be a false positive:
This is now owned by KnowBe4 a phishing training and simulation company. Blocking this disallows the simulated phishing.

List it is on:
adguard/abuse-ags.txt
109189:||34.75.2o2.lol^

adguard/malware-ags.txt
7554:||34.75.2o2.lol^

dnsmasq-version/abuse-dnsmasq.txt
109189:server=/34.75.2o2.lol/

dnsmasq-version/malware-dnsmasq.txt
7554:server=/34.75.2o2.lol/

alt-version/abuse-nl.txt
109189:34.75.2o2.lol

alt-version/malware-nl.txt
7554:34.75.2o2.lol

adguard/everything-ags.txt
815072:||34.75.2o2.lol^

abuse.txt
109188:0.0.0.0 34.75.2o2.lol

malware.txt
7554:0.0.0.0 34.75.2o2.lol

dnsmasq-version/everything-dnsmasq.txt
815072:server=/34.75.2o2.lol/

alt-version/everything-nl.txt
815072:34.75.2o2.lol

everything.txt
815072:0.0.0.0 34.75.2o2.lol

Other info you think we should know:

**Comment by blocklistproject** [comment]
If you can please provide valid ownership we will remove. Closing until then
