### ISSUE TITLE
[Remove Request] - msftconnecttest.com

### ISSUE THREAD

**Issue by jhueppauff** [blocklistproject/Lists#783]
URL you wish to be removed:
www.msftconnecttest.com, ipv6.msftconnecttest.com

Why you believe this to be a false positive:
This is a hotspot test website which is used by Microsoft to detect if a network needs authentication (Open Hotspots, etc)

List it is on:
tracking-ags

Other info you think we should know:
I had a quick look at the list, and I can't spot anything with msftconnecttest.com in it. 
However it seems like adguard is blocking this based on this list:
![image](https://user-images.githubusercontent.com/20532954/180441270-235152e2-49eb-44db-84d8-eb41faf0d519.png)

**Comment by spirillen** [comment]
Because it is used for tracking your online activities, If you take a look into your network, you will notice it is pinging about once every seconds. The best you can do is to obfuscate the destination for the ping.

-- it's  keeper

**Comment by blocklistproject** [comment]
This is indeed a tracker. Will remain
