### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by ghost** [blocklistproject/Lists#784]
URL you wish to be added: shalltry.com

Why you believe this should be added: Tracking

Add to list: Tracking

Other info you think we should know:

**Comment by spirillen** [comment]
Don't you have any code pieces or logs of some kind that will demonstrate this.

PS: your url do not work for me

**Comment by spirillen** [comment]
Super, I have updated https://mypdns.org/my-privacy-dns/matrix/-/issues/983952
