### ISSUE TITLE
[Add request] api.mousegesturesapi.com

### ISSUE THREAD

**Issue by ALILEX-1** [blocklistproject/Lists#786]
URL you wish to be added:api.mousegesturesapi.com

Why you believe this should be added:tracking-ags

Add to list:tracking-ags.txt

Other info you think we should know:

**Comment by spirillen** [comment]
What does it do?

code snippets, explanations

**Comment by cryptogap** [comment]
This has been researched and show to be a tracking/information gathering API. It will be added to the tracking list in the next push
