### ISSUE TITLE
[Add request] api.miwifi.com

### ISSUE THREAD

**Issue by ALILEX-1** [blocklistproject/Lists#787]
URL you wish to be added:   api.miwifi.com

Why you believe this should be added: tracking-ags

Add to list: tracking-ags.txt

Other info you think we should know:

**Comment by spirillen** [comment]
proves/examples??

**Comment by cryptogap** [comment]
Please provide additional details

**Comment by cryptogap** [comment]
Closed without additional info. Please feel free to reopen with additional details. Thank you
