### ISSUE TITLE
[Add request] asus.router.com

### ISSUE THREAD

**Issue by aminnaggar** [blocklistproject/Lists#791]
URL you wish to be added:
asus.router.com

Why you believe this should be added:
It's a forwarder to multiple Scam / Phishing sites

Add to list:
Scam?

Other info you think we should know:

**Comment by spirillen** [comment]
Unable to connect

Firefox can’t establish a connection to the server at asus.router.com.

what is it you believes is showing up as phis

**Comment by spirillen** [comment]
Common domain-jacked by [parklogic.com](https://mypdns.org/my-privacy-dns/matrix/-/issues/2352)

```
drill asus.router.com -T
.       518400  IN      NS      a.root-servers.net.
com.    172800  IN      NS      m.gtld-servers.net.
router.com.     172800  IN      NS      ns1.ih120.parklogic.com.
router.com.     172800  IN      NS      ns2.ih120.parklogic.com.
asus.router.com.        1074    IN      A       69.16.231.56

```

New issue: https://mypdns.org/my-privacy-dns/matrix/-/issues/998753

**Comment by cryptogap** [comment]
Added with merge
