### ISSUE TITLE
[Remove Request] - https://fossbytes.com from Torrents

### ISSUE THREAD

**Issue by kbp80** [blocklistproject/Lists#792]
URL you wish to be removed: https://fossbytes.com 

Why you believe this to be a false positive: This is a tech blogging site that ostensibly discusses FOSS but is general tech news. 

List it is on: Torrent

Other info you think we should know: They have posted a handful of how-to articles over the past six months about torrenting services which may have gotten them flagged.

**Comment by blocklistproject** [comment]
This should be fixed
