### ISSUE TITLE
[Remove Request] - госуспуги.рф

### ISSUE THREAD

**Issue by Nabhan87** [blocklistproject/Lists#798]
[i] Target: https://blocklistproject.github.io/Lists/alt-version/phishing-nl.txt
[✓] Status: No changes detected
[i] Analyzed 190245 domains, 1 domains invalid!
Sample of invalid domains:
- госуспуги.рф

**Comment by spirillen** [comment]
There should for real be a IDNA converter while importing from unreliable sources

Here is the converted version, thanks to PyFunceble

`xn--c1aapwflapc.xn--p1ai`

**Comment by thomasmerz** [comment]
See Issue #628 and PR #683 …

**Comment by thomasmerz** [comment]
See this:
https://github.com/blocklistproject/Lists/issues/740#issuecomment-1117893190

This issue can be closed due to "duplicate" of https://github.com/blocklistproject/Lists/issues/740 @cryptogap , @fishcharlie !?
