### ISSUE TITLE
web.whatsapp.com

### ISSUE THREAD

**Issue by brunovms** [blocklistproject/Lists#80]
URL you wish to be removed: web.whatsapp.com

Why you believe this to be a false positive: It's WhatsApp Web Service, used to mirror the messaging platform in a PC.

List it is on: Abuse, Fraud.

Other info you think we should know:

**Comment by gap579137** [comment]
I am not finding these on the lists you specified. Am I just missing it??

**Comment by brunovms** [comment]
Don't know what changed, but from when I opened the issue to today, the lists seem to have changed. Now it`s in 'ads'

`pihole -q web.whatsapp.com
 Match found in exact whitelist
   web.whatsapp.com (disabled)
 Match found in regex whitelist
   ^.+\.whatsapp\.com$
 Match found in https://blocklistproject.github.io/Lists/ads.txt:
   dev-web.whatsapp.com
   dyn.web.whatsapp.com
   up.web.whatsapp.com
   w1.web.whatsapp.com
   w2.web.whatsapp.com
   w3.web.whatsapp.com
   w4.web.whatsapp.com
   w5.web.whatsapp.com
   w6.web.whatsapp.com
   w7.web.whatsapp.com
   w8.web.whatsapp.com
   w9.web.whatsapp.com
   web.whatsapp.com`
