### ISSUE TITLE
[Remove Request] - circularhub.com api.flipp.com

### ISSUE THREAD

**Issue by ddxtanx** [blocklistproject/Lists#802]
URL you wish to be removed:
circularhub.com and api.flipp.com

Why you believe this to be a false positive:
These links are used to serve the 'Weekly Ads' section on the Jewel Osco Grocery mobile app. This section provides users with deals on grocery items, which is quite useful for money saving.

List it is on:
abuse and ads

Other info you think we should know:

**Comment by blocklistproject** [comment]
These are still ads. I recommend WL these if you would like to see them
