### ISSUE TITLE
[Remove Request] - js.sentry-cdn.com

### ISSUE THREAD

**Issue by gyCfjSnO** [blocklistproject/Lists#808]
URL you wish to be removed: js.sentry-cdn.com

Why you believe this to be a false positive: When ```js.sentry-cdn.com``` is blocked it breaks ```https://www.pizzahut.com.au/``` can't put store information or address in etc. Unblocking ```js.sentry-cdn.com``` allows for postcode/address to be put in to set delivery or pickup of pizza.

List it is on: Ads

Other info you think we should know:

**Comment by blocklistproject** [comment]
This has been fixed
