### ISSUE TITLE
[Remove Request] - www.foundation-alliance.com

### ISSUE THREAD

**Issue by tan0407** [blocklistproject/Lists#809]
URL you wish to be removed:
- www.foundation-alliance.com

Why you believe this to be a false positive:
The foundation-alliance.com is a legitimate website owned by the construction company VINCI. We monitor this domain and we don't see any evidence of sending phishing.

List it is on:
- phishing.txt Line 138307: 0.0.0.0 www.foundation-alliance.com

- everything.txt Line 493590: 0.0.0.0 www.foundation-alliance.com

- dnsmasq-version\phishing-dnsmasq.txt Line 138310: server=/www.foundation-alliance.com/

- alt-version\phishing-nl.txt Line 138310: www.foundation-alliance.com

- adguard\phishing-ags.txt Line 138310: ||www.foundation-alliance.com^

- dnsmasq-version\everything-dnsmasq.txt Line 493590: server=/www.foundation-alliance.com/

- alt-version\everything-nl.txt Line 493590: www.foundation-alliance.com

- adguard\everything-ags.txt Line 493590: ||www.foundation-alliance.com^

Other info you think we should know:

**Comment by AlexanderBeng** [comment]
This website is clean without malicious file.
Kindly remove it from blacklist.

You can refer to this link:
https://sitecheck.sucuri.net/results/foundation-alliance.com
![Screenshot 2022-10-13 092500](https://user-images.githubusercontent.com/115676288/195478376-216b7c58-52e4-49ee-8d57-c364d82b4317.png)

**Comment by blocklistproject** [comment]
This has been fixed
