### ISSUE TITLE
[Remove Request] - ns1.com

### ISSUE THREAD

**Issue by RooneyMcNibNug** [blocklistproject/Lists#810]
URL you wish to be removed:

    ns1.com

Why you believe this to be a false positive:
NS1 is a legitimate company managing DNS Services for several businesses across the globe. This being blocked could cause a lot of people using your lists to not be able to access critical resources.

List it is on:

    alt-version/abuse-nl.txt line 372434 - ns1.com

    alt-version/malware-nl.txt line 187068 - ns1.com

Other info you think we should know:

**Comment by cryptogap** [comment]
This has been resolved
