### ISSUE TITLE
[Remove Request] - api.crowdin.com

### ISSUE THREAD

**Issue by fishcharlie** [blocklistproject/Lists#813]
URL you wish to be removed:

```
api.crowdin.com
```

Why you believe this to be a false positive:

Has nothing to do with ads

List it is on:

Ads

Other info you think we should know:

**Comment by spirillen** [comment]
That is not something I would go easy on... at least ensure it get a place on the tracking list

https://mypdns.org/my-privacy-dns/matrix/-/issues/983973

**Comment by blocklistproject** [comment]
This has been moved to tracking
