### ISSUE TITLE
whatsapp.com

### ISSUE THREAD

**Issue by brunovms** [blocklistproject/Lists#82]
URL you wish to be removed: whatsapp.com

Why you believe this to be a false positive: WhatsApp Frontpage

List it is on: Abuse

Other info you think we should know: There are other WhatsApp related subdomains being blocked, that stops media sharing inside the app.

**Comment by gap579137** [comment]
Unable to locate whatsapp.com on this list. We have 16 fake whatsapp domains on the lists but not actually whatsapp.com
