### ISSUE TITLE
[Add request] huawei Tracking domains

### ISSUE THREAD

**Issue by z3r0c0nf1gs** [blocklistproject/Lists#820]
URL you wish to be added:
metrics.data.hicloud.com
metrics1.data.hicloud.com
metrics2.data.hicloud.com
metrics3.data.hicloud.com
metrics4.data.hicloud.com
metrics5.data.hicloud.com 
logservice.hicloud.com
logservice1.hicloud.com
metrics-dra.dt.hicloud.com
logbak.hicloud.com

Why you believe this should be added:
This Domain is used by huawei.com for tracking.
Add to list:
https://blocklistproject.github.io/Lists/tracking.txt

Other info you think we should know:
This Domain is used by huawei.com for tracking.

**Comment by spirillen** [comment]
Do you have any links or other data that can backup this statement? logs, docs anything that proves this?

**Comment by z3r0c0nf1gs** [comment]
@spirillen  https://d3ward.github.io/toolz/adblock.html

**Comment by spirillen** [comment]
that  i just a page with no data
