### ISSUE TITLE
[Add request] Samsung Ads

### ISSUE THREAD

**Issue by z3r0c0nf1gs** [blocklistproject/Lists#821]
URL you wish to be added:
ad.samsungadhub.com
samsungadhub.com
samsungads.com
config.samsungads.com

Why you believe this should be added:
Samsung Ads domain

Add to list:
https://blocklistproject.github.io/Lists/ads.txt

Other info you think we should know:

**Comment by spirillen** [comment]
You should remember to write that blacklisting `config.samsungads.com` might brake unsmart TV features
Sourced from:

- https://mypdns.org/my-privacy-dns/matrix/-/issues/1734
- https://mypdns.org/my-privacy-dns/matrix/-/issues/1831
- https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Samsung-AdBlock.txt
