### ISSUE TITLE
[Add request] Samsung Tracking

### ISSUE THREAD

**Issue by z3r0c0nf1gs** [blocklistproject/Lists#822]
URL you wish to be added:
smetrics.samsung.com
nmetrics.samsung.com
samsung-com.112.2o7.net
business.samsungusa.com
analytics.samsungknox.com
bigdata.ssp.samsung.com
analytics-api.samsunghealthcn.com

Why you believe this should be added:
Samsung Tracking domains

Add to list:
https://blocklistproject.github.io/Lists/tracking.txt

Other info you think we should know:
Samsung Tracking domains

**Comment by spirillen** [comment]
Do you have any links or other data that can backup this statement? logs, docs anything that proves this?

Related own notes:

- `samsung.com` https://mypdns.org/my-privacy-dns/matrix/-/issues/1833
- `2o7.net` https://mypdns.org/my-privacy-dns/matrix/-/issues/965686
- `samsungusa.com` https://mypdns.org/my-privacy-dns/matrix/-/issues/1167631
-  `samsunghealthcn.com` https://mypdns.org/my-privacy-dns/matrix/-/issues/1168826 (All credit to @z3r0c0nf1gs)
- `samsungknox.com` https://mypdns.org/my-privacy-dns/matrix/-/issues/1167623 (All credit to @z3r0c0nf1gs)

**Comment by z3r0c0nf1gs** [comment]
@spirillen https://d3ward.github.io/toolz/adblock.html
