### ISSUE TITLE
[Remove Request] - cdn2.hubspot.net

### ISSUE THREAD

**Issue by Marcus1Pierce** [blocklistproject/Lists#826]
URL you wish to be removed: cdn2.hubspot.net

Why you believe this to be a false positive: when I access https://support.anydesk.com, it ruined the entire website.

List it is on: phishing-ags.txt

Other info you think we should know: Maybe you can access https://support.anydesk.com first to check.

**Comment by blocklistproject** [comment]
This has been fixed
