### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by ghost** [blocklistproject/Lists#827]
URL you wish to be added:
toolmatrix.plus
transacme.com
api.eagllwin.com
gamegamb.com
clog.geniex.com
api.ahagamecenter.com
irl-api.twibida.com
restart-api.palmplaystore.com
hippoobox.com
minigame.vip
mini6g.com 
Why you believe this should be added:
These domains are similar to shalltry.com
Add to list:
Tracking + Ads
Other info you think we should know:
![Screenshot_20220919-173414.jpg](https://user-images.githubusercontent.com/109208335/191412953-3fa02a35-3bcd-4c95-8a9f-4349b8996a44.jpg)
![Screenshot_20220919-173520.jpg](https://user-images.githubusercontent.com/109208335/191412980-9d3b4063-57e9-4a7c-9d4a-f77d6b430f82.jpg)
(To recreate: Install XOS Launcher and open the apps drawer)

Also, these are also blocked on 1Hosts

**Comment by spirillen** [comment]
Just to be sure, where did you find these records and there categorizing??

If you found them on https://mypdns.org/, which you are permitted to for not for profit OSS project, you still have to link to out [license](https://mypdns.org/my-privacy-dns/matrix/-/blob/master/source/LICENSE) and where you found them.

**Comment by cryptogap** [comment]
These have been added and will be included in the next push
