### ISSUE TITLE
trace.svc.ui.com

### ISSUE THREAD

**Issue by Wxfisch** [blocklistproject/Lists#83]
URL you wish to be removed: trace.svc.ui.com

Why you believe this to be a false positive: device crash reports for Ubiquiti network equipment, is not an advertising domain. 

List it is on: ads

Other info you think we should know: This domain is reached out to from equipment if a specific configuration option is enabled. It is not advertising related but may fit into the tracking list.

**Comment by gap579137** [comment]
Fixed. Thank you
