### ISSUE TITLE
Master lists not synchronize with adguard lists

### ISSUE THREAD

**Issue by Marcus1Pierce** [blocklistproject/Lists#832]
It seems the block lists from the master lists (All lists from https://github.com/blocklistproject/Lists) is not syncing with the adguard lists (https://github.com/blocklistproject/Lists/tree/master/adguard)

**Comment by Satellite-Galaxy** [comment]
Appears to be fixed now.

**Comment by thomasmerz** [comment]
@cryptogap can you please close this issue?

**Comment by Marcus1Pierce** [comment]
It fixed now.
