### ISSUE TITLE
[Remove Request] - false positive for c2ctrees.com

### ISSUE THREAD

**Issue by ebelliveau** [blocklistproject/Lists#835]
URL you wish to be removed: 
* c2ctrees.com

Why you believe this to be a false positive:
* I work here and we sell trees for reforestation efforts.  No ill intent or malware being distributed behind this domain whatsoever.

List it is on:
* abuse.txt, line 27834 (as of current HEAD)

Other info you think we should know:
* Keep up the great work!  I use these lists everywhere I run a caching DNS server.

**Comment by cryptogap** [comment]
This has been removed
