### ISSUE TITLE
[Remove Request] - www.tdameritrade.com

### ISSUE THREAD

**Issue by kevinh-csalabs** [blocklistproject/Lists#839]
URL you wish to be removed:
www.tdameritrade.com

Why you believe this to be a false positive:
This is a standard stock market trading site not aimed specifically at crypto. This seems to be a questionable inclusion at best - by the same argument almost the entire financial industry should be blocked such as other stock trading sites and many banks. For example: etrade, ally, etc

List it is on:
crypto

Other info you think we should know:
Included per request: https://github.com/blocklistproject/Lists/issues/542
Commit: https://github.com/blocklistproject/Lists/commit/f222cb09df4bb8ba24ab999388bbb1cae0bb420b

**Comment by ebelliveau** [comment]
responses delivered to tdameritrade.com can absolutely access undocumented APIs and deliver arbitrary information to a blackboxed bank.

I say we leave this until someone at TD complains that they aren't getting the analytics they're used to.

**Comment by kevinh-csalabs** [comment]
@ebelliveau what does analytics have to do with the crypto blocklist? Do you have some evidence of them misusing their apis or their domain for nefarious crypto mining or is that just speculation?

**Comment by ebelliveau** [comment]
Even worse: it's blind speculation haha.  I didn't notice the list it was on - don't mind me.

**Comment by cryptogap** [comment]
This has been removed
