### ISSUE TITLE
[Remove Request] - metricool.com

### ISSUE THREAD

**Issue by mcprol** [blocklistproject/Lists#843]
URL you wish to be removed:
metricool.com

Why you believe this to be a false positive:
Metricool is a social media tool and in no way should it be considered used for 'advertisements'.
Some customers are complaining that their ad blocker is denying them access to *.metricool.com

List it is on:
ads.txt
everything.txt
adguard/ads-ags.txt
adguard/everything-ags.txt
alt-version/ads-nl.txt
alt-version/everything-nl.txt
dnsmasq-version/ads-dnsmasq.txt
dnsmasq-version/everything-dnsmasq.txt

Other info you think we should know:

**Comment by cryptogap** [comment]
This has been removed
