### ISSUE TITLE
[Remove Request] - cloudinary

### ISSUE THREAD

**Issue by daniel-thisnow** [blocklistproject/Lists#846]
URL you wish to be removed:
cloudinary.com

Why you believe this to be a false positive:
its a dynamic image serving asset management tool

List it is on:
https://blocklistproject.github.io/Lists/ads.txt:
  dualstack.cloudinary.com

Other info you think we should know:
Their interface is broken for me now - would also brake images in websites

**Comment by cryptogap** [comment]
This has been removed
