### ISSUE TITLE
[Add request] - toutiao

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [blocklistproject/Lists#847]
URL you wish to be added:

```
log-api.pangolin-sdk-toutiao-b.com
p6-be-pack-sign.pglstatp-toutiao.com
p3-be-pack-sign.pglstatp-toutiao.com
```

Why you believe this should be added:
The first one is logging
The second and third ones are ads

Add to list:
Ads

Other info you think we should know:
From what I can see, the number seems to be changing. I suppose the second and third are CDN servers. Maybe block the whole domain? or block p1 p2 all the way to p9?

**Comment by spirillen** [comment]
Nice you like to report, is there a fair change you can bag this up with some logs of where you have found this, for other to confirm/duplicating your observation?

**Comment by SodaWithoutSparkles** [comment]
https://blocklist-tools.developerdan.com/entries/search?q=p9-be-pack-sign.pglstatp-toutiao.com

Seen in this app: https://play.google.com/store/apps/details?id=make.more.r2d2.cellular_z

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

- pglstatp-toutiao.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/4438082
- pangolin-sdk-toutiao-b.com: https://mypdns.org/my-privacy-dns/matrix/-/issues/4438077

</details>
