### ISSUE TITLE
A lot of FP in gambling

### ISSUE THREAD

**Issue by Homas** [blocklistproject/Lists#85]
Looks like the gambling list contains a lot of FP (non gambling sites). I'm using notracking feeds (https://github.com/notracking/hosts-blocklists) and found 35% (20799 entries) overlap between gambling and the notracking lists. I'm using the notracking lists more than 1.5 years and their quality is pretty good.

```
sort gambling_hosts.txt nt_hostnames_uniq.txt nt_domains_uniq.txt| awk 'dup[$0]++ == 1' | wc -l  
20799  

wc -l gambling_hosts.txt  
58600 gambling_hosts.txt
```

For example dropbox.com, office.com, responsys.net are included into the gambling feeds.

URL you wish to be removed:
```
telemetry.dropbox.com  
measure.office.com
mi.dickssportinggoods.com   
static.cdn.responsys.net
```

and please take a look on other 20k entries which are listed in the notracking feeds.

Why you believe this to be a false positive:
The mentioned sites are not gambling.

List it is on:
Gambling

Other info you think we should know:
There is 10k overlap between abuse and gambling feeds. It seems too high even some sites may be included into multiple categories.

```
sort abuse_hosts.txt gambling_hosts.txt| awk 'dup[$0]++ == 1' | wc -l   
10227
```

There is also 30k overlap between the abuse and notracking feeds but likely it is Ok because the notracking feeds also block some other trash.
```
sort abuse_hosts.txt nt_hostnames_uniq.txt nt_domains_uniq.txt| awk 'dup[$0]++ == 1' | wc -l  
30313
```

**Comment by gap579137** [comment]
Reviewing

**Comment by gap579137** [comment]
We have reworked the gambling list. See if that works better.
