### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by PJGitHub9** [blocklistproject/Lists#853]
URL you wish to be added: https://github.com/PJGitHub9/PJsAdobeBlocklist (the txt file)

Why you believe this should be added:

Im surprised one isn't easy to find. I put together an adobe block section that might be better to hand off to you guys if you want to add an Adobe section.
They have documentation on what links they require to be open for their program to work:
https://helpx.adobe.com/ca/enterprise/kb/network-endpoints.html

Add to list: 

Other info you think we should know: This would be a solid section to add to block the majority of adobe domains

**Comment by Satellite-Galaxy** [comment]
I would say since you already made the list to make a PR adding it.

**Comment by PJGitHub9** [comment]
> I would say since you already made the list to make a PR adding it.

Not used to github but will try!

**Comment by thomasmerz** [comment]
@PJGitHub9 , I made PR #880 for your convenience. Please have a look at it!
