### ISSUE TITLE
[Add request] - BPER bank SMS phishing domains

### ISSUE THREAD

**Issue by Trainax** [blocklistproject/Lists#855]
URL you wish to be added:

- `https://accesso-restrizione.com`
- `https://kiawu.com` (same sms with different domain) [urlscan.io proof](https://urlscan.io/result/5eb58946-5195-406d-9f39-61c176abc175/)
- `https://area-identificazione.com`

Why you believe this should be added: Phishing attempt. I received an SMS (see screenshot) in which they pretended to be BPER (an Italian bank).

Add to list: `Phishing.txt`

Other info you think we should know:

![immagine](https://user-images.githubusercontent.com/30187360/201995140-7e9bb2c8-31e9-483b-b3fa-5e611228292d.png)

**Translation**

> Dear customer, your BPER app is connected to a new device from Lugano. If it's not you, block it at the following link: `link`

![immagine](https://user-images.githubusercontent.com/30187360/202718036-fe9f2427-9c14-4f88-a1e1-ef3e476a6dd4.jpg)

**Comment by Satellite-Galaxy** [comment]
All sites are down.

**Comment by Trainax** [comment]
> All sites are down.

Ok. Closing this issue. Probably those sites have gone down in the meantime
