### ISSUE TITLE
[Remove Request] - nfltags.com

### ISSUE THREAD

**Issue by spreiter** [blocklistproject/Lists#856]
URL you wish to be removed: nfltags.com

Why you believe this to be a false positive: Watch via NFL gamepass is not possible

List it is on: `tracking.txt`

Other info you think we should know:
Tested via PiHole, as soon as this page is included in whitelist, watch works as expected.

During watch, `p.nfltags.com` is used. I am not sure about other sub domains.

**Comment by cryptogap** [comment]
This has been removed
