### ISSUE TITLE
[Add request] costoc.ca

### ISSUE THREAD

**Issue by aminnaggar** [blocklistproject/Lists#857]
URL you wish to be added: http://costoc.ca

Why you believe this should be added:
Phishing website. common "Costco" typo

Add to list:
Phishing maybe?

Other info you think we should know:

**Comment by Satellite-Galaxy** [comment]
Seems to be a redirect.

@blocklistproject

**Comment by cryptogap** [comment]
This has been added to redirect and will be included in the next push

**Comment by spirillen** [comment]
Do not redirect, it returns 404

![image](https://user-images.githubusercontent.com/44526987/235463711-928be9f4-9722-4e19-868a-baf306bc2d63.png)

**Comment by aminnaggar** [comment]
must have taken it down then. Thanks
