### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by MrNobody334** [blocklistproject/Lists#859]
URL you wish to be added: surveyonline.top, www.mysexymatches.com, wwww.travelparked.com, https-www.store, www.remembergirl.com, flyingadvert.com, booptuwa.net, chaturbate.com, psoalreh.com

Why you believe this should be added: all the above are redirecting to useless sites and some of them are stupid adult games.

Add to list: Redirect

Other info you think we should know: Thanks for doing these kind of stuff for us. much love. My first time of doing this add request. So If anything went wrong, i'm very sorry...
thanks

**Comment by Satellite-Galaxy** [comment]
Looks like `travelparked.com`, and `https-www.store` are redirects. The rest are either down or not redirects.

**Comment by blocklistproject** [comment]
These two have been added
