### ISSUE TITLE
dickssportinggoods.com, metrics.dickssportinggoods.com, metrics.delta.com are in the abuse list

### ISSUE THREAD

**Issue by Homas** [blocklistproject/Lists#86]
URL you wish to be removed:
dickssportinggoods.com, metrics.dickssportinggoods.com, metrics.delta.com

Why you believe this to be a false positive:
dickssportinggoods.com - shop
metrics.dickssportinggoods.com, metrics.delta.com - tracking

List it is on:
abuse

**Comment by gap579137** [comment]
This has been fixed. Thank you
