### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by nightznero** [blocklistproject/Lists#860]
Helloz!

Is there any,or could be created a list for most of "garbage" in the internet but rather than list "everything" should contain:
Abuse
Ads
Fraud
Malware
Phishing
Ransomware
Scam
Tracking(optional,depend how much its break stuffs)
This list would be the best for users that want to set up amd forget,like OISD. Could We get list like this please?

Best regards, NIGHTZNERO.

**Comment by thomasmerz** [comment]
Sorry, wrong PR linked to this issue. How can I unlink it?

**Comment by thomasmerz** [comment]
Why do you want to build a new oisd.nl list? If you like oisd.nl list, then why do you not use it? This is an addition to other lists… Or am I wrong @cryptogap ?

**Comment by cryptogap** [comment]
> Why do you want to build a new oisd.nl list? If you like oisd.nl list, then why do you not use it? This is an addition to other lists… Or am I wrong @cryptogap ?

You are correct the reason the lists were created the way they were is so that you can pick and choose the categories you would like to block. Making more and more combine lists defeats that goal. Unless provided with additional reason and reopened, this is closed.
