### ISSUE TITLE
[Remove Request] - www.danhinsley.com

### ISSUE THREAD

**Issue by danhi** [blocklistproject/Lists#861]
URL you wish to be removed:

www.danhinsley.com

Why you believe this to be a false positive:

Not sure why this was ever flagged.  It's just a standard website hosted via BlueHost.

**Comment by cryptogap** [comment]
Please provide the list this url is on

**Comment by danhi** [comment]
Lists your site appears in.
 - https://blocklistproject.github.io/Lists/malware.txt
 - https://blocklistproject.github.io/Lists/abuse.txt
 - https://blocklistproject.github.io/Lists/alt-version/malware-nl.txt

**Comment by thomasmerz** [comment]
I really can't find anything related to `danhinsley` in any of these lists or in this repo!?
It has already been removed via https://github.com/blocklistproject/Lists/issues/838 and https://github.com/blocklistproject/Lists/issues/841

@cryptogap , please close this issue.
