### ISSUE TITLE
opensubtitles.org found on 2 lists

### ISSUE THREAD

**Issue by clickwir** [blocklistproject/Lists#87]
URL you wish to be removed: opensubtitles.org and www.opensubtitles.org

Why you believe this to be a false positive: I've used this site before and I would not call it malware or abusive.

List it is on:
https://github.com/blocklistproject/Lists/raw/master/abuse.txt 
https://github.com/blocklistproject/Lists/raw/master/malware.txt

Other info you think we should know:

**Comment by gap579137** [comment]
This has been fixed. Thank you for letting us know.
