### ISSUE TITLE
DNS Firewall/RPZ feeds

### ISSUE THREAD

**Issue by Homas** [blocklistproject/Lists#88]
Just FYI
On my ioc2rpz community website (https://ioc2rpz.net) I've created 2 DNS Firewall/RPZ feeds based on your lists:
- adultfree.ioc2rpz based is on abuse, drugs, gambling lists;
- blocklist-malicious.ioc2rpz is based on fraud, malware, phishing, ransomware, scam lists.

RPZ feeds can be used with open source ISC Bind, PowerDNS or commercial (Infoblox, Blue Cat, Akamai AnswerX) DNS DNS servers.

If you have any questions or concerns please let me know.

**Comment by gap579137** [comment]
That's great! Thank you for letting us know. Looks like a very interesting site and project. Please keep us updated.
