### ISSUE TITLE
[Add request] - Fake Italian Postal Service SMS

### ISSUE THREAD

**Issue by Trainax** [blocklistproject/Lists#885]
URL you wish to be added: `igiz.info`

Why you believe this should be added: I have received a fake SMS saying they attempted to deliver my order and I wasn't home and to click on a link to reschedule the delivery

Add to list: `phishing.txt`

Other info you think we should know:

![immagine](https://user-images.githubusercontent.com/30187360/208462391-d9a918e7-f8d2-4599-bae5-70911fc43d25.png)

**Translation:**
> We attempted to deliver your order *number* today 19/12/22. Since nobody was home, you have to reschedule it here *link*

**Comment by cryptogap** [comment]
This has been added and will be included in the next push.
