### ISSUE TITLE
[Remove Request] - TorrentFreak

### ISSUE THREAD

**Issue by toastloop** [blocklistproject/Lists#886]
URL you wish to be removed: torrentfreak.com

Why you believe this to be a false positive: It is a news website covering stories pertaining to copyright, piracy, the internet,  and litigation. Does not contain any pirated content or instructions on how to pirate content.

List it is on: torrent.txt

Other info you think we should know:

**Comment by cryptogap** [comment]
This has been fixed and will be updated in the next push
