### ISSUE TITLE
[Add request] Scam + Fraud site

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#890]
URL you wish to be added:
`http://kyrycp.online.dream.website/`
Why you believe this should be added:
Scam : NetBanking
Add to list:
Scam
Other info you think we should know:

Archive Link if this link gets removed: [here](https://web.archive.org/web/20221228070122/http://kyrycp.online.dream.website/)

**Comment by alanjacobmathew** [comment]
New LInk: `http://ranikopenbar.online.dream.website/cft/`
archive link: [here](https://web.archive.org/web/20230105123423/http://ranikopenbar.online.dream.website/cft/)

**Comment by cryptogap** [comment]
This has been added in the next push.
