### ISSUE TITLE
Badly formatted lines in output lists

### ISSUE THREAD

**Issue by moviuro** [blocklistproject/Lists#894]
porn.txt contains `/` in domain names; this should never happen:

```
0.0.0.0 www.familysexvideos.pro/en/
0.0.0.0 familysexvideos.pro/en/
0.0.0.0 lusthive.com/tym
0.0.0.0 promo.foxes.com/pics/
```

Solutions:

* Reject "domains" with a `/` char
* Discard the end of the line (`/.*`)

**Comment by cryptogap** [comment]
This has been fixed and will be updated in the next push
