### ISSUE TITLE
[Remove Request] - iubenda.com

### ISSUE THREAD

**Issue by accountiub** [blocklistproject/Lists#895]
URL you wish to be removed: iubenda.com and related (I have found 5 entries in your blacklist when filtering "iubenda"

Why you believe this to be a false positive:  iubenda provides software solutions for legal compliance of websites and apps: our products are Privacy and Cookie Policy, Terms and Conditions, Privacy Controls and Cookie Solution to name a few. We do not track any user information, other than the consent level of the person who has agreed to that.

List it is on: Block List Project: Ads

Other info you think we should know:

**Comment by accountiub** [comment]
List it is on: Malware

**Comment by cryptogap** [comment]
This has been fixed and will be included in the next push
