### ISSUE TITLE
[Add request] Redirectors

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#896]
URL you wish to be added:
```
k8i.cc
2fr.cc
9k.gg
```

Why you believe this should be added:
Redirector
Possibly belongs to `https://www.heymarket.com/`

Add to list:
Redirector/ Tracking

Other info you think we should know:
2fr.cc/p/kim0AINC
k8i.cc/p/jGr807Et
9k.gg/zjv6t

**Comment by cryptogap** [comment]
These have been added and will be included in the next push
