### ISSUE TITLE
Empty folders

### ISSUE THREAD

**Issue by p1r473** [blocklistproject/Lists#9]
Hi,
Some of the folders on the main site are empty
So the links on the main site won't redirect
https://blocklist.site/app/dl/ransomeware/
https://blocklist.site/app/dl/spam/

etc.

**Comment by blocklistproject** [comment]
Ransomeware has been fixed. SPAM is likely not going to get recreated. See conversation here -> [https://www.reddit.com/r/blocklistproject/comments/h7tqmf/moving_to_git_now_which_one/](https://www.reddit.com/r/blocklistproject/comments/h7tqmf/moving_to_git_now_which_one/)
