### ISSUE TITLE
[Remove Request] - IQ Credit Union is Blocked

### ISSUE THREAD

**Issue by ElectroVer** [blocklistproject/Lists#902]
URL you wish to be removed:
iqcu.com

Why you believe this to be a false positive:
This is a legitimate financial institution. 

List it is on:
Tracking List (NL)

Other info you think we should know:
It appears one of the blocked URLs ends up inadvertently blocking iqcu.com.

**Comment by cryptogap** [comment]
I don't find this on our lists. Are you sure...

**Comment by cryptogap** [comment]
Did not mean to close

**Comment by ElectroVer** [comment]
> I don't find this on our lists. Are you sure...
I ruIed out the possibility that it could be another list. Only happens when I have the tracker list enabled.
It might be an issue with the site itself relying on a blocked url seeing as it's not on the list..

**Comment by cryptogap** [comment]
![Screenshot_20230109_084303](https://user-images.githubusercontent.com/30596626/211334767-7ebad044-5bf9-42fb-8124-c7317be8f00c.png)

Have you tried updating your lists?

**Comment by cryptogap** [comment]
This will be closed. Please feel free to reopen if you have any additional issues pertaining to this.
