### ISSUE TITLE
[Add request] dkb-de.online & sparkassse.safecheck22.com.de -> phishing

### ISSUE THREAD

**Issue by Metrax** [blocklistproject/Lists#905]
URL you wish to be added:
dkb-de.online
sparkassse.safecheck22.com.de

Why you believe this should be added:
Both sites are send by e-mail and SMS, trying to phish bank account logins from German banks

Add to list:
phishing

Other info you think we should know:

**Comment by cryptogap** [comment]
These has been added to redirect as that is currently what the URLs do.
