### ISSUE TITLE
[Remove Request] - 

### ISSUE THREAD

**Issue by dohabandit** [blocklistproject/Lists#908]
URL you wish to be removed:
valkyrie.comodo.com

Why you believe this to be a false positive:
valkyrie is a file hash reputation service used by the Comodo endpoint Anti Virus software client. It isn't malicious, it is used in similar fashion to virustotal to determine if a file or process has a malicious reputation.

List it is on:
Adult/Porn

Other info you think we should know:
ioc2rpz is pulling this from blocklistproject, I am not sure the specific list here that has the false positive.

**Comment by cryptogap** [comment]
This has been addressed and will be included in the next push
