### ISSUE TITLE
[Add request] Redirector

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#909]
URL you wish to be added:
```
https://go.bundlebyte.net/r/f690bd169f996d379970b59438b696ab
```
Why you believe this should be added:
Redirector
Add to list:
redirect
Other info you think we should know:
Redirects to a torrent client. So may be add that too the list

**Comment by cryptogap** [comment]
We would have to block the entire site. Please provide support that the entire site should be added. Closed until then

**Comment by alanjacobmathew** [comment]
> We would have to block the entire site. Please provide support that the entire site should be added. Closed until then

@cryptogap The entire subdomain, [https://go.bundlebyte.net/r/f690bd169f996d379970b59438b696ab
](https://go.bundlebyte.net/r/f690bd169f996d379970b59438b696ab) is used as a redirector domain. It's already being blocked in uBlock defualt filter lists
