### ISSUE TITLE
Multiple porn sites in ads list

### ISSUE THREAD

**Issue by kollege-anonym** [blocklistproject/Lists#91]
URL you wish to be removed:
- redtube.com
- youporn.com
- tube8.com

Why you believe this to be a false positive:
These belong on the porn list, not on the ads list, because they are porn streaming platforms.

List it is on:
ads

Other info you think we should know:
Those are the three I recognized, there could be more, if there are three already.

**Comment by gap579137** [comment]
This has been fixed. Thank you
