### ISSUE TITLE
[Add request] Torrent

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#910]
URL you wish to be added:
```
https://getdstudio.cc/
```
Why you believe this should be added:
Site to download torrent client
Add to list:
torrent
Other info you think we should know:
archive: [here](https://web.archive.org/web/20230114062451/https://getdstudio.cc/)

**Comment by cryptogap** [comment]
This has been added

**Comment by spirillen** [comment]
![image](https://user-images.githubusercontent.com/44526987/234551786-ba4c280d-2b7e-4e8b-849f-b517bf812b82.png)
