### ISSUE TITLE
[Add request] Piracy

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#911]
URL you wish to be added:
```
https://1337x.unblockit.ink/
https://proxy-bay.ink/
https://pirate-proxy.ink/
https://piratenow.xyz/
https://tpb25.ukpass.co/
https://theproxybay.ga/
https://thepiratetorpia.xyz/
https://pirateproxy247.com/
https://pirateproxy.cfd/
https://tpb-proxy.xyz/
https://fightpirate.xyz/
https://piratebay.army/index.html
https://www.tpbproxy.xyz/
https://tpb-visit.me/
https://piratesbay.tk/
https://ww1.piratebayz.top/
https://tpb.skynetcloud.site/
https://ww1.piratebayz.top/
https://knaben.ru/thepiratebay
https://mirrorbay.top/

```
Why you believe this should be added:
Piracy
Add to list:
Piracy
Other info you think we should know:
All the links were alive when added

**Comment by cryptogap** [comment]
Please edit the urls to the correct format. Closed until edited

**Comment by alanjacobmathew** [comment]
@cryptogap Edited the links.

**Comment by spirillen** [comment]
The following records test reports can be found at My Privacy DNS:

<details><summary>Unfold to see links to all reports</summary>

| Record | Report |
| :--------- | ---------: |
| `piratenow.xyz` | My Privacy DNS report [20790](https://0xacab.org/my-privacy-dns/matrix/-/issues/20790) |
| `tpb25.ukpass.co` | My Privacy DNS report [19400](https://0xacab.org/my-privacy-dns/matrix/-/issues/19400) |
| `piratesbay.tk` | My Privacy DNS report [19276](https://0xacab.org/my-privacy-dns/matrix/-/issues/19276) |
| `pirate-proxy.ink` | https://0xacab.org/my-privacy-dns/matrix/-/issues/22353 |

Waiting In Line

```
1337x.unblockit.ink
proxy-bay.ink
theproxybay.ga
thepiratetorpia.xyz
pirateproxy.cfd
tpb-proxy.xyz
www.tpbproxy.xyz
tpb-visit.me
ww1.piratebayz.top
mirrorbay.top
```

Not Listed (Other reason)

```
pirateproxy247.com
fightpirate.xyz
tpb.skynetcloud.site
```

</details>
