### ISSUE TITLE
[Remove Request] Invalid domains

### ISSUE THREAD

**Issue by ndsvw** [blocklistproject/Lists#912]
URL you wish to be removed:

 - pmenboeqhyrpvomq.v
 - pmenboeqhyrpvomq.w

When I updated PiHole, it listed them as invalid domains:

>   [i] Target: https://blocklistproject.github.io/Lists/abuse.txt
>   [✓] Status: Retrieval successful
>   [i] Analyzed 435182 domains, 2 domains invalid!
>       Sample of invalid domains:
>       - pmenboeqhyrpvomq.v
>       - pmenboeqhyrpvomq.w
>

**Comment by pawcoding** [comment]
These two domains are also listed on the `malware` list. Of course, Pi-Hole issues the same error there.

**Comment by cryptogap** [comment]
Duplicate of #921
