### ISSUE TITLE
[Add request] Piracy + Malware

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#915]
URL you wish to be added:
`
https://winrar.fileplanet.com/
`
Why you believe this should be added:
winRAR is a paid sofware. Not availabel for free download
Add to list:
Piracy / Malware
Other info you think we should know:
Possibly distributing malware : [VIrusTotal](https://www.virustotal.com/gui/file/833064195b0c96bce9a8c00dc95df6bd9fce1092c1260ba0e877810bfc44b0aa)

**Comment by cryptogap** [comment]
Winrar is free but it has been added to malware
