### ISSUE TITLE
[Add request] Malware distribution

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#916]
URL you wish to be added:
`https://jamesnewbrain.com/`
Why you believe this should be added:
Malware distribution
Add to list:
Malware
Other info you think we should know:
[VirusTotal](https://www.virustotal.com/gui/file/a82541bf3e2232ae6cf1a4d410c8f0554bd4cff1accc10f90e629f4063142ca1)

**Comment by alanjacobmathew** [comment]
```
jytibarose.xyz/?sandy
https://offsebike.cyou/?sandy
``` 
[VirusTotal](https://www.virustotal.com/gui/file/38a48d0791effad1abd366c9f538d0eaef508b079c670cb1fe8d48d755fcffe7)

Distributing Malware

**Comment by cryptogap** [comment]
These have been added
