### ISSUE TITLE
[Add request] Redirector

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#917]
URL you wish to be added:
`https://insta24h.com/`
Why you believe this should be added:
redirects to a malware hosting site
Add to list:
redirector
Other info you think we should know:

**Comment by alanjacobmathew** [comment]
`https://primrvils.click`

Redirects to malware hosting 
Example
`https://primrvils.click/?open=df3c9be1966401335aa7bec56362&d=1&x=183&close=f66f157fc6afa&p=Adobe%20Photoshop%20Crack%202022%20V23.1.1.202%20Full%20Version`

**Comment by alanjacobmathew** [comment]
`http://162.243.164.175/`

Proof
```
http://162.243.164.175/?63a07a011f989=544d893fa927d23b4e6d0f0615d422be&63a07a011f992=183&63a07a011f994=1_adobe-photoshop-crack-2022-v23-1-1-202-full-version&gkss=178522&63a07a011f998=1
```

**Comment by alanjacobmathew** [comment]
```
https://redirlinkin2.click/?c=g
```
 
Redirects to Google. 
Used to scam `https://i.redd.it/kaj42krj6kda1.png`

**Comment by cryptogap** [comment]
`insta24h.com` has been added. We can not block IPs at this time
