### ISSUE TITLE
[Add request] Malware

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#918]
URL you wish to be added:
```
https://www.blendepr.org/
https://www.blendevr.org/
https://blender3d-software.net/
```
Why you believe this should be added:
Malware distribution through Google ads ads
Add to list:
Malware
Other info you think we should know:

https://www.bleepingcomputer.com/news/security/hackers-push-malware-via-google-search-ads-for-vlc-7-zip-ccleaner/

**Comment by cryptogap** [comment]
These have been added
