### ISSUE TITLE
[Add request] Pirate

### ISSUE THREAD

**Issue by alanjacobmathew** [blocklistproject/Lists#919]
URL you wish to be added:
```
https://free4pc.org/
https://piratepc.me/
https://crackedversion.com/
https://greencracks.com/
https://cracksoftwareguru.com/
https://abbaspc.net/


```
Why you believe this should be added:
Distributing Pirate software
Add to list:
Pirate
Other info you think we should know:

**Comment by cryptogap** [comment]
These have been added
