### ISSUE TITLE
www.storage.googleapis.com in phishing list

### ISSUE THREAD

**Issue by Homas** [blocklistproject/Lists#95]
URL you wish to be removed:
www.storage.googleapis.com

Why you believe this to be a false positive:
It's a google cloud storage. It contains a lot of stuff including malicious and can not be blocked on the domain level.

List it is on:
phishing

Other info you think we should know:
You may need to create a list of benign domains to avoid such blocks in the future.

**Comment by gap579137** [comment]
This has been fixed. Thank you
