### ISSUE TITLE
invalid domain "-sso.anbtr.com" in malware-list

### ISSUE THREAD

**Issue by tjay** [blocklistproject/Lists#963]
Although closed with #4  there is still a invalid domain in the malware list:

https://blocklistproject.github.io/Lists/alt-version/malware-nl.txt :
-sso.anbtr.com

**Comment by b-m-f** [comment]
Same in  https://blocklistproject.github.io/Lists/malware.txt and https://blocklistproject.github.io/Lists/abuse.txt

**Comment by iam-py-test** [comment]
This domain (oddly) does seem to exist: https://www.virustotal.com/gui/domain/-sso.anbtr.com/detection

**Comment by tjay** [comment]
probably not [(https://www.ietf.org/rfc/rfc1035.txt)](https://www.ietf.org/rfc/rfc1035.txt):
`They must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen.`

**Comment by tjay** [comment]
let me guess your hostsystem is windows?
but you are right https://toolbox.googleapps.com/apps/dig/ resolves it too .

so ist seems a valid domain (but not for linux/unix? systems) >> closed
