### ISSUE TITLE
[Remove Request] - Your lists need cleaning

### ISSUE THREAD

**Issue by moeng** [blocklistproject/Lists#988]
Hello!
I checked your hosts file, which you offer in the public domain. And I was able to identify many irrelevant entries:
http://nulledhosts.ruir.com/downloads/blocklistproject-gambling_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-fraud_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-everything_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-ads_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-abuse_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-smarttv_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-basic_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-tracking_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-scram_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-redirect_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-ransomware_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-porn_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-malware_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-crypto_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-drugs_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-facebook_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-phishing_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-piracy_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-tiktok_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-torrent_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-whatsapp_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-vaping_notresolved
http://nulledhosts.ruir.com/downloads/blocklistproject-adobe_notresolved
- list of addresses that are not defined in public DNS

http://nulledhosts.ruir.com/downloads/blocklistproject-gambling_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-fraud_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-everything_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-ads_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-abuse_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-basic_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-tracking_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-scram_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-redirect_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-ransomware_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-porn_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-malware_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-crypto_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-drugs_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-facebook_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-phishing_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-piracy_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-tiktok_excludedips
http://nulledhosts.ruir.com/downloads/blocklistproject-torrent_excludedips
- list of addresses that resolve to addresses excluded from public use by IANA. I suspect that these addresses will soon expire the lease. 

http://nulledhosts.ruir.com/ - the site was created only for personal fun.
Thank you and good luck!

**Comment by gap579137** [comment]
Working on getting them cleaned right now

**Comment by gap579137** [comment]
Done
